import em from '@$$emscript'
export const $U = em.$declare('COMPOSITE')

export function em$generate() {
    let out = $outfile('emm.distro.9305/REGS.hpp')
    out.addFile('../emm.9305/emm.distro.9305/REGS.hpp.txt')
    out.close()
}

// -------- GPIO TYPE -------- //

export interface GPIO_t {
    RegGPIOInputEn: $Reg
    RegGPIOOutputEn: $Reg
    RegGPIOPuEn: $Reg
    RegGPIOPdEn: $Reg
    RegGPIOOdEn: $Reg
    RegGPIOOutSel0: $Reg
    RegGPIOOutSel1: $Reg
    RegGPIOOutSel2: $Reg
    RegGPIOInpSel0: $Reg
    RegGPIOInpSel1: $Reg
    RegGPIOInpSel2: $Reg
    RegGPIOInpSel3: $Reg
    RegGPIODataOut: $Reg
    RegGPIODataOutSet: $Reg
    RegGPIODataOutClr: $Reg
    RegGPIODataIn: $Reg
    RegGPIOIRQPolarity: $Reg
    RegGPIOCfg: $Reg
}

// -------- GPIO CONSTANTS -------- //

export const REG_GPIO_INPUT_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_INPUT_EN_MASK: any = '0x00000FFFu'
export const GPIO_INPUT_EN_SHIFT: any = '0'
export const GPIO_INPUT_EN_MASK: any = '0x00000FFFu'
export const GPIO_INPUT_EN_BMASK: any = '0xFFFu'
export const REG_GPIO_OUTPUT_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OUTPUT_EN_MASK: any = '0x00000FFFu'
export const GPIO_OUTPUT_EN_SHIFT: any = '0'
export const GPIO_OUTPUT_EN_MASK: any = '0x00000FFFu'
export const GPIO_OUTPUT_EN_BMASK: any = '0xFFFu'
export const REG_GPIO_PU_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_PU_EN_MASK: any = '0x00000FFFu'
export const GPIO_PU_EN_SHIFT: any = '0'
export const GPIO_PU_EN_MASK: any = '0x00000FFFu'
export const GPIO_PU_EN_BMASK: any = '0xFFFu'
export const REG_GPIO_PD_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_PD_EN_MASK: any = '0x00000FFFu'
export const GPIO_PD_EN_SHIFT: any = '0'
export const GPIO_PD_EN_MASK: any = '0x00000FFFu'
export const GPIO_PD_EN_BMASK: any = '0xFFFu'
export const REG_GPIO_OD_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OD_EN_MASK: any = '0x00000F33u'
export const GPIO_OD_EN0_SHIFT: any = '0'
export const GPIO_OD_EN0_MASK: any = '0x00000001u'
export const GPIO_OD_EN0_BMASK: any = '0x1u'
export const GPIO_OD_EN1_SHIFT: any = '1'
export const GPIO_OD_EN1_MASK: any = '0x00000002u'
export const GPIO_OD_EN1_BMASK: any = '0x1u'
export const GPIO_OD_EN4_SHIFT: any = '4'
export const GPIO_OD_EN4_MASK: any = '0x00000010u'
export const GPIO_OD_EN4_BMASK: any = '0x1u'
export const GPIO_OD_EN5_SHIFT: any = '5'
export const GPIO_OD_EN5_MASK: any = '0x00000020u'
export const GPIO_OD_EN5_BMASK: any = '0x1u'
export const GPIO_OD_EN8_SHIFT: any = '8'
export const GPIO_OD_EN8_MASK: any = '0x00000100u'
export const GPIO_OD_EN8_BMASK: any = '0x1u'
export const GPIO_OD_EN9_SHIFT: any = '9'
export const GPIO_OD_EN9_MASK: any = '0x00000200u'
export const GPIO_OD_EN9_BMASK: any = '0x1u'
export const GPIO_OD_EN10_SHIFT: any = '10'
export const GPIO_OD_EN10_MASK: any = '0x00000400u'
export const GPIO_OD_EN10_BMASK: any = '0x1u'
export const GPIO_OD_EN11_SHIFT: any = '11'
export const GPIO_OD_EN11_MASK: any = '0x00000800u'
export const GPIO_OD_EN11_BMASK: any = '0x1u'
export const REG_GPIO_OUT_SEL0_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OUT_SEL0_MASK: any = '0x1F1F1F1Fu'
export const GPIO_OUT_SEL0_SHIFT: any = '0'
export const GPIO_OUT_SEL0_MASK: any = '0x0000001Fu'
export const GPIO_OUT_SEL0_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL1_SHIFT: any = '8'
export const GPIO_OUT_SEL1_MASK: any = '0x00001F00u'
export const GPIO_OUT_SEL1_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL2_SHIFT: any = '16'
export const GPIO_OUT_SEL2_MASK: any = '0x001F0000u'
export const GPIO_OUT_SEL2_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL3_SHIFT: any = '24'
export const GPIO_OUT_SEL3_MASK: any = '0x1F000000u'
export const GPIO_OUT_SEL3_BMASK: any = '0x1Fu'
export const REG_GPIO_OUT_SEL1_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OUT_SEL1_MASK: any = '0x1F1F1F1Fu'
export const GPIO_OUT_SEL4_SHIFT: any = '0'
export const GPIO_OUT_SEL4_MASK: any = '0x0000001Fu'
export const GPIO_OUT_SEL4_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL5_SHIFT: any = '8'
export const GPIO_OUT_SEL5_MASK: any = '0x00001F00u'
export const GPIO_OUT_SEL5_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL6_SHIFT: any = '16'
export const GPIO_OUT_SEL6_MASK: any = '0x001F0000u'
export const GPIO_OUT_SEL6_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL7_SHIFT: any = '24'
export const GPIO_OUT_SEL7_MASK: any = '0x1F000000u'
export const GPIO_OUT_SEL7_BMASK: any = '0x1Fu'
export const REG_GPIO_OUT_SEL2_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OUT_SEL2_MASK: any = '0x1F1F1F1Fu'
export const GPIO_OUT_SEL8_SHIFT: any = '0'
export const GPIO_OUT_SEL8_MASK: any = '0x0000001Fu'
export const GPIO_OUT_SEL8_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL9_SHIFT: any = '8'
export const GPIO_OUT_SEL9_MASK: any = '0x00001F00u'
export const GPIO_OUT_SEL9_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL10_SHIFT: any = '16'
export const GPIO_OUT_SEL10_MASK: any = '0x001F0000u'
export const GPIO_OUT_SEL10_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL11_SHIFT: any = '24'
export const GPIO_OUT_SEL11_MASK: any = '0x1F000000u'
export const GPIO_OUT_SEL11_BMASK: any = '0x1Fu'
export const REG_GPIO_INP_SEL0_RESET_VALUE: any = '0x0F0F0F0Fu'
export const REG_GPIO_INP_SEL0_MASK: any = '0x0F0F0F0Fu'
export const GPIO_IN_SEL_SS_CSN_SHIFT: any = '0'
export const GPIO_IN_SEL_SS_CSN_MASK: any = '0x0000000Fu'
export const GPIO_IN_SEL_SS_CSN_BMASK: any = '0xFu'
export const GPIO_IN_SEL_SS_SCK_SHIFT: any = '8'
export const GPIO_IN_SEL_SS_SCK_MASK: any = '0x00000F00u'
export const GPIO_IN_SEL_SS_SCK_BMASK: any = '0xFu'
export const GPIO_IN_SEL_SS_MOSI_SHIFT: any = '16'
export const GPIO_IN_SEL_SS_MOSI_MASK: any = '0x000F0000u'
export const GPIO_IN_SEL_SS_MOSI_BMASK: any = '0xFu'
export const GPIO_IN_SEL_SM_MISO_SHIFT: any = '24'
export const GPIO_IN_SEL_SM_MISO_MASK: any = '0x0F000000u'
export const GPIO_IN_SEL_SM_MISO_BMASK: any = '0xFu'
export const REG_GPIO_INP_SEL1_RESET_VALUE: any = '0x0F0F0F0Fu'
export const REG_GPIO_INP_SEL1_MASK: any = '0x0F0F0F0Fu'
export const GPIO_IN_SEL_UART_RDX_SHIFT: any = '0'
export const GPIO_IN_SEL_UART_RDX_MASK: any = '0x0000000Fu'
export const GPIO_IN_SEL_UART_RDX_BMASK: any = '0xFu'
export const GPIO_IN_SEL_UART_CTS_SHIFT: any = '8'
export const GPIO_IN_SEL_UART_CTS_MASK: any = '0x00000F00u'
export const GPIO_IN_SEL_UART_CTS_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM2_START_SHIFT: any = '16'
export const GPIO_IN_SEL_TIM2_START_MASK: any = '0x000F0000u'
export const GPIO_IN_SEL_TIM2_START_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM2_CAP_SHIFT: any = '24'
export const GPIO_IN_SEL_TIM2_CAP_MASK: any = '0x0F000000u'
export const GPIO_IN_SEL_TIM2_CAP_BMASK: any = '0xFu'
export const REG_GPIO_INP_SEL2_RESET_VALUE: any = '0x0F0F0F0Fu'
export const REG_GPIO_INP_SEL2_MASK: any = '0x0F0F0F0Fu'
export const GPIO_IN_SEL_TIM3_START_SHIFT: any = '0'
export const GPIO_IN_SEL_TIM3_START_MASK: any = '0x0000000Fu'
export const GPIO_IN_SEL_TIM3_START_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM3_CAP_SHIFT: any = '8'
export const GPIO_IN_SEL_TIM3_CAP_MASK: any = '0x00000F00u'
export const GPIO_IN_SEL_TIM3_CAP_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM2_CLK_SHIFT: any = '16'
export const GPIO_IN_SEL_TIM2_CLK_MASK: any = '0x000F0000u'
export const GPIO_IN_SEL_TIM2_CLK_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM3_CLK_SHIFT: any = '24'
export const GPIO_IN_SEL_TIM3_CLK_MASK: any = '0x0F000000u'
export const GPIO_IN_SEL_TIM3_CLK_BMASK: any = '0xFu'
export const REG_GPIO_INP_SEL3_RESET_VALUE: any = '0x000F0F0Fu'
export const REG_GPIO_INP_SEL3_MASK: any = '0x000F0F0Fu'
export const GPIO_IN_SEL_I2S_SCLK_SHIFT: any = '0'
export const GPIO_IN_SEL_I2S_SCLK_MASK: any = '0x0000000Fu'
export const GPIO_IN_SEL_I2S_SCLK_BMASK: any = '0xFu'
export const GPIO_IN_SEL_I2S_FSYNC_SHIFT: any = '8'
export const GPIO_IN_SEL_I2S_FSYNC_MASK: any = '0x00000F00u'
export const GPIO_IN_SEL_I2S_FSYNC_BMASK: any = '0xFu'
export const GPIO_IN_SEL_I2S_SDATA_SHIFT: any = '16'
export const GPIO_IN_SEL_I2S_SDATA_MASK: any = '0x000F0000u'
export const GPIO_IN_SEL_I2S_SDATA_BMASK: any = '0xFu'
export const REG_GPIO_DATA_OUT_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_DATA_OUT_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_SHIFT: any = '0'
export const GPIO_DATA_OUT_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_BMASK: any = '0xFFFu'
export const REG_GPIO_DATA_OUT_SET_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_DATA_OUT_SET_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_SET_SHIFT: any = '0'
export const GPIO_DATA_OUT_SET_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_SET_BMASK: any = '0xFFFu'
export const REG_GPIO_DATA_OUT_CLR_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_DATA_OUT_CLR_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_CLR_SHIFT: any = '0'
export const GPIO_DATA_OUT_CLR_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_CLR_BMASK: any = '0xFFFu'
export const REG_GPIO_DATA_IN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_DATA_IN_MASK: any = '0x00000FFFu'
export const GPIO_DATA_IN_SHIFT: any = '0'
export const GPIO_DATA_IN_MASK: any = '0x00000FFFu'
export const GPIO_DATA_IN_BMASK: any = '0xFFFu'
export const REG_GPIO_IRQ_POLARITY_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_IRQ_POLARITY_MASK: any = '0x00000FFFu'
export const GPIO_IRQ_POLARITY_SHIFT: any = '0'
export const GPIO_IRQ_POLARITY_MASK: any = '0x00000FFFu'
export const GPIO_IRQ_POLARITY_BMASK: any = '0xFFFu'
export const REG_GPIO_CFG_RESET_VALUE: any = '0x00180000u'
export const REG_GPIO_CFG_MASK: any = '0x003F000Fu'
export const GPIO_RESERVED_SHIFT: any = '0'
export const GPIO_RESERVED_MASK: any = '0x00000001u'
export const GPIO_RESERVED_BMASK: any = '0x1u'
export const GPIO_HIGH_DRIVE_SHIFT: any = '1'
export const GPIO_HIGH_DRIVE_MASK: any = '0x0000000Eu'
export const GPIO_HIGH_DRIVE_BMASK: any = '0x7u'
export const GPIO_USB_MODE_SHIFT: any = '16'
export const GPIO_USB_MODE_MASK: any = '0x00010000u'
export const GPIO_USB_MODE_BMASK: any = '0x1u'
export const GPIO_USB_SLEW_RATE_SHIFT: any = '17'
export const GPIO_USB_SLEW_RATE_MASK: any = '0x00020000u'
export const GPIO_USB_SLEW_RATE_BMASK: any = '0x1u'
export const GPIO_USB_HIGH_DRIVE_SHIFT: any = '18'
export const GPIO_USB_HIGH_DRIVE_MASK: any = '0x00040000u'
export const GPIO_USB_HIGH_DRIVE_BMASK: any = '0x1u'
export const GPIO_USB_RPU1_EN_N_SHIFT: any = '19'
export const GPIO_USB_RPU1_EN_N_MASK: any = '0x00080000u'
export const GPIO_USB_RPU1_EN_N_BMASK: any = '0x1u'
export const GPIO_USB_RPU2_EN_N_SHIFT: any = '20'
export const GPIO_USB_RPU2_EN_N_MASK: any = '0x00100000u'
export const GPIO_USB_RPU2_EN_N_BMASK: any = '0x1u'
export const GPIO_USB_SUSP_N_SHIFT: any = '21'
export const GPIO_USB_SUSP_N_MASK: any = '0x00200000u'
export const GPIO_USB_SUSP_N_BMASK: any = '0x1u'

// -------- UART TYPE -------- //

export interface UART_t {
    RegUARTCfg: $Reg
    RegUARTCtrl: $Reg
    RegUARTStat: $Reg
    RegUARTBaudRate: $Reg
    RegUARTRxFIFO1B: $Reg
    RegUARTRxFIFO2B: $Reg
    RegUARTRxFIFO3B: $Reg
    RegUARTRxFIFO4B: $Reg
    RegUARTTxFIFO1B: $Reg
    RegUARTTxFIFO2B: $Reg
    RegUARTTxFIFO3B: $Reg
    RegUARTTxFIFO4B: $Reg
    RegUARTFIFOCfg: $Reg
    RegUARTFIFOCtrl: $Reg
    RegUARTFIFOStat: $Reg
}

// -------- UART CONSTANTS -------- //

export const REG_UART_CFG_RESET_VALUE: any = '0x00000000u'
export const REG_UART_CFG_MASK: any = '0x0000003Fu'
export const UART_MSB_FIRST_SHIFT: any = '0'
export const UART_MSB_FIRST_MASK: any = '0x00000001u'
export const UART_MSB_FIRST_BMASK: any = '0x1u'
export const UART_PARITY_MODE_SHIFT: any = '1'
export const UART_PARITY_MODE_MASK: any = '0x00000002u'
export const UART_PARITY_MODE_BMASK: any = '0x1u'
export const UART_EVEN_PARITY_SHIFT: any = '2'
export const UART_EVEN_PARITY_MASK: any = '0x00000004u'
export const UART_EVEN_PARITY_BMASK: any = '0x1u'
export const UART_FLOW_CTRL_EN_SHIFT: any = '3'
export const UART_FLOW_CTRL_EN_MASK: any = '0x00000008u'
export const UART_FLOW_CTRL_EN_BMASK: any = '0x1u'
export const UART_MAJORITY_DIS_SHIFT: any = '4'
export const UART_MAJORITY_DIS_MASK: any = '0x00000010u'
export const UART_MAJORITY_DIS_BMASK: any = '0x1u'
export const UART_LOOP_BACK_EN_SHIFT: any = '5'
export const UART_LOOP_BACK_EN_MASK: any = '0x00000020u'
export const UART_LOOP_BACK_EN_BMASK: any = '0x1u'
export const REG_UART_CTRL_RESET_VALUE: any = '0x00000000u'
export const REG_UART_CTRL_MASK: any = '0x00000103u'
export const UART_RX_EN_SHIFT: any = '0'
export const UART_RX_EN_MASK: any = '0x00000001u'
export const UART_RX_EN_BMASK: any = '0x1u'
export const UART_TX_EN_SHIFT: any = '1'
export const UART_TX_EN_MASK: any = '0x00000002u'
export const UART_TX_EN_BMASK: any = '0x1u'
export const UART_FORCE_RTS_SHIFT: any = '8'
export const UART_FORCE_RTS_MASK: any = '0x00000100u'
export const UART_FORCE_RTS_BMASK: any = '0x1u'
export const REG_UART_STAT_RESET_VALUE: any = '0x00000000u'
export const REG_UART_STAT_MASK: any = '0x00000003u'
export const UART_RX_BUSY_SHIFT: any = '0'
export const UART_RX_BUSY_MASK: any = '0x00000001u'
export const UART_RX_BUSY_BMASK: any = '0x1u'
export const UART_TX_BUSY_SHIFT: any = '1'
export const UART_TX_BUSY_MASK: any = '0x00000002u'
export const UART_TX_BUSY_BMASK: any = '0x1u'
export const REG_UART_BAUD_RATE_RESET_VALUE: any = '0x0D000010u'
export const REG_UART_BAUD_RATE_MASK: any = '0x1F003FFFu'
export const UART_CLOCK_DIV_SHIFT: any = '0'
export const UART_CLOCK_DIV_MASK: any = '0x00003FFFu'
export const UART_CLOCK_DIV_BMASK: any = '0x3FFFu'
export const UART_OVERSAMPLING_SHIFT: any = '24'
export const UART_OVERSAMPLING_MASK: any = '0x1F000000u'
export const UART_OVERSAMPLING_BMASK: any = '0x1Fu'
export const REG_UART_RX_FIFO_1B_RESET_VALUE: any = '0x00000000u'
export const REG_UART_RX_FIFO_1B_MASK: any = '0x000000FFu'
export const UART_RX_FIFO_1B_SHIFT: any = '0'
export const UART_RX_FIFO_1B_MASK: any = '0x000000FFu'
export const UART_RX_FIFO_1B_BMASK: any = '0xFFu'
export const REG_UART_RX_FIFO_2B_RESET_VALUE: any = '0x00000000u'
export const REG_UART_RX_FIFO_2B_MASK: any = '0x0000FFFFu'
export const UART_RX_FIFO_2B_SHIFT: any = '0'
export const UART_RX_FIFO_2B_MASK: any = '0x0000FFFFu'
export const UART_RX_FIFO_2B_BMASK: any = '0xFFFFu'
export const REG_UART_RX_FIFO_3B_RESET_VALUE: any = '0x00000000u'
export const REG_UART_RX_FIFO_3B_MASK: any = '0x00FFFFFFu'
export const UART_RX_FIFO_3B_SHIFT: any = '0'
export const UART_RX_FIFO_3B_MASK: any = '0x00FFFFFFu'
export const UART_RX_FIFO_3B_BMASK: any = '0xFFFFFFu'
export const REG_UART_RX_FIFO_4B_RESET_VALUE: any = '0x00000000u'
export const REG_UART_RX_FIFO_4B_MASK: any = '0xFFFFFFFFu'
export const UART_RX_FIFO_4B_SHIFT: any = '0'
export const UART_RX_FIFO_4B_MASK: any = '0xFFFFFFFFu'
export const UART_RX_FIFO_4B_BMASK: any = '0xFFFFFFFFu'
export const REG_UART_TX_FIFO_1B_RESET_VALUE: any = '0x00000000u'
export const REG_UART_TX_FIFO_1B_MASK: any = '0x000000FFu'
export const UART_TX_FIFO_1B_SHIFT: any = '0'
export const UART_TX_FIFO_1B_MASK: any = '0x000000FFu'
export const UART_TX_FIFO_1B_BMASK: any = '0xFFu'
export const REG_UART_TX_FIFO_2B_RESET_VALUE: any = '0x00000000u'
export const REG_UART_TX_FIFO_2B_MASK: any = '0x0000FFFFu'
export const UART_TX_FIFO_2B_SHIFT: any = '0'
export const UART_TX_FIFO_2B_MASK: any = '0x0000FFFFu'
export const UART_TX_FIFO_2B_BMASK: any = '0xFFFFu'
export const REG_UART_TX_FIFO_3B_RESET_VALUE: any = '0x00000000u'
export const REG_UART_TX_FIFO_3B_MASK: any = '0x00FFFFFFu'
export const UART_TX_FIFO_3B_SHIFT: any = '0'
export const UART_TX_FIFO_3B_MASK: any = '0x00FFFFFFu'
export const UART_TX_FIFO_3B_BMASK: any = '0xFFFFFFu'
export const REG_UART_TX_FIFO_4B_RESET_VALUE: any = '0x00000000u'
export const REG_UART_TX_FIFO_4B_MASK: any = '0xFFFFFFFFu'
export const UART_TX_FIFO_4B_SHIFT: any = '0'
export const UART_TX_FIFO_4B_MASK: any = '0xFFFFFFFFu'
export const UART_TX_FIFO_4B_BMASK: any = '0xFFFFFFFFu'
export const REG_UART_FIFO_CFG_RESET_VALUE: any = '0x00000808u'
export const REG_UART_FIFO_CFG_MASK: any = '0x00001F1Fu'
export const UART_TX_FIFO_LIMIT_SHIFT: any = '0'
export const UART_TX_FIFO_LIMIT_MASK: any = '0x0000001Fu'
export const UART_TX_FIFO_LIMIT_BMASK: any = '0x1Fu'
export const UART_RX_FIFO_LIMIT_SHIFT: any = '8'
export const UART_RX_FIFO_LIMIT_MASK: any = '0x00001F00u'
export const UART_RX_FIFO_LIMIT_BMASK: any = '0x1Fu'
export const REG_UART_FIFO_CTRL_RESET_VALUE: any = '0x00000000u'
export const REG_UART_FIFO_CTRL_MASK: any = '0x00000003u'
export const UART_TX_FIFO_FLUSH_SHIFT: any = '0'
export const UART_TX_FIFO_FLUSH_MASK: any = '0x00000001u'
export const UART_TX_FIFO_FLUSH_BMASK: any = '0x1u'
export const UART_RX_FIFO_FLUSH_SHIFT: any = '1'
export const UART_RX_FIFO_FLUSH_MASK: any = '0x00000002u'
export const UART_RX_FIFO_FLUSH_BMASK: any = '0x1u'
export const REG_UART_FIFO_STAT_RESET_VALUE: any = '0x00000000u'
export const REG_UART_FIFO_STAT_MASK: any = '0x7F7F0077u'
export const UART_TX_FIFO_EMPTY_SHIFT: any = '0'
export const UART_TX_FIFO_EMPTY_MASK: any = '0x00000001u'
export const UART_TX_FIFO_EMPTY_BMASK: any = '0x1u'
export const UART_TX_FIFO_LIMIT_DET_SHIFT: any = '1'
export const UART_TX_FIFO_LIMIT_DET_MASK: any = '0x00000002u'
export const UART_TX_FIFO_LIMIT_DET_BMASK: any = '0x1u'
export const UART_TX_FIFO_FULL_SHIFT: any = '2'
export const UART_TX_FIFO_FULL_MASK: any = '0x00000004u'
export const UART_TX_FIFO_FULL_BMASK: any = '0x1u'
export const UART_RX_FIFO_EMPTY_SHIFT: any = '4'
export const UART_RX_FIFO_EMPTY_MASK: any = '0x00000010u'
export const UART_RX_FIFO_EMPTY_BMASK: any = '0x1u'
export const UART_RX_FIFO_LIMIT_DET_SHIFT: any = '5'
export const UART_RX_FIFO_LIMIT_DET_MASK: any = '0x00000020u'
export const UART_RX_FIFO_LIMIT_DET_BMASK: any = '0x1u'
export const UART_RX_FIFO_FULL_SHIFT: any = '6'
export const UART_RX_FIFO_FULL_MASK: any = '0x00000040u'
export const UART_RX_FIFO_FULL_BMASK: any = '0x1u'
export const UART_TX_FIFO_NUM_BYTES_SHIFT: any = '16'
export const UART_TX_FIFO_NUM_BYTES_MASK: any = '0x007F0000u'
export const UART_TX_FIFO_NUM_BYTES_BMASK: any = '0x7Fu'
export const UART_RX_FIFO_NUM_BYTES_SHIFT: any = '24'
export const UART_RX_FIFO_NUM_BYTES_MASK: any = '0x7F000000u'
export const UART_RX_FIFO_NUM_BYTES_BMASK: any = '0x7Fu'

// -------- INSTANCES -------- //

export const GPIO = {} as GPIO_t
export const UART = {} as UART_t
