import em from '@$$emscript'
export const $U = em.$declare('COMPOSITE')

export function em$generate() {
    let out = $outfile('emm.distro.9305/REGS.hpp')
    out.addFile('../emm.9305/emm.distro.9305/REGS.hpp.txt')
    out.close()
}

// -------- GPIO TYPE -------- //

export interface GPIO_t {
    RegGPIOInputEn: $Reg
    RegGPIOOutputEn: $Reg
    RegGPIOPuEn: $Reg
    RegGPIOPdEn: $Reg
    RegGPIOOdEn: $Reg
    RegGPIOOutSel0: $Reg
    RegGPIOOutSel1: $Reg
    RegGPIOOutSel2: $Reg
    RegGPIOInpSel0: $Reg
    RegGPIOInpSel1: $Reg
    RegGPIOInpSel2: $Reg
    RegGPIOInpSel3: $Reg
    RegGPIODataOut: $Reg
    RegGPIODataOutSet: $Reg
    RegGPIODataOutClr: $Reg
    RegGPIODataIn: $Reg
    RegGPIOIRQPolarity: $Reg
    RegGPIOCfg: $Reg
}

// -------- GPIO CONSTANTS -------- //

export const REG_GPIO_INPUT_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_INPUT_EN_MASK: any = '0x00000FFFu'
export const GPIO_INPUT_EN_SHIFT: any = '0'
export const GPIO_INPUT_EN_MASK: any = '0x00000FFFu'
export const GPIO_INPUT_EN_BMASK: any = '0xFFFu'
export const REG_GPIO_OUTPUT_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OUTPUT_EN_MASK: any = '0x00000FFFu'
export const GPIO_OUTPUT_EN_SHIFT: any = '0'
export const GPIO_OUTPUT_EN_MASK: any = '0x00000FFFu'
export const GPIO_OUTPUT_EN_BMASK: any = '0xFFFu'
export const REG_GPIO_PU_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_PU_EN_MASK: any = '0x00000FFFu'
export const GPIO_PU_EN_SHIFT: any = '0'
export const GPIO_PU_EN_MASK: any = '0x00000FFFu'
export const GPIO_PU_EN_BMASK: any = '0xFFFu'
export const REG_GPIO_PD_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_PD_EN_MASK: any = '0x00000FFFu'
export const GPIO_PD_EN_SHIFT: any = '0'
export const GPIO_PD_EN_MASK: any = '0x00000FFFu'
export const GPIO_PD_EN_BMASK: any = '0xFFFu'
export const REG_GPIO_OD_EN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OD_EN_MASK: any = '0x00000F33u'
export const GPIO_OD_EN0_SHIFT: any = '0'
export const GPIO_OD_EN0_MASK: any = '0x00000001u'
export const GPIO_OD_EN0_BMASK: any = '0x1u'
export const GPIO_OD_EN1_SHIFT: any = '1'
export const GPIO_OD_EN1_MASK: any = '0x00000002u'
export const GPIO_OD_EN1_BMASK: any = '0x1u'
export const GPIO_OD_EN4_SHIFT: any = '4'
export const GPIO_OD_EN4_MASK: any = '0x00000010u'
export const GPIO_OD_EN4_BMASK: any = '0x1u'
export const GPIO_OD_EN5_SHIFT: any = '5'
export const GPIO_OD_EN5_MASK: any = '0x00000020u'
export const GPIO_OD_EN5_BMASK: any = '0x1u'
export const GPIO_OD_EN8_SHIFT: any = '8'
export const GPIO_OD_EN8_MASK: any = '0x00000100u'
export const GPIO_OD_EN8_BMASK: any = '0x1u'
export const GPIO_OD_EN9_SHIFT: any = '9'
export const GPIO_OD_EN9_MASK: any = '0x00000200u'
export const GPIO_OD_EN9_BMASK: any = '0x1u'
export const GPIO_OD_EN10_SHIFT: any = '10'
export const GPIO_OD_EN10_MASK: any = '0x00000400u'
export const GPIO_OD_EN10_BMASK: any = '0x1u'
export const GPIO_OD_EN11_SHIFT: any = '11'
export const GPIO_OD_EN11_MASK: any = '0x00000800u'
export const GPIO_OD_EN11_BMASK: any = '0x1u'
export const REG_GPIO_OUT_SEL0_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OUT_SEL0_MASK: any = '0x1F1F1F1Fu'
export const GPIO_OUT_SEL0_SHIFT: any = '0'
export const GPIO_OUT_SEL0_MASK: any = '0x0000001Fu'
export const GPIO_OUT_SEL0_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL1_SHIFT: any = '8'
export const GPIO_OUT_SEL1_MASK: any = '0x00001F00u'
export const GPIO_OUT_SEL1_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL2_SHIFT: any = '16'
export const GPIO_OUT_SEL2_MASK: any = '0x001F0000u'
export const GPIO_OUT_SEL2_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL3_SHIFT: any = '24'
export const GPIO_OUT_SEL3_MASK: any = '0x1F000000u'
export const GPIO_OUT_SEL3_BMASK: any = '0x1Fu'
export const REG_GPIO_OUT_SEL1_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OUT_SEL1_MASK: any = '0x1F1F1F1Fu'
export const GPIO_OUT_SEL4_SHIFT: any = '0'
export const GPIO_OUT_SEL4_MASK: any = '0x0000001Fu'
export const GPIO_OUT_SEL4_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL5_SHIFT: any = '8'
export const GPIO_OUT_SEL5_MASK: any = '0x00001F00u'
export const GPIO_OUT_SEL5_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL6_SHIFT: any = '16'
export const GPIO_OUT_SEL6_MASK: any = '0x001F0000u'
export const GPIO_OUT_SEL6_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL7_SHIFT: any = '24'
export const GPIO_OUT_SEL7_MASK: any = '0x1F000000u'
export const GPIO_OUT_SEL7_BMASK: any = '0x1Fu'
export const REG_GPIO_OUT_SEL2_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_OUT_SEL2_MASK: any = '0x1F1F1F1Fu'
export const GPIO_OUT_SEL8_SHIFT: any = '0'
export const GPIO_OUT_SEL8_MASK: any = '0x0000001Fu'
export const GPIO_OUT_SEL8_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL9_SHIFT: any = '8'
export const GPIO_OUT_SEL9_MASK: any = '0x00001F00u'
export const GPIO_OUT_SEL9_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL10_SHIFT: any = '16'
export const GPIO_OUT_SEL10_MASK: any = '0x001F0000u'
export const GPIO_OUT_SEL10_BMASK: any = '0x1Fu'
export const GPIO_OUT_SEL11_SHIFT: any = '24'
export const GPIO_OUT_SEL11_MASK: any = '0x1F000000u'
export const GPIO_OUT_SEL11_BMASK: any = '0x1Fu'
export const REG_GPIO_INP_SEL0_RESET_VALUE: any = '0x0F0F0F0Fu'
export const REG_GPIO_INP_SEL0_MASK: any = '0x0F0F0F0Fu'
export const GPIO_IN_SEL_SS_CSN_SHIFT: any = '0'
export const GPIO_IN_SEL_SS_CSN_MASK: any = '0x0000000Fu'
export const GPIO_IN_SEL_SS_CSN_BMASK: any = '0xFu'
export const GPIO_IN_SEL_SS_SCK_SHIFT: any = '8'
export const GPIO_IN_SEL_SS_SCK_MASK: any = '0x00000F00u'
export const GPIO_IN_SEL_SS_SCK_BMASK: any = '0xFu'
export const GPIO_IN_SEL_SS_MOSI_SHIFT: any = '16'
export const GPIO_IN_SEL_SS_MOSI_MASK: any = '0x000F0000u'
export const GPIO_IN_SEL_SS_MOSI_BMASK: any = '0xFu'
export const GPIO_IN_SEL_SM_MISO_SHIFT: any = '24'
export const GPIO_IN_SEL_SM_MISO_MASK: any = '0x0F000000u'
export const GPIO_IN_SEL_SM_MISO_BMASK: any = '0xFu'
export const REG_GPIO_INP_SEL1_RESET_VALUE: any = '0x0F0F0F0Fu'
export const REG_GPIO_INP_SEL1_MASK: any = '0x0F0F0F0Fu'
export const GPIO_IN_SEL_UART_RDX_SHIFT: any = '0'
export const GPIO_IN_SEL_UART_RDX_MASK: any = '0x0000000Fu'
export const GPIO_IN_SEL_UART_RDX_BMASK: any = '0xFu'
export const GPIO_IN_SEL_UART_CTS_SHIFT: any = '8'
export const GPIO_IN_SEL_UART_CTS_MASK: any = '0x00000F00u'
export const GPIO_IN_SEL_UART_CTS_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM2_START_SHIFT: any = '16'
export const GPIO_IN_SEL_TIM2_START_MASK: any = '0x000F0000u'
export const GPIO_IN_SEL_TIM2_START_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM2_CAP_SHIFT: any = '24'
export const GPIO_IN_SEL_TIM2_CAP_MASK: any = '0x0F000000u'
export const GPIO_IN_SEL_TIM2_CAP_BMASK: any = '0xFu'
export const REG_GPIO_INP_SEL2_RESET_VALUE: any = '0x0F0F0F0Fu'
export const REG_GPIO_INP_SEL2_MASK: any = '0x0F0F0F0Fu'
export const GPIO_IN_SEL_TIM3_START_SHIFT: any = '0'
export const GPIO_IN_SEL_TIM3_START_MASK: any = '0x0000000Fu'
export const GPIO_IN_SEL_TIM3_START_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM3_CAP_SHIFT: any = '8'
export const GPIO_IN_SEL_TIM3_CAP_MASK: any = '0x00000F00u'
export const GPIO_IN_SEL_TIM3_CAP_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM2_CLK_SHIFT: any = '16'
export const GPIO_IN_SEL_TIM2_CLK_MASK: any = '0x000F0000u'
export const GPIO_IN_SEL_TIM2_CLK_BMASK: any = '0xFu'
export const GPIO_IN_SEL_TIM3_CLK_SHIFT: any = '24'
export const GPIO_IN_SEL_TIM3_CLK_MASK: any = '0x0F000000u'
export const GPIO_IN_SEL_TIM3_CLK_BMASK: any = '0xFu'
export const REG_GPIO_INP_SEL3_RESET_VALUE: any = '0x000F0F0Fu'
export const REG_GPIO_INP_SEL3_MASK: any = '0x000F0F0Fu'
export const GPIO_IN_SEL_I2S_SCLK_SHIFT: any = '0'
export const GPIO_IN_SEL_I2S_SCLK_MASK: any = '0x0000000Fu'
export const GPIO_IN_SEL_I2S_SCLK_BMASK: any = '0xFu'
export const GPIO_IN_SEL_I2S_FSYNC_SHIFT: any = '8'
export const GPIO_IN_SEL_I2S_FSYNC_MASK: any = '0x00000F00u'
export const GPIO_IN_SEL_I2S_FSYNC_BMASK: any = '0xFu'
export const GPIO_IN_SEL_I2S_SDATA_SHIFT: any = '16'
export const GPIO_IN_SEL_I2S_SDATA_MASK: any = '0x000F0000u'
export const GPIO_IN_SEL_I2S_SDATA_BMASK: any = '0xFu'
export const REG_GPIO_DATA_OUT_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_DATA_OUT_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_SHIFT: any = '0'
export const GPIO_DATA_OUT_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_BMASK: any = '0xFFFu'
export const REG_GPIO_DATA_OUT_SET_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_DATA_OUT_SET_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_SET_SHIFT: any = '0'
export const GPIO_DATA_OUT_SET_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_SET_BMASK: any = '0xFFFu'
export const REG_GPIO_DATA_OUT_CLR_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_DATA_OUT_CLR_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_CLR_SHIFT: any = '0'
export const GPIO_DATA_OUT_CLR_MASK: any = '0x00000FFFu'
export const GPIO_DATA_OUT_CLR_BMASK: any = '0xFFFu'
export const REG_GPIO_DATA_IN_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_DATA_IN_MASK: any = '0x00000FFFu'
export const GPIO_DATA_IN_SHIFT: any = '0'
export const GPIO_DATA_IN_MASK: any = '0x00000FFFu'
export const GPIO_DATA_IN_BMASK: any = '0xFFFu'
export const REG_GPIO_IRQ_POLARITY_RESET_VALUE: any = '0x00000000u'
export const REG_GPIO_IRQ_POLARITY_MASK: any = '0x00000FFFu'
export const GPIO_IRQ_POLARITY_SHIFT: any = '0'
export const GPIO_IRQ_POLARITY_MASK: any = '0x00000FFFu'
export const GPIO_IRQ_POLARITY_BMASK: any = '0xFFFu'
export const REG_GPIO_CFG_RESET_VALUE: any = '0x00180000u'
export const REG_GPIO_CFG_MASK: any = '0x003F000Fu'
export const GPIO_RESERVED_SHIFT: any = '0'
export const GPIO_RESERVED_MASK: any = '0x00000001u'
export const GPIO_RESERVED_BMASK: any = '0x1u'
export const GPIO_HIGH_DRIVE_SHIFT: any = '1'
export const GPIO_HIGH_DRIVE_MASK: any = '0x0000000Eu'
export const GPIO_HIGH_DRIVE_BMASK: any = '0x7u'
export const GPIO_USB_MODE_SHIFT: any = '16'
export const GPIO_USB_MODE_MASK: any = '0x00010000u'
export const GPIO_USB_MODE_BMASK: any = '0x1u'
export const GPIO_USB_SLEW_RATE_SHIFT: any = '17'
export const GPIO_USB_SLEW_RATE_MASK: any = '0x00020000u'
export const GPIO_USB_SLEW_RATE_BMASK: any = '0x1u'
export const GPIO_USB_HIGH_DRIVE_SHIFT: any = '18'
export const GPIO_USB_HIGH_DRIVE_MASK: any = '0x00040000u'
export const GPIO_USB_HIGH_DRIVE_BMASK: any = '0x1u'
export const GPIO_USB_RPU1_EN_N_SHIFT: any = '19'
export const GPIO_USB_RPU1_EN_N_MASK: any = '0x00080000u'
export const GPIO_USB_RPU1_EN_N_BMASK: any = '0x1u'
export const GPIO_USB_RPU2_EN_N_SHIFT: any = '20'
export const GPIO_USB_RPU2_EN_N_MASK: any = '0x00100000u'
export const GPIO_USB_RPU2_EN_N_BMASK: any = '0x1u'
export const GPIO_USB_SUSP_N_SHIFT: any = '21'
export const GPIO_USB_SUSP_N_MASK: any = '0x00200000u'
export const GPIO_USB_SUSP_N_BMASK: any = '0x1u'

// -------- INSTANCES -------- //

export const GPIO = {} as GPIO_t
