import em from '@$$emscript'
export const $U = em.$declare('COMPOSITE')

export function em$generate() {
    let out = $outfile('silabs.distro.efr32x/REGS.hpp')
    out.addFile('../silabs.efr32x/silabs.distro.efr32x/REGS.hpp.txt')
    out.close()
}

// -------- CMU -------- //

export interface CMU_t {
    IPVERSION: $Reg
    STATUS: $Reg
    LOCK: $Reg
    WDOGLOCK: $Reg
    IF: $Reg
    IEN: $Reg
    CALCMD: $Reg
    CALCTRL: $Reg
    CALCNT: $Reg
    CLKEN0: $Reg
    CLKEN1: $Reg
    SYSCLKCTRL: $Reg
    TRACECLKCTRL: $Reg
    EXPORTCLKCTRL: $Reg
    DPLLREFCLKCTRL: $Reg
    EM01GRPACLKCTRL: $Reg
    EM01GRPBCLKCTRL: $Reg
    EM23GRPACLKCTRL: $Reg
    EM4GRPACLKCTRL: $Reg
    IADCCLKCTRL: $Reg
    WDOG0CLKCTRL: $Reg
    EUART0CLKCTRL: $Reg
    RTCCCLKCTRL: $Reg
    PRORTCCLKCTRL: $Reg
    CRYPTOACCCLKCTRL: $Reg
    RADIOCLKCTRL: $Reg
    IPVERSION_SET: $Reg
    STATUS_SET: $Reg
    LOCK_SET: $Reg
    WDOGLOCK_SET: $Reg
    IF_SET: $Reg
    IEN_SET: $Reg
    CALCMD_SET: $Reg
    CALCTRL_SET: $Reg
    CALCNT_SET: $Reg
    CLKEN0_SET: $Reg
    CLKEN1_SET: $Reg
    SYSCLKCTRL_SET: $Reg
    TRACECLKCTRL_SET: $Reg
    EXPORTCLKCTRL_SET: $Reg
    DPLLREFCLKCTRL_SET: $Reg
    EM01GRPACLKCTRL_SET: $Reg
    EM01GRPBCLKCTRL_SET: $Reg
    EM23GRPACLKCTRL_SET: $Reg
    EM4GRPACLKCTRL_SET: $Reg
    IADCCLKCTRL_SET: $Reg
    WDOG0CLKCTRL_SET: $Reg
    EUART0CLKCTRL_SET: $Reg
    RTCCCLKCTRL_SET: $Reg
    PRORTCCLKCTRL_SET: $Reg
    CRYPTOACCCLKCTRL_SET: $Reg
    RADIOCLKCTRL_SET: $Reg
    IPVERSION_CLR: $Reg
    STATUS_CLR: $Reg
    LOCK_CLR: $Reg
    WDOGLOCK_CLR: $Reg
    IF_CLR: $Reg
    IEN_CLR: $Reg
    CALCMD_CLR: $Reg
    CALCTRL_CLR: $Reg
    CALCNT_CLR: $Reg
    CLKEN0_CLR: $Reg
    CLKEN1_CLR: $Reg
    SYSCLKCTRL_CLR: $Reg
    TRACECLKCTRL_CLR: $Reg
    EXPORTCLKCTRL_CLR: $Reg
    DPLLREFCLKCTRL_CLR: $Reg
    EM01GRPACLKCTRL_CLR: $Reg
    EM01GRPBCLKCTRL_CLR: $Reg
    EM23GRPACLKCTRL_CLR: $Reg
    EM4GRPACLKCTRL_CLR: $Reg
    IADCCLKCTRL_CLR: $Reg
    WDOG0CLKCTRL_CLR: $Reg
    EUART0CLKCTRL_CLR: $Reg
    RTCCCLKCTRL_CLR: $Reg
    PRORTCCLKCTRL_CLR: $Reg
    CRYPTOACCCLKCTRL_CLR: $Reg
    RADIOCLKCTRL_CLR: $Reg
    IPVERSION_TGL: $Reg
    STATUS_TGL: $Reg
    LOCK_TGL: $Reg
    WDOGLOCK_TGL: $Reg
    IF_TGL: $Reg
    IEN_TGL: $Reg
    CALCMD_TGL: $Reg
    CALCTRL_TGL: $Reg
    CALCNT_TGL: $Reg
    CLKEN0_TGL: $Reg
    CLKEN1_TGL: $Reg
    SYSCLKCTRL_TGL: $Reg
    TRACECLKCTRL_TGL: $Reg
    EXPORTCLKCTRL_TGL: $Reg
    DPLLREFCLKCTRL_TGL: $Reg
    EM01GRPACLKCTRL_TGL: $Reg
    EM01GRPBCLKCTRL_TGL: $Reg
    EM23GRPACLKCTRL_TGL: $Reg
    EM4GRPACLKCTRL_TGL: $Reg
    IADCCLKCTRL_TGL: $Reg
    WDOG0CLKCTRL_TGL: $Reg
    EUART0CLKCTRL_TGL: $Reg
    RTCCCLKCTRL_TGL: $Reg
    PRORTCCLKCTRL_TGL: $Reg
    CRYPTOACCCLKCTRL_TGL: $Reg
    RADIOCLKCTRL_TGL: $Reg
}
export const CMU_IPVERSION_IPVERSION_DEFAULT: any = '_CMU_IPVERSION_IPVERSION_DEFAULT << 0'
export const CMU_STATUS_WDOGLOCK: any = '0x1UL << 30'
export const CMU_STATUS_WDOGLOCK_UNLOCKED: any = '_CMU_STATUS_WDOGLOCK_UNLOCKED << 30'
export const CMU_STATUS_WDOGLOCK_LOCKED: any = '_CMU_STATUS_WDOGLOCK_LOCKED << 30'
export const CMU_STATUS_LOCK: any = '0x1UL << 31'
export const CMU_STATUS_LOCK_UNLOCKED: any = '_CMU_STATUS_LOCK_UNLOCKED << 31'
export const CMU_STATUS_LOCK_LOCKED: any = '_CMU_STATUS_LOCK_LOCKED << 31'
export const CMU_LOCK_LOCKKEY_UNLOCK: any = '_CMU_LOCK_LOCKKEY_UNLOCK << 0'
export const CMU_WDOGLOCK_LOCKKEY_UNLOCK: any = '_CMU_WDOGLOCK_LOCKKEY_UNLOCK << 0'
export const CMU_IF_CALOF: any = '0x1UL << 1'
export const CMU_IEN_CALOF: any = '0x1UL << 1'
export const CMU_CALCMD_CALSTOP: any = '0x1UL << 1'
export const CMU_CALCTRL_CALTOP_DEFAULT: any = '_CMU_CALCTRL_CALTOP_DEFAULT << 0'
export const CMU_CALCTRL_CONT: any = '0x1UL << 23'
export const CMU_CALCTRL_UPSEL_DISABLED: any = '_CMU_CALCTRL_UPSEL_DISABLED << 24'
export const CMU_CALCTRL_UPSEL_PRS: any = '_CMU_CALCTRL_UPSEL_PRS << 24'
export const CMU_CALCTRL_UPSEL_HFXO: any = '_CMU_CALCTRL_UPSEL_HFXO << 24'
export const CMU_CALCTRL_UPSEL_LFXO: any = '_CMU_CALCTRL_UPSEL_LFXO << 24'
export const CMU_CALCTRL_UPSEL_HFRCODPLL: any = '_CMU_CALCTRL_UPSEL_HFRCODPLL << 24'
export const CMU_CALCTRL_UPSEL_FSRCO: any = '_CMU_CALCTRL_UPSEL_FSRCO << 24'
export const CMU_CALCTRL_UPSEL_LFRCO: any = '_CMU_CALCTRL_UPSEL_LFRCO << 24'
export const CMU_CALCTRL_UPSEL_ULFRCO: any = '_CMU_CALCTRL_UPSEL_ULFRCO << 24'
export const CMU_CALCTRL_DOWNSEL_DEFAULT: any = '_CMU_CALCTRL_DOWNSEL_DEFAULT << 28'
export const CMU_CALCTRL_DOWNSEL_DISABLED: any = '_CMU_CALCTRL_DOWNSEL_DISABLED << 28'
export const CMU_CALCTRL_DOWNSEL_HCLK: any = '_CMU_CALCTRL_DOWNSEL_HCLK << 28'
export const CMU_CALCTRL_DOWNSEL_PRS: any = '_CMU_CALCTRL_DOWNSEL_PRS << 28'
export const CMU_CALCTRL_DOWNSEL_HFXO: any = '_CMU_CALCTRL_DOWNSEL_HFXO << 28'
export const CMU_CALCTRL_DOWNSEL_LFXO: any = '_CMU_CALCTRL_DOWNSEL_LFXO << 28'
export const CMU_CALCTRL_DOWNSEL_HFRCODPLL: any = '_CMU_CALCTRL_DOWNSEL_HFRCODPLL << 28'
export const CMU_CALCTRL_DOWNSEL_FSRCO: any = '_CMU_CALCTRL_DOWNSEL_FSRCO << 28'
export const CMU_CALCTRL_DOWNSEL_LFRCO: any = '_CMU_CALCTRL_DOWNSEL_LFRCO << 28'
export const CMU_CALCTRL_DOWNSEL_ULFRCO: any = '_CMU_CALCTRL_DOWNSEL_ULFRCO << 28'
export const CMU_CALCNT_CALCNT_DEFAULT: any = '_CMU_CALCNT_CALCNT_DEFAULT << 0'
export const CMU_CLKEN0_LDMAXBAR: any = '0x1UL << 1'
export const CMU_CLKEN0_RADIOAES: any = '0x1UL << 2'
export const CMU_CLKEN0_GPCRC: any = '0x1UL << 3'
export const CMU_CLKEN0_TIMER0: any = '0x1UL << 4'
export const CMU_CLKEN0_TIMER1: any = '0x1UL << 5'
export const CMU_CLKEN0_TIMER2: any = '0x1UL << 6'
export const CMU_CLKEN0_TIMER3: any = '0x1UL << 7'
export const CMU_CLKEN0_USART0: any = '0x1UL << 8'
export const CMU_CLKEN0_USART1: any = '0x1UL << 9'
export const CMU_CLKEN0_IADC0: any = '0x1UL << 10'
export const CMU_CLKEN0_AMUXCP0: any = '0x1UL << 11'
export const CMU_CLKEN0_LETIMER0: any = '0x1UL << 12'
export const CMU_CLKEN0_WDOG0: any = '0x1UL << 13'
export const CMU_CLKEN0_I2C0: any = '0x1UL << 14'
export const CMU_CLKEN0_I2C1: any = '0x1UL << 15'
export const CMU_CLKEN0_SYSCFG: any = '0x1UL << 16'
export const CMU_CLKEN0_DPLL0: any = '0x1UL << 17'
export const CMU_CLKEN0_HFRCO0: any = '0x1UL << 18'
export const CMU_CLKEN0_HFXO0: any = '0x1UL << 19'
export const CMU_CLKEN0_FSRCO: any = '0x1UL << 20'
export const CMU_CLKEN0_LFRCO: any = '0x1UL << 21'
export const CMU_CLKEN0_LFXO: any = '0x1UL << 22'
export const CMU_CLKEN0_ULFRCO: any = '0x1UL << 23'
export const CMU_CLKEN0_EUART0: any = '0x1UL << 24'
export const CMU_CLKEN0_PDM: any = '0x1UL << 25'
export const CMU_CLKEN0_GPIO: any = '0x1UL << 26'
export const CMU_CLKEN0_PRS: any = '0x1UL << 27'
export const CMU_CLKEN0_BURAM: any = '0x1UL << 28'
export const CMU_CLKEN0_BURTC: any = '0x1UL << 29'
export const CMU_CLKEN0_RTCC: any = '0x1UL << 30'
export const CMU_CLKEN0_DCDC: any = '0x1UL << 31'
export const CMU_CLKEN1_MODEM: any = '0x1UL << 1'
export const CMU_CLKEN1_RFCRC: any = '0x1UL << 2'
export const CMU_CLKEN1_FRC: any = '0x1UL << 3'
export const CMU_CLKEN1_PROTIMER: any = '0x1UL << 4'
export const CMU_CLKEN1_RAC: any = '0x1UL << 5'
export const CMU_CLKEN1_SYNTH: any = '0x1UL << 6'
export const CMU_CLKEN1_RDSCRATCHPAD: any = '0x1UL << 7'
export const CMU_CLKEN1_RDMAILBOX0: any = '0x1UL << 8'
export const CMU_CLKEN1_RDMAILBOX1: any = '0x1UL << 9'
export const CMU_CLKEN1_PRORTC: any = '0x1UL << 10'
export const CMU_CLKEN1_BUFC: any = '0x1UL << 11'
export const CMU_CLKEN1_IFADCDEBUG: any = '0x1UL << 12'
export const CMU_CLKEN1_CRYPTOACC: any = '0x1UL << 13'
export const CMU_CLKEN1_RFSENSE: any = '0x1UL << 14'
export const CMU_CLKEN1_SMU: any = '0x1UL << 15'
export const CMU_CLKEN1_ICACHE0: any = '0x1UL << 16'
export const CMU_CLKEN1_MSC: any = '0x1UL << 17'
export const CMU_CLKEN1_TIMER4: any = '0x1UL << 18'
export const CMU_SYSCLKCTRL_CLKSEL_DEFAULT: any = '_CMU_SYSCLKCTRL_CLKSEL_DEFAULT << 0'
export const CMU_SYSCLKCTRL_CLKSEL_FSRCO: any = '_CMU_SYSCLKCTRL_CLKSEL_FSRCO << 0'
export const CMU_SYSCLKCTRL_CLKSEL_HFRCODPLL: any = '_CMU_SYSCLKCTRL_CLKSEL_HFRCODPLL << 0'
export const CMU_SYSCLKCTRL_CLKSEL_HFXO: any = '_CMU_SYSCLKCTRL_CLKSEL_HFXO << 0'
export const CMU_SYSCLKCTRL_CLKSEL_CLKIN0: any = '_CMU_SYSCLKCTRL_CLKSEL_CLKIN0 << 0'
export const CMU_SYSCLKCTRL_PCLKPRESC: any = '0x1UL << 10'
export const CMU_SYSCLKCTRL_PCLKPRESC_DIV1: any = '_CMU_SYSCLKCTRL_PCLKPRESC_DIV1 << 10'
export const CMU_SYSCLKCTRL_PCLKPRESC_DIV2: any = '_CMU_SYSCLKCTRL_PCLKPRESC_DIV2 << 10'
export const CMU_SYSCLKCTRL_HCLKPRESC_DEFAULT: any = '_CMU_SYSCLKCTRL_HCLKPRESC_DEFAULT << 12'
export const CMU_SYSCLKCTRL_HCLKPRESC_DIV1: any = '_CMU_SYSCLKCTRL_HCLKPRESC_DIV1 << 12'
export const CMU_SYSCLKCTRL_HCLKPRESC_DIV2: any = '_CMU_SYSCLKCTRL_HCLKPRESC_DIV2 << 12'
export const CMU_SYSCLKCTRL_HCLKPRESC_DIV4: any = '_CMU_SYSCLKCTRL_HCLKPRESC_DIV4 << 12'
export const CMU_SYSCLKCTRL_HCLKPRESC_DIV8: any = '_CMU_SYSCLKCTRL_HCLKPRESC_DIV8 << 12'
export const CMU_SYSCLKCTRL_HCLKPRESC_DIV16: any = '_CMU_SYSCLKCTRL_HCLKPRESC_DIV16 << 12'
export const CMU_SYSCLKCTRL_RHCLKPRESC: any = '0x1UL << 16'
export const CMU_SYSCLKCTRL_RHCLKPRESC_DIV1: any = '_CMU_SYSCLKCTRL_RHCLKPRESC_DIV1 << 16'
export const CMU_SYSCLKCTRL_RHCLKPRESC_DIV2: any = '_CMU_SYSCLKCTRL_RHCLKPRESC_DIV2 << 16'
export const CMU_TRACECLKCTRL_PRESC_DIV1: any = '_CMU_TRACECLKCTRL_PRESC_DIV1 << 4'
export const CMU_TRACECLKCTRL_PRESC_DIV2: any = '_CMU_TRACECLKCTRL_PRESC_DIV2 << 4'
export const CMU_TRACECLKCTRL_PRESC_DIV4: any = '_CMU_TRACECLKCTRL_PRESC_DIV4 << 4'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_DISABLED: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_DISABLED << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_HCLK: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_HCLK << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_HFEXPCLK: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_HFEXPCLK << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_ULFRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_ULFRCO << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_LFRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_LFRCO << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_LFXO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_LFXO << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_HFRCODPLL: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_HFRCODPLL << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_HFXO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_HFXO << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL0_FSRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL0_FSRCO << 0'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_DEFAULT: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_DEFAULT << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_DISABLED: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_DISABLED << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_HCLK: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_HCLK << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_HFEXPCLK: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_HFEXPCLK << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_ULFRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_ULFRCO << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_LFRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_LFRCO << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_LFXO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_LFXO << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_HFRCODPLL: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_HFRCODPLL << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_HFXO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_HFXO << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL1_FSRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL1_FSRCO << 8'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_DEFAULT: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_DEFAULT << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_DISABLED: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_DISABLED << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_HCLK: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_HCLK << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_HFEXPCLK: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_HFEXPCLK << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_ULFRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_ULFRCO << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_LFRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_LFRCO << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_LFXO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_LFXO << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_HFRCODPLL: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_HFRCODPLL << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_HFXO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_HFXO << 16'
export const CMU_EXPORTCLKCTRL_CLKOUTSEL2_FSRCO: any = '_CMU_EXPORTCLKCTRL_CLKOUTSEL2_FSRCO << 16'
export const CMU_DPLLREFCLKCTRL_CLKSEL_DEFAULT: any = '_CMU_DPLLREFCLKCTRL_CLKSEL_DEFAULT << 0'
export const CMU_DPLLREFCLKCTRL_CLKSEL_DISABLED: any = '_CMU_DPLLREFCLKCTRL_CLKSEL_DISABLED << 0'
export const CMU_DPLLREFCLKCTRL_CLKSEL_HFXO: any = '_CMU_DPLLREFCLKCTRL_CLKSEL_HFXO << 0'
export const CMU_DPLLREFCLKCTRL_CLKSEL_LFXO: any = '_CMU_DPLLREFCLKCTRL_CLKSEL_LFXO << 0'
export const CMU_DPLLREFCLKCTRL_CLKSEL_CLKIN0: any = '_CMU_DPLLREFCLKCTRL_CLKSEL_CLKIN0 << 0'
export const CMU_EM01GRPACLKCTRL_CLKSEL_HFRCODPLL: any = '_CMU_EM01GRPACLKCTRL_CLKSEL_HFRCODPLL << 0'
export const CMU_EM01GRPACLKCTRL_CLKSEL_HFXO: any = '_CMU_EM01GRPACLKCTRL_CLKSEL_HFXO << 0'
export const CMU_EM01GRPACLKCTRL_CLKSEL_FSRCO: any = '_CMU_EM01GRPACLKCTRL_CLKSEL_FSRCO << 0'
export const CMU_EM01GRPBCLKCTRL_CLKSEL_DEFAULT: any = '_CMU_EM01GRPBCLKCTRL_CLKSEL_DEFAULT << 0'
export const CMU_EM01GRPBCLKCTRL_CLKSEL_HFRCODPLL: any = '_CMU_EM01GRPBCLKCTRL_CLKSEL_HFRCODPLL << 0'
export const CMU_EM01GRPBCLKCTRL_CLKSEL_HFXO: any = '_CMU_EM01GRPBCLKCTRL_CLKSEL_HFXO << 0'
export const CMU_EM01GRPBCLKCTRL_CLKSEL_FSRCO: any = '_CMU_EM01GRPBCLKCTRL_CLKSEL_FSRCO << 0'
export const CMU_EM01GRPBCLKCTRL_CLKSEL_CLKIN0: any = '_CMU_EM01GRPBCLKCTRL_CLKSEL_CLKIN0 << 0'
export const CMU_EM01GRPBCLKCTRL_CLKSEL_HFRCODPLLRT: any = '_CMU_EM01GRPBCLKCTRL_CLKSEL_HFRCODPLLRT << 0'
export const CMU_EM01GRPBCLKCTRL_CLKSEL_HFXORT: any = '_CMU_EM01GRPBCLKCTRL_CLKSEL_HFXORT << 0'
export const CMU_EM23GRPACLKCTRL_CLKSEL_LFRCO: any = '_CMU_EM23GRPACLKCTRL_CLKSEL_LFRCO << 0'
export const CMU_EM23GRPACLKCTRL_CLKSEL_LFXO: any = '_CMU_EM23GRPACLKCTRL_CLKSEL_LFXO << 0'
export const CMU_EM23GRPACLKCTRL_CLKSEL_ULFRCO: any = '_CMU_EM23GRPACLKCTRL_CLKSEL_ULFRCO << 0'
export const CMU_EM4GRPACLKCTRL_CLKSEL_LFRCO: any = '_CMU_EM4GRPACLKCTRL_CLKSEL_LFRCO << 0'
export const CMU_EM4GRPACLKCTRL_CLKSEL_LFXO: any = '_CMU_EM4GRPACLKCTRL_CLKSEL_LFXO << 0'
export const CMU_EM4GRPACLKCTRL_CLKSEL_ULFRCO: any = '_CMU_EM4GRPACLKCTRL_CLKSEL_ULFRCO << 0'
export const CMU_IADCCLKCTRL_CLKSEL_DEFAULT: any = '_CMU_IADCCLKCTRL_CLKSEL_DEFAULT << 0'
export const CMU_IADCCLKCTRL_CLKSEL_EM01GRPACLK: any = '_CMU_IADCCLKCTRL_CLKSEL_EM01GRPACLK << 0'
export const CMU_IADCCLKCTRL_CLKSEL_FSRCO: any = '_CMU_IADCCLKCTRL_CLKSEL_FSRCO << 0'
export const CMU_WDOG0CLKCTRL_CLKSEL_DEFAULT: any = '_CMU_WDOG0CLKCTRL_CLKSEL_DEFAULT << 0'
export const CMU_WDOG0CLKCTRL_CLKSEL_LFRCO: any = '_CMU_WDOG0CLKCTRL_CLKSEL_LFRCO << 0'
export const CMU_WDOG0CLKCTRL_CLKSEL_LFXO: any = '_CMU_WDOG0CLKCTRL_CLKSEL_LFXO << 0'
export const CMU_WDOG0CLKCTRL_CLKSEL_ULFRCO: any = '_CMU_WDOG0CLKCTRL_CLKSEL_ULFRCO << 0'
export const CMU_WDOG0CLKCTRL_CLKSEL_HCLKDIV1024: any = '_CMU_WDOG0CLKCTRL_CLKSEL_HCLKDIV1024 << 0'
export const CMU_EUART0CLKCTRL_CLKSEL_DISABLED: any = '_CMU_EUART0CLKCTRL_CLKSEL_DISABLED << 0'
export const CMU_EUART0CLKCTRL_CLKSEL_EM01GRPACLK: any = '_CMU_EUART0CLKCTRL_CLKSEL_EM01GRPACLK << 0'
export const CMU_EUART0CLKCTRL_CLKSEL_EM23GRPACLK: any = '_CMU_EUART0CLKCTRL_CLKSEL_EM23GRPACLK << 0'
export const CMU_RTCCCLKCTRL_CLKSEL_LFRCO: any = '_CMU_RTCCCLKCTRL_CLKSEL_LFRCO << 0'
export const CMU_RTCCCLKCTRL_CLKSEL_LFXO: any = '_CMU_RTCCCLKCTRL_CLKSEL_LFXO << 0'
export const CMU_RTCCCLKCTRL_CLKSEL_ULFRCO: any = '_CMU_RTCCCLKCTRL_CLKSEL_ULFRCO << 0'
export const CMU_PRORTCCLKCTRL_CLKSEL_LFRCO: any = '_CMU_PRORTCCLKCTRL_CLKSEL_LFRCO << 0'
export const CMU_PRORTCCLKCTRL_CLKSEL_LFXO: any = '_CMU_PRORTCCLKCTRL_CLKSEL_LFXO << 0'
export const CMU_PRORTCCLKCTRL_CLKSEL_ULFRCO: any = '_CMU_PRORTCCLKCTRL_CLKSEL_ULFRCO << 0'
export const CMU_CRYPTOACCCLKCTRL_AESEN: any = '0x1UL << 1'
export const CMU_RADIOCLKCTRL_DBGCLK: any = '0x1UL << 31'

// -------- GPIO_CMUROUTE -------- //

export interface GPIO_CMUROUTE_t {
    ROUTEEN: $Reg
    CLKIN0ROUTE: $Reg
    CLKOUT0ROUTE: $Reg
    CLKOUT1ROUTE: $Reg
    CLKOUT2ROUTE: $Reg
}

// -------- GPIO_DCDCROUTE -------- //

export interface GPIO_DCDCROUTE_t {
    ROUTEEN: $Reg
}

// -------- GPIO_FRCROUTE -------- //

export interface GPIO_FRCROUTE_t {
    ROUTEEN: $Reg
    DCLKROUTE: $Reg
    DFRAMEROUTE: $Reg
    DOUTROUTE: $Reg
}

// -------- GPIO_I2CROUTE -------- //

export interface GPIO_I2CROUTE_t {
    ROUTEEN: $Reg
    SCLROUTE: $Reg
    SDAROUTE: $Reg
}

// -------- GPIO_LETIMERROUTE -------- //

export interface GPIO_LETIMERROUTE_t {
    ROUTEEN: $Reg
    OUT0ROUTE: $Reg
    OUT1ROUTE: $Reg
}

// -------- GPIO_EUARTROUTE -------- //

export interface GPIO_EUARTROUTE_t {
    ROUTEEN: $Reg
    CTSROUTE: $Reg
    RTSROUTE: $Reg
    RXROUTE: $Reg
    TXROUTE: $Reg
}

// -------- GPIO_MODEMROUTE -------- //

export interface GPIO_MODEMROUTE_t {
    ROUTEEN: $Reg
    ANT0ROUTE: $Reg
    ANT1ROUTE: $Reg
    ANTROLLOVERROUTE: $Reg
    ANTRR0ROUTE: $Reg
    ANTRR1ROUTE: $Reg
    ANTRR2ROUTE: $Reg
    ANTRR3ROUTE: $Reg
    ANTRR4ROUTE: $Reg
    ANTRR5ROUTE: $Reg
    ANTSWENROUTE: $Reg
    ANTSWUSROUTE: $Reg
    ANTTRIGROUTE: $Reg
    ANTTRIGSTOPROUTE: $Reg
    DCLKROUTE: $Reg
    DINROUTE: $Reg
    DOUTROUTE: $Reg
}

// -------- GPIO_PDMROUTE -------- //

export interface GPIO_PDMROUTE_t {
    ROUTEEN: $Reg
    CLKROUTE: $Reg
    DAT0ROUTE: $Reg
    DAT1ROUTE: $Reg
}

// -------- GPIO_PRSROUTE -------- //

export interface GPIO_PRSROUTE_t {
    ROUTEEN: $Reg
    ASYNCH0ROUTE: $Reg
    ASYNCH1ROUTE: $Reg
    ASYNCH2ROUTE: $Reg
    ASYNCH3ROUTE: $Reg
    ASYNCH4ROUTE: $Reg
    ASYNCH5ROUTE: $Reg
    ASYNCH6ROUTE: $Reg
    ASYNCH7ROUTE: $Reg
    ASYNCH8ROUTE: $Reg
    ASYNCH9ROUTE: $Reg
    ASYNCH10ROUTE: $Reg
    ASYNCH11ROUTE: $Reg
    SYNCH0ROUTE: $Reg
    SYNCH1ROUTE: $Reg
    SYNCH2ROUTE: $Reg
    SYNCH3ROUTE: $Reg
}

// -------- GPIO_TIMERROUTE -------- //

export interface GPIO_TIMERROUTE_t {
    ROUTEEN: $Reg
    CC0ROUTE: $Reg
    CC1ROUTE: $Reg
    CC2ROUTE: $Reg
    CDTI0ROUTE: $Reg
    CDTI1ROUTE: $Reg
    CDTI2ROUTE: $Reg
}

// -------- GPIO_USARTROUTE -------- //

export interface GPIO_USARTROUTE_t {
    ROUTEEN: $Reg
    CSROUTE: $Reg
    CTSROUTE: $Reg
    RTSROUTE: $Reg
    RXROUTE: $Reg
    CLKROUTE: $Reg
    TXROUTE: $Reg
}

// -------- GPIO -------- //

export interface GPIO_t {
    P: dim_t<GPIO_PORT_t, 4>
    LOCK: $Reg
    GPIOLOCKSTATUS: $Reg
    ABUSALLOC: $Reg
    BBUSALLOC: $Reg
    CDBUSALLOC: $Reg
    EXTIPSELL: $Reg
    EXTIPSELH: $Reg
    EXTIPINSELL: $Reg
    EXTIPINSELH: $Reg
    EXTIRISE: $Reg
    EXTIFALL: $Reg
    IF: $Reg
    IEN: $Reg
    EM4WUEN: $Reg
    EM4WUPOL: $Reg
    DBGROUTEPEN: $Reg
    TRACEROUTEPEN: $Reg
    CMUROUTE: GPIO_CMUROUTE_t
    DCDCROUTE: GPIO_DCDCROUTE_t
    FRCROUTE: GPIO_FRCROUTE_t
    I2CROUTE: dim_t<GPIO_I2CROUTE_t, 2>
    LETIMERROUTE: dim_t<GPIO_LETIMERROUTE_t, 1>
    EUARTROUTE: dim_t<GPIO_EUARTROUTE_t, 1>
    MODEMROUTE: GPIO_MODEMROUTE_t
    PDMROUTE: GPIO_PDMROUTE_t
    PRSROUTE: dim_t<GPIO_PRSROUTE_t, 1>
    TIMERROUTE: dim_t<GPIO_TIMERROUTE_t, 5>
    USARTROUTE: dim_t<GPIO_USARTROUTE_t, 2>
    P_SET: dim_t<GPIO_PORT_t, 4>
    LOCK_SET: $Reg
    GPIOLOCKSTATUS_SET: $Reg
    ABUSALLOC_SET: $Reg
    BBUSALLOC_SET: $Reg
    CDBUSALLOC_SET: $Reg
    EXTIPSELL_SET: $Reg
    EXTIPSELH_SET: $Reg
    EXTIPINSELL_SET: $Reg
    EXTIPINSELH_SET: $Reg
    EXTIRISE_SET: $Reg
    EXTIFALL_SET: $Reg
    IF_SET: $Reg
    IEN_SET: $Reg
    EM4WUEN_SET: $Reg
    EM4WUPOL_SET: $Reg
    DBGROUTEPEN_SET: $Reg
    TRACEROUTEPEN_SET: $Reg
    CMUROUTE_SET: GPIO_CMUROUTE_t
    DCDCROUTE_SET: GPIO_DCDCROUTE_t
    FRCROUTE_SET: GPIO_FRCROUTE_t
    I2CROUTE_SET: dim_t<GPIO_I2CROUTE_t, 2>
    LETIMERROUTE_SET: dim_t<GPIO_LETIMERROUTE_t, 1>
    EUARTROUTE_SET: dim_t<GPIO_EUARTROUTE_t, 1>
    MODEMROUTE_SET: GPIO_MODEMROUTE_t
    PDMROUTE_SET: GPIO_PDMROUTE_t
    PRSROUTE_SET: dim_t<GPIO_PRSROUTE_t, 1>
    TIMERROUTE_SET: dim_t<GPIO_TIMERROUTE_t, 5>
    USARTROUTE_SET: dim_t<GPIO_USARTROUTE_t, 2>
    P_CLR: dim_t<GPIO_PORT_t, 4>
    LOCK_CLR: $Reg
    GPIOLOCKSTATUS_CLR: $Reg
    ABUSALLOC_CLR: $Reg
    BBUSALLOC_CLR: $Reg
    CDBUSALLOC_CLR: $Reg
    EXTIPSELL_CLR: $Reg
    EXTIPSELH_CLR: $Reg
    EXTIPINSELL_CLR: $Reg
    EXTIPINSELH_CLR: $Reg
    EXTIRISE_CLR: $Reg
    EXTIFALL_CLR: $Reg
    IF_CLR: $Reg
    IEN_CLR: $Reg
    EM4WUEN_CLR: $Reg
    EM4WUPOL_CLR: $Reg
    DBGROUTEPEN_CLR: $Reg
    TRACEROUTEPEN_CLR: $Reg
    CMUROUTE_CLR: GPIO_CMUROUTE_t
    DCDCROUTE_CLR: GPIO_DCDCROUTE_t
    FRCROUTE_CLR: GPIO_FRCROUTE_t
    I2CROUTE_CLR: dim_t<GPIO_I2CROUTE_t, 2>
    LETIMERROUTE_CLR: dim_t<GPIO_LETIMERROUTE_t, 1>
    EUARTROUTE_CLR: dim_t<GPIO_EUARTROUTE_t, 1>
    MODEMROUTE_CLR: GPIO_MODEMROUTE_t
    PDMROUTE_CLR: GPIO_PDMROUTE_t
    PRSROUTE_CLR: dim_t<GPIO_PRSROUTE_t, 1>
    TIMERROUTE_CLR: dim_t<GPIO_TIMERROUTE_t, 5>
    USARTROUTE_CLR: dim_t<GPIO_USARTROUTE_t, 2>
    P_TGL: dim_t<GPIO_PORT_t, 4>
    LOCK_TGL: $Reg
    GPIOLOCKSTATUS_TGL: $Reg
    ABUSALLOC_TGL: $Reg
    BBUSALLOC_TGL: $Reg
    CDBUSALLOC_TGL: $Reg
    EXTIPSELL_TGL: $Reg
    EXTIPSELH_TGL: $Reg
    EXTIPINSELL_TGL: $Reg
    EXTIPINSELH_TGL: $Reg
    EXTIRISE_TGL: $Reg
    EXTIFALL_TGL: $Reg
    IF_TGL: $Reg
    IEN_TGL: $Reg
    EM4WUEN_TGL: $Reg
    EM4WUPOL_TGL: $Reg
    DBGROUTEPEN_TGL: $Reg
    TRACEROUTEPEN_TGL: $Reg
    CMUROUTE_TGL: GPIO_CMUROUTE_t
    DCDCROUTE_TGL: GPIO_DCDCROUTE_t
    FRCROUTE_TGL: GPIO_FRCROUTE_t
    I2CROUTE_TGL: dim_t<GPIO_I2CROUTE_t, 2>
    LETIMERROUTE_TGL: dim_t<GPIO_LETIMERROUTE_t, 1>
    EUARTROUTE_TGL: dim_t<GPIO_EUARTROUTE_t, 1>
    MODEMROUTE_TGL: GPIO_MODEMROUTE_t
    PDMROUTE_TGL: GPIO_PDMROUTE_t
    PRSROUTE_TGL: dim_t<GPIO_PRSROUTE_t, 1>
    TIMERROUTE_TGL: dim_t<GPIO_TIMERROUTE_t, 5>
    USARTROUTE_TGL: dim_t<GPIO_USARTROUTE_t, 2>
}
export const GPIO_LOCK_LOCKKEY_UNLOCK: any = '_GPIO_LOCK_LOCKKEY_UNLOCK << 0'
export const GPIO_GPIOLOCKSTATUS_LOCK_UNLOCKED: any = '_GPIO_GPIOLOCKSTATUS_LOCK_UNLOCKED << 0'
export const GPIO_GPIOLOCKSTATUS_LOCK_LOCKED: any = '_GPIO_GPIOLOCKSTATUS_LOCK_LOCKED << 0'
export const GPIO_ABUSALLOC_AEVEN0_DEFAULT: any = '_GPIO_ABUSALLOC_AEVEN0_DEFAULT << 0'
export const GPIO_ABUSALLOC_AEVEN0_TRISTATE: any = '_GPIO_ABUSALLOC_AEVEN0_TRISTATE << 0'
export const GPIO_ABUSALLOC_AEVEN0_ADC0: any = '_GPIO_ABUSALLOC_AEVEN0_ADC0 << 0'
export const GPIO_ABUSALLOC_AEVEN1_TRISTATE: any = '_GPIO_ABUSALLOC_AEVEN1_TRISTATE << 8'
export const GPIO_ABUSALLOC_AEVEN1_ADC0: any = '_GPIO_ABUSALLOC_AEVEN1_ADC0 << 8'
export const GPIO_ABUSALLOC_AODD0_TRISTATE: any = '_GPIO_ABUSALLOC_AODD0_TRISTATE << 16'
export const GPIO_ABUSALLOC_AODD0_ADC0: any = '_GPIO_ABUSALLOC_AODD0_ADC0 << 16'
export const GPIO_ABUSALLOC_AODD1_TRISTATE: any = '_GPIO_ABUSALLOC_AODD1_TRISTATE << 24'
export const GPIO_ABUSALLOC_AODD1_ADC0: any = '_GPIO_ABUSALLOC_AODD1_ADC0 << 24'
export const GPIO_BBUSALLOC_BEVEN0_DEFAULT: any = '_GPIO_BBUSALLOC_BEVEN0_DEFAULT << 0'
export const GPIO_BBUSALLOC_BEVEN0_TRISTATE: any = '_GPIO_BBUSALLOC_BEVEN0_TRISTATE << 0'
export const GPIO_BBUSALLOC_BEVEN0_ADC0: any = '_GPIO_BBUSALLOC_BEVEN0_ADC0 << 0'
export const GPIO_BBUSALLOC_BEVEN1_TRISTATE: any = '_GPIO_BBUSALLOC_BEVEN1_TRISTATE << 8'
export const GPIO_BBUSALLOC_BEVEN1_ADC0: any = '_GPIO_BBUSALLOC_BEVEN1_ADC0 << 8'
export const GPIO_BBUSALLOC_BODD0_TRISTATE: any = '_GPIO_BBUSALLOC_BODD0_TRISTATE << 16'
export const GPIO_BBUSALLOC_BODD0_ADC0: any = '_GPIO_BBUSALLOC_BODD0_ADC0 << 16'
export const GPIO_BBUSALLOC_BODD1_TRISTATE: any = '_GPIO_BBUSALLOC_BODD1_TRISTATE << 24'
export const GPIO_BBUSALLOC_BODD1_ADC0: any = '_GPIO_BBUSALLOC_BODD1_ADC0 << 24'
export const GPIO_CDBUSALLOC_CDEVEN0_DEFAULT: any = '_GPIO_CDBUSALLOC_CDEVEN0_DEFAULT << 0'
export const GPIO_CDBUSALLOC_CDEVEN0_TRISTATE: any = '_GPIO_CDBUSALLOC_CDEVEN0_TRISTATE << 0'
export const GPIO_CDBUSALLOC_CDEVEN0_ADC0: any = '_GPIO_CDBUSALLOC_CDEVEN0_ADC0 << 0'
export const GPIO_CDBUSALLOC_CDEVEN1_TRISTATE: any = '_GPIO_CDBUSALLOC_CDEVEN1_TRISTATE << 8'
export const GPIO_CDBUSALLOC_CDEVEN1_ADC0: any = '_GPIO_CDBUSALLOC_CDEVEN1_ADC0 << 8'
export const GPIO_CDBUSALLOC_CDODD0_TRISTATE: any = '_GPIO_CDBUSALLOC_CDODD0_TRISTATE << 16'
export const GPIO_CDBUSALLOC_CDODD0_ADC0: any = '_GPIO_CDBUSALLOC_CDODD0_ADC0 << 16'
export const GPIO_CDBUSALLOC_CDODD1_TRISTATE: any = '_GPIO_CDBUSALLOC_CDODD1_TRISTATE << 24'
export const GPIO_CDBUSALLOC_CDODD1_ADC0: any = '_GPIO_CDBUSALLOC_CDODD1_ADC0 << 24'
export const GPIO_EXTIPSELL_EXTIPSEL0_DEFAULT: any = '_GPIO_EXTIPSELL_EXTIPSEL0_DEFAULT << 0'
export const GPIO_EXTIPSELL_EXTIPSEL0_PORTA: any = '_GPIO_EXTIPSELL_EXTIPSEL0_PORTA << 0'
export const GPIO_EXTIPSELL_EXTIPSEL0_PORTB: any = '_GPIO_EXTIPSELL_EXTIPSEL0_PORTB << 0'
export const GPIO_EXTIPSELL_EXTIPSEL0_PORTC: any = '_GPIO_EXTIPSELL_EXTIPSEL0_PORTC << 0'
export const GPIO_EXTIPSELL_EXTIPSEL0_PORTD: any = '_GPIO_EXTIPSELL_EXTIPSEL0_PORTD << 0'
export const GPIO_EXTIPSELL_EXTIPSEL1_PORTA: any = '_GPIO_EXTIPSELL_EXTIPSEL1_PORTA << 4'
export const GPIO_EXTIPSELL_EXTIPSEL1_PORTB: any = '_GPIO_EXTIPSELL_EXTIPSEL1_PORTB << 4'
export const GPIO_EXTIPSELL_EXTIPSEL1_PORTC: any = '_GPIO_EXTIPSELL_EXTIPSEL1_PORTC << 4'
export const GPIO_EXTIPSELL_EXTIPSEL1_PORTD: any = '_GPIO_EXTIPSELL_EXTIPSEL1_PORTD << 4'
export const GPIO_EXTIPSELL_EXTIPSEL2_PORTA: any = '_GPIO_EXTIPSELL_EXTIPSEL2_PORTA << 8'
export const GPIO_EXTIPSELL_EXTIPSEL2_PORTB: any = '_GPIO_EXTIPSELL_EXTIPSEL2_PORTB << 8'
export const GPIO_EXTIPSELL_EXTIPSEL2_PORTC: any = '_GPIO_EXTIPSELL_EXTIPSEL2_PORTC << 8'
export const GPIO_EXTIPSELL_EXTIPSEL2_PORTD: any = '_GPIO_EXTIPSELL_EXTIPSEL2_PORTD << 8'
export const GPIO_EXTIPSELL_EXTIPSEL3_PORTA: any = '_GPIO_EXTIPSELL_EXTIPSEL3_PORTA << 12'
export const GPIO_EXTIPSELL_EXTIPSEL3_PORTB: any = '_GPIO_EXTIPSELL_EXTIPSEL3_PORTB << 12'
export const GPIO_EXTIPSELL_EXTIPSEL3_PORTC: any = '_GPIO_EXTIPSELL_EXTIPSEL3_PORTC << 12'
export const GPIO_EXTIPSELL_EXTIPSEL3_PORTD: any = '_GPIO_EXTIPSELL_EXTIPSEL3_PORTD << 12'
export const GPIO_EXTIPSELL_EXTIPSEL4_PORTA: any = '_GPIO_EXTIPSELL_EXTIPSEL4_PORTA << 16'
export const GPIO_EXTIPSELL_EXTIPSEL4_PORTB: any = '_GPIO_EXTIPSELL_EXTIPSEL4_PORTB << 16'
export const GPIO_EXTIPSELL_EXTIPSEL4_PORTC: any = '_GPIO_EXTIPSELL_EXTIPSEL4_PORTC << 16'
export const GPIO_EXTIPSELL_EXTIPSEL4_PORTD: any = '_GPIO_EXTIPSELL_EXTIPSEL4_PORTD << 16'
export const GPIO_EXTIPSELL_EXTIPSEL5_PORTA: any = '_GPIO_EXTIPSELL_EXTIPSEL5_PORTA << 20'
export const GPIO_EXTIPSELL_EXTIPSEL5_PORTB: any = '_GPIO_EXTIPSELL_EXTIPSEL5_PORTB << 20'
export const GPIO_EXTIPSELL_EXTIPSEL5_PORTC: any = '_GPIO_EXTIPSELL_EXTIPSEL5_PORTC << 20'
export const GPIO_EXTIPSELL_EXTIPSEL5_PORTD: any = '_GPIO_EXTIPSELL_EXTIPSEL5_PORTD << 20'
export const GPIO_EXTIPSELL_EXTIPSEL6_PORTA: any = '_GPIO_EXTIPSELL_EXTIPSEL6_PORTA << 24'
export const GPIO_EXTIPSELL_EXTIPSEL6_PORTB: any = '_GPIO_EXTIPSELL_EXTIPSEL6_PORTB << 24'
export const GPIO_EXTIPSELL_EXTIPSEL6_PORTC: any = '_GPIO_EXTIPSELL_EXTIPSEL6_PORTC << 24'
export const GPIO_EXTIPSELL_EXTIPSEL6_PORTD: any = '_GPIO_EXTIPSELL_EXTIPSEL6_PORTD << 24'
export const GPIO_EXTIPSELL_EXTIPSEL7_PORTA: any = '_GPIO_EXTIPSELL_EXTIPSEL7_PORTA << 28'
export const GPIO_EXTIPSELL_EXTIPSEL7_PORTB: any = '_GPIO_EXTIPSELL_EXTIPSEL7_PORTB << 28'
export const GPIO_EXTIPSELL_EXTIPSEL7_PORTC: any = '_GPIO_EXTIPSELL_EXTIPSEL7_PORTC << 28'
export const GPIO_EXTIPSELL_EXTIPSEL7_PORTD: any = '_GPIO_EXTIPSELL_EXTIPSEL7_PORTD << 28'
export const GPIO_EXTIPSELH_EXTIPSEL0_DEFAULT: any = '_GPIO_EXTIPSELH_EXTIPSEL0_DEFAULT << 0'
export const GPIO_EXTIPSELH_EXTIPSEL0_PORTA: any = '_GPIO_EXTIPSELH_EXTIPSEL0_PORTA << 0'
export const GPIO_EXTIPSELH_EXTIPSEL0_PORTB: any = '_GPIO_EXTIPSELH_EXTIPSEL0_PORTB << 0'
export const GPIO_EXTIPSELH_EXTIPSEL0_PORTC: any = '_GPIO_EXTIPSELH_EXTIPSEL0_PORTC << 0'
export const GPIO_EXTIPSELH_EXTIPSEL0_PORTD: any = '_GPIO_EXTIPSELH_EXTIPSEL0_PORTD << 0'
export const GPIO_EXTIPSELH_EXTIPSEL1_PORTA: any = '_GPIO_EXTIPSELH_EXTIPSEL1_PORTA << 4'
export const GPIO_EXTIPSELH_EXTIPSEL1_PORTB: any = '_GPIO_EXTIPSELH_EXTIPSEL1_PORTB << 4'
export const GPIO_EXTIPSELH_EXTIPSEL1_PORTC: any = '_GPIO_EXTIPSELH_EXTIPSEL1_PORTC << 4'
export const GPIO_EXTIPSELH_EXTIPSEL1_PORTD: any = '_GPIO_EXTIPSELH_EXTIPSEL1_PORTD << 4'
export const GPIO_EXTIPSELH_EXTIPSEL2_PORTA: any = '_GPIO_EXTIPSELH_EXTIPSEL2_PORTA << 8'
export const GPIO_EXTIPSELH_EXTIPSEL2_PORTB: any = '_GPIO_EXTIPSELH_EXTIPSEL2_PORTB << 8'
export const GPIO_EXTIPSELH_EXTIPSEL2_PORTC: any = '_GPIO_EXTIPSELH_EXTIPSEL2_PORTC << 8'
export const GPIO_EXTIPSELH_EXTIPSEL2_PORTD: any = '_GPIO_EXTIPSELH_EXTIPSEL2_PORTD << 8'
export const GPIO_EXTIPSELH_EXTIPSEL3_PORTA: any = '_GPIO_EXTIPSELH_EXTIPSEL3_PORTA << 12'
export const GPIO_EXTIPSELH_EXTIPSEL3_PORTB: any = '_GPIO_EXTIPSELH_EXTIPSEL3_PORTB << 12'
export const GPIO_EXTIPSELH_EXTIPSEL3_PORTC: any = '_GPIO_EXTIPSELH_EXTIPSEL3_PORTC << 12'
export const GPIO_EXTIPSELH_EXTIPSEL3_PORTD: any = '_GPIO_EXTIPSELH_EXTIPSEL3_PORTD << 12'
export const GPIO_EXTIPINSELL_EXTIPINSEL0_DEFAULT: any = '_GPIO_EXTIPINSELL_EXTIPINSEL0_DEFAULT << 0'
export const GPIO_EXTIPINSELL_EXTIPINSEL0_OFFSET0: any = '_GPIO_EXTIPINSELL_EXTIPINSEL0_OFFSET0 << 0'
export const GPIO_EXTIPINSELL_EXTIPINSEL0_OFFSET1: any = '_GPIO_EXTIPINSELL_EXTIPINSEL0_OFFSET1 << 0'
export const GPIO_EXTIPINSELL_EXTIPINSEL0_OFFSET2: any = '_GPIO_EXTIPINSELL_EXTIPINSEL0_OFFSET2 << 0'
export const GPIO_EXTIPINSELL_EXTIPINSEL0_OFFSET3: any = '_GPIO_EXTIPINSELL_EXTIPINSEL0_OFFSET3 << 0'
export const GPIO_EXTIPINSELL_EXTIPINSEL1_OFFSET0: any = '_GPIO_EXTIPINSELL_EXTIPINSEL1_OFFSET0 << 4'
export const GPIO_EXTIPINSELL_EXTIPINSEL1_OFFSET1: any = '_GPIO_EXTIPINSELL_EXTIPINSEL1_OFFSET1 << 4'
export const GPIO_EXTIPINSELL_EXTIPINSEL1_OFFSET2: any = '_GPIO_EXTIPINSELL_EXTIPINSEL1_OFFSET2 << 4'
export const GPIO_EXTIPINSELL_EXTIPINSEL1_OFFSET3: any = '_GPIO_EXTIPINSELL_EXTIPINSEL1_OFFSET3 << 4'
export const GPIO_EXTIPINSELL_EXTIPINSEL2_OFFSET0: any = '_GPIO_EXTIPINSELL_EXTIPINSEL2_OFFSET0 << 8'
export const GPIO_EXTIPINSELL_EXTIPINSEL2_OFFSET1: any = '_GPIO_EXTIPINSELL_EXTIPINSEL2_OFFSET1 << 8'
export const GPIO_EXTIPINSELL_EXTIPINSEL2_OFFSET2: any = '_GPIO_EXTIPINSELL_EXTIPINSEL2_OFFSET2 << 8'
export const GPIO_EXTIPINSELL_EXTIPINSEL2_OFFSET3: any = '_GPIO_EXTIPINSELL_EXTIPINSEL2_OFFSET3 << 8'
export const GPIO_EXTIPINSELL_EXTIPINSEL3_OFFSET0: any = '_GPIO_EXTIPINSELL_EXTIPINSEL3_OFFSET0 << 12'
export const GPIO_EXTIPINSELL_EXTIPINSEL3_OFFSET1: any = '_GPIO_EXTIPINSELL_EXTIPINSEL3_OFFSET1 << 12'
export const GPIO_EXTIPINSELL_EXTIPINSEL3_OFFSET2: any = '_GPIO_EXTIPINSELL_EXTIPINSEL3_OFFSET2 << 12'
export const GPIO_EXTIPINSELL_EXTIPINSEL3_OFFSET3: any = '_GPIO_EXTIPINSELL_EXTIPINSEL3_OFFSET3 << 12'
export const GPIO_EXTIPINSELL_EXTIPINSEL4_OFFSET0: any = '_GPIO_EXTIPINSELL_EXTIPINSEL4_OFFSET0 << 16'
export const GPIO_EXTIPINSELL_EXTIPINSEL4_OFFSET1: any = '_GPIO_EXTIPINSELL_EXTIPINSEL4_OFFSET1 << 16'
export const GPIO_EXTIPINSELL_EXTIPINSEL4_OFFSET2: any = '_GPIO_EXTIPINSELL_EXTIPINSEL4_OFFSET2 << 16'
export const GPIO_EXTIPINSELL_EXTIPINSEL4_OFFSET3: any = '_GPIO_EXTIPINSELL_EXTIPINSEL4_OFFSET3 << 16'
export const GPIO_EXTIPINSELL_EXTIPINSEL5_OFFSET0: any = '_GPIO_EXTIPINSELL_EXTIPINSEL5_OFFSET0 << 20'
export const GPIO_EXTIPINSELL_EXTIPINSEL5_OFFSET1: any = '_GPIO_EXTIPINSELL_EXTIPINSEL5_OFFSET1 << 20'
export const GPIO_EXTIPINSELL_EXTIPINSEL5_OFFSET2: any = '_GPIO_EXTIPINSELL_EXTIPINSEL5_OFFSET2 << 20'
export const GPIO_EXTIPINSELL_EXTIPINSEL5_OFFSET3: any = '_GPIO_EXTIPINSELL_EXTIPINSEL5_OFFSET3 << 20'
export const GPIO_EXTIPINSELL_EXTIPINSEL6_OFFSET0: any = '_GPIO_EXTIPINSELL_EXTIPINSEL6_OFFSET0 << 24'
export const GPIO_EXTIPINSELL_EXTIPINSEL6_OFFSET1: any = '_GPIO_EXTIPINSELL_EXTIPINSEL6_OFFSET1 << 24'
export const GPIO_EXTIPINSELL_EXTIPINSEL6_OFFSET2: any = '_GPIO_EXTIPINSELL_EXTIPINSEL6_OFFSET2 << 24'
export const GPIO_EXTIPINSELL_EXTIPINSEL6_OFFSET3: any = '_GPIO_EXTIPINSELL_EXTIPINSEL6_OFFSET3 << 24'
export const GPIO_EXTIPINSELL_EXTIPINSEL7_OFFSET0: any = '_GPIO_EXTIPINSELL_EXTIPINSEL7_OFFSET0 << 28'
export const GPIO_EXTIPINSELL_EXTIPINSEL7_OFFSET1: any = '_GPIO_EXTIPINSELL_EXTIPINSEL7_OFFSET1 << 28'
export const GPIO_EXTIPINSELL_EXTIPINSEL7_OFFSET2: any = '_GPIO_EXTIPINSELL_EXTIPINSEL7_OFFSET2 << 28'
export const GPIO_EXTIPINSELL_EXTIPINSEL7_OFFSET3: any = '_GPIO_EXTIPINSELL_EXTIPINSEL7_OFFSET3 << 28'
export const GPIO_EXTIPINSELH_EXTIPINSEL0_DEFAULT: any = '_GPIO_EXTIPINSELH_EXTIPINSEL0_DEFAULT << 0'
export const GPIO_EXTIPINSELH_EXTIPINSEL0_OFFSET8: any = '_GPIO_EXTIPINSELH_EXTIPINSEL0_OFFSET8 << 0'
export const GPIO_EXTIPINSELH_EXTIPINSEL0_OFFSET9: any = '_GPIO_EXTIPINSELH_EXTIPINSEL0_OFFSET9 << 0'
export const GPIO_EXTIPINSELH_EXTIPINSEL0_OFFSET10: any = '_GPIO_EXTIPINSELH_EXTIPINSEL0_OFFSET10 << 0'
export const GPIO_EXTIPINSELH_EXTIPINSEL0_OFFSET11: any = '_GPIO_EXTIPINSELH_EXTIPINSEL0_OFFSET11 << 0'
export const GPIO_EXTIPINSELH_EXTIPINSEL1_OFFSET8: any = '_GPIO_EXTIPINSELH_EXTIPINSEL1_OFFSET8 << 4'
export const GPIO_EXTIPINSELH_EXTIPINSEL1_OFFSET9: any = '_GPIO_EXTIPINSELH_EXTIPINSEL1_OFFSET9 << 4'
export const GPIO_EXTIPINSELH_EXTIPINSEL1_OFFSET10: any = '_GPIO_EXTIPINSELH_EXTIPINSEL1_OFFSET10 << 4'
export const GPIO_EXTIPINSELH_EXTIPINSEL1_OFFSET11: any = '_GPIO_EXTIPINSELH_EXTIPINSEL1_OFFSET11 << 4'
export const GPIO_EXTIPINSELH_EXTIPINSEL2_OFFSET8: any = '_GPIO_EXTIPINSELH_EXTIPINSEL2_OFFSET8 << 8'
export const GPIO_EXTIPINSELH_EXTIPINSEL2_OFFSET9: any = '_GPIO_EXTIPINSELH_EXTIPINSEL2_OFFSET9 << 8'
export const GPIO_EXTIPINSELH_EXTIPINSEL2_OFFSET10: any = '_GPIO_EXTIPINSELH_EXTIPINSEL2_OFFSET10 << 8'
export const GPIO_EXTIPINSELH_EXTIPINSEL2_OFFSET11: any = '_GPIO_EXTIPINSELH_EXTIPINSEL2_OFFSET11 << 8'
export const GPIO_EXTIPINSELH_EXTIPINSEL3_OFFSET8: any = '_GPIO_EXTIPINSELH_EXTIPINSEL3_OFFSET8 << 12'
export const GPIO_EXTIPINSELH_EXTIPINSEL3_OFFSET9: any = '_GPIO_EXTIPINSELH_EXTIPINSEL3_OFFSET9 << 12'
export const GPIO_EXTIPINSELH_EXTIPINSEL3_OFFSET10: any = '_GPIO_EXTIPINSELH_EXTIPINSEL3_OFFSET10 << 12'
export const GPIO_EXTIPINSELH_EXTIPINSEL3_OFFSET11: any = '_GPIO_EXTIPINSELH_EXTIPINSEL3_OFFSET11 << 12'
export const GPIO_EXTIRISE_EXTIRISE_DEFAULT: any = '_GPIO_EXTIRISE_EXTIRISE_DEFAULT << 0'
export const GPIO_EXTIFALL_EXTIFALL_DEFAULT: any = '_GPIO_EXTIFALL_EXTIFALL_DEFAULT << 0'
export const GPIO_IF_EXTIF1: any = '0x1UL << 1'
export const GPIO_IF_EXTIF2: any = '0x1UL << 2'
export const GPIO_IF_EXTIF3: any = '0x1UL << 3'
export const GPIO_IF_EXTIF4: any = '0x1UL << 4'
export const GPIO_IF_EXTIF5: any = '0x1UL << 5'
export const GPIO_IF_EXTIF6: any = '0x1UL << 6'
export const GPIO_IF_EXTIF7: any = '0x1UL << 7'
export const GPIO_IF_EXTIF8: any = '0x1UL << 8'
export const GPIO_IF_EXTIF9: any = '0x1UL << 9'
export const GPIO_IF_EXTIF10: any = '0x1UL << 10'
export const GPIO_IF_EXTIF11: any = '0x1UL << 11'
export const GPIO_IEN_EXTIEN1: any = '0x1UL << 1'
export const GPIO_IEN_EXTIEN2: any = '0x1UL << 2'
export const GPIO_IEN_EXTIEN3: any = '0x1UL << 3'
export const GPIO_IEN_EXTIEN4: any = '0x1UL << 4'
export const GPIO_IEN_EXTIEN5: any = '0x1UL << 5'
export const GPIO_IEN_EXTIEN6: any = '0x1UL << 6'
export const GPIO_IEN_EXTIEN7: any = '0x1UL << 7'
export const GPIO_IEN_EXTIEN8: any = '0x1UL << 8'
export const GPIO_IEN_EXTIEN9: any = '0x1UL << 9'
export const GPIO_IEN_EXTIEN10: any = '0x1UL << 10'
export const GPIO_IEN_EXTIEN11: any = '0x1UL << 11'
export const GPIO_IEN_EM4WUIEN0: any = '0x1UL << 16'
export const GPIO_IEN_EM4WUIEN1: any = '0x1UL << 17'
export const GPIO_IEN_EM4WUIEN2: any = '0x1UL << 18'
export const GPIO_IEN_EM4WUIEN3: any = '0x1UL << 19'
export const GPIO_IEN_EM4WUIEN4: any = '0x1UL << 20'
export const GPIO_IEN_EM4WUIEN5: any = '0x1UL << 21'
export const GPIO_IEN_EM4WUIEN6: any = '0x1UL << 22'
export const GPIO_IEN_EM4WUIEN7: any = '0x1UL << 23'
export const GPIO_IEN_EM4WUIEN8: any = '0x1UL << 24'
export const GPIO_IEN_EM4WUIEN9: any = '0x1UL << 25'
export const GPIO_IEN_EM4WUIEN10: any = '0x1UL << 26'
export const GPIO_IEN_EM4WUIEN11: any = '0x1UL << 27'
export const GPIO_EM4WUEN_EM4WUEN_DEFAULT: any = '_GPIO_EM4WUEN_EM4WUEN_DEFAULT << 16'
export const GPIO_EM4WUPOL_EM4WUPOL_DEFAULT: any = '_GPIO_EM4WUPOL_EM4WUPOL_DEFAULT << 16'
export const GPIO_DBGROUTEPEN_SWDIOTMSPEN: any = '0x1UL << 1'
export const GPIO_DBGROUTEPEN_TDOPEN: any = '0x1UL << 2'
export const GPIO_DBGROUTEPEN_TDIPEN: any = '0x1UL << 3'
export const GPIO_TRACEROUTEPEN_TRACECLKPEN: any = '0x1UL << 1'
export const GPIO_TRACEROUTEPEN_TRACEDATA0PEN: any = '0x1UL << 2'
export const GPIO_CMU_ROUTEEN_CLKOUT1PEN: any = '0x1UL << 1'
export const GPIO_CMU_ROUTEEN_CLKOUT2PEN: any = '0x1UL << 2'
export const GPIO_CMU_CLKIN0ROUTE_PORT_DEFAULT: any = '_GPIO_CMU_CLKIN0ROUTE_PORT_DEFAULT << 0'
export const GPIO_CMU_CLKOUT0ROUTE_PORT_DEFAULT: any = '_GPIO_CMU_CLKOUT0ROUTE_PORT_DEFAULT << 0'
export const GPIO_CMU_CLKOUT1ROUTE_PORT_DEFAULT: any = '_GPIO_CMU_CLKOUT1ROUTE_PORT_DEFAULT << 0'
export const GPIO_CMU_CLKOUT2ROUTE_PORT_DEFAULT: any = '_GPIO_CMU_CLKOUT2ROUTE_PORT_DEFAULT << 0'
export const GPIO_FRC_ROUTEEN_DFRAMEPEN: any = '0x1UL << 1'
export const GPIO_FRC_ROUTEEN_DOUTPEN: any = '0x1UL << 2'
export const GPIO_FRC_DCLKROUTE_PORT_DEFAULT: any = '_GPIO_FRC_DCLKROUTE_PORT_DEFAULT << 0'
export const GPIO_FRC_DFRAMEROUTE_PORT_DEFAULT: any = '_GPIO_FRC_DFRAMEROUTE_PORT_DEFAULT << 0'
export const GPIO_FRC_DOUTROUTE_PORT_DEFAULT: any = '_GPIO_FRC_DOUTROUTE_PORT_DEFAULT << 0'
export const GPIO_I2C_ROUTEEN_SDAPEN: any = '0x1UL << 1'
export const GPIO_I2C_SCLROUTE_PORT_DEFAULT: any = '_GPIO_I2C_SCLROUTE_PORT_DEFAULT << 0'
export const GPIO_I2C_SDAROUTE_PORT_DEFAULT: any = '_GPIO_I2C_SDAROUTE_PORT_DEFAULT << 0'
export const GPIO_LETIMER_ROUTEEN_OUT1PEN: any = '0x1UL << 1'
export const GPIO_LETIMER_OUT0ROUTE_PORT_DEFAULT: any = '_GPIO_LETIMER_OUT0ROUTE_PORT_DEFAULT << 0'
export const GPIO_LETIMER_OUT1ROUTE_PORT_DEFAULT: any = '_GPIO_LETIMER_OUT1ROUTE_PORT_DEFAULT << 0'
export const GPIO_EUART_ROUTEEN_TXPEN: any = '0x1UL << 1'
export const GPIO_EUART_CTSROUTE_PORT_DEFAULT: any = '_GPIO_EUART_CTSROUTE_PORT_DEFAULT << 0'
export const GPIO_EUART_RTSROUTE_PORT_DEFAULT: any = '_GPIO_EUART_RTSROUTE_PORT_DEFAULT << 0'
export const GPIO_EUART_RXROUTE_PORT_DEFAULT: any = '_GPIO_EUART_RXROUTE_PORT_DEFAULT << 0'
export const GPIO_EUART_TXROUTE_PORT_DEFAULT: any = '_GPIO_EUART_TXROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ROUTEEN_ANT1PEN: any = '0x1UL << 1'
export const GPIO_MODEM_ROUTEEN_ANTROLLOVERPEN: any = '0x1UL << 2'
export const GPIO_MODEM_ROUTEEN_ANTRR0PEN: any = '0x1UL << 3'
export const GPIO_MODEM_ROUTEEN_ANTRR1PEN: any = '0x1UL << 4'
export const GPIO_MODEM_ROUTEEN_ANTRR2PEN: any = '0x1UL << 5'
export const GPIO_MODEM_ROUTEEN_ANTRR3PEN: any = '0x1UL << 6'
export const GPIO_MODEM_ROUTEEN_ANTRR4PEN: any = '0x1UL << 7'
export const GPIO_MODEM_ROUTEEN_ANTRR5PEN: any = '0x1UL << 8'
export const GPIO_MODEM_ROUTEEN_ANTSWENPEN: any = '0x1UL << 9'
export const GPIO_MODEM_ROUTEEN_ANTSWUSPEN: any = '0x1UL << 10'
export const GPIO_MODEM_ROUTEEN_ANTTRIGPEN: any = '0x1UL << 11'
export const GPIO_MODEM_ROUTEEN_ANTTRIGSTOPPEN: any = '0x1UL << 12'
export const GPIO_MODEM_ROUTEEN_DCLKPEN: any = '0x1UL << 13'
export const GPIO_MODEM_ROUTEEN_DOUTPEN: any = '0x1UL << 14'
export const GPIO_MODEM_ANT0ROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANT0ROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANT1ROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANT1ROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTROLLOVERROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTROLLOVERROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTRR0ROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTRR0ROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTRR1ROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTRR1ROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTRR2ROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTRR2ROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTRR3ROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTRR3ROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTRR4ROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTRR4ROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTRR5ROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTRR5ROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTSWENROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTSWENROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTSWUSROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTSWUSROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTTRIGROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTTRIGROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_ANTTRIGSTOPROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_ANTTRIGSTOPROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_DCLKROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_DCLKROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_DINROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_DINROUTE_PORT_DEFAULT << 0'
export const GPIO_MODEM_DOUTROUTE_PORT_DEFAULT: any = '_GPIO_MODEM_DOUTROUTE_PORT_DEFAULT << 0'
export const GPIO_PDM_CLKROUTE_PORT_DEFAULT: any = '_GPIO_PDM_CLKROUTE_PORT_DEFAULT << 0'
export const GPIO_PDM_DAT0ROUTE_PORT_DEFAULT: any = '_GPIO_PDM_DAT0ROUTE_PORT_DEFAULT << 0'
export const GPIO_PDM_DAT1ROUTE_PORT_DEFAULT: any = '_GPIO_PDM_DAT1ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ROUTEEN_ASYNCH1PEN: any = '0x1UL << 1'
export const GPIO_PRS_ROUTEEN_ASYNCH2PEN: any = '0x1UL << 2'
export const GPIO_PRS_ROUTEEN_ASYNCH3PEN: any = '0x1UL << 3'
export const GPIO_PRS_ROUTEEN_ASYNCH4PEN: any = '0x1UL << 4'
export const GPIO_PRS_ROUTEEN_ASYNCH5PEN: any = '0x1UL << 5'
export const GPIO_PRS_ROUTEEN_ASYNCH6PEN: any = '0x1UL << 6'
export const GPIO_PRS_ROUTEEN_ASYNCH7PEN: any = '0x1UL << 7'
export const GPIO_PRS_ROUTEEN_ASYNCH8PEN: any = '0x1UL << 8'
export const GPIO_PRS_ROUTEEN_ASYNCH9PEN: any = '0x1UL << 9'
export const GPIO_PRS_ROUTEEN_ASYNCH10PEN: any = '0x1UL << 10'
export const GPIO_PRS_ROUTEEN_ASYNCH11PEN: any = '0x1UL << 11'
export const GPIO_PRS_ROUTEEN_SYNCH0PEN: any = '0x1UL << 12'
export const GPIO_PRS_ROUTEEN_SYNCH1PEN: any = '0x1UL << 13'
export const GPIO_PRS_ROUTEEN_SYNCH2PEN: any = '0x1UL << 14'
export const GPIO_PRS_ROUTEEN_SYNCH3PEN: any = '0x1UL << 15'
export const GPIO_PRS_ASYNCH0ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH0ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH1ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH1ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH2ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH2ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH3ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH3ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH4ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH4ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH5ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH5ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH6ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH6ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH7ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH7ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH8ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH8ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH9ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH9ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH10ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH10ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_ASYNCH11ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_ASYNCH11ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_SYNCH0ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_SYNCH0ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_SYNCH1ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_SYNCH1ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_SYNCH2ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_SYNCH2ROUTE_PORT_DEFAULT << 0'
export const GPIO_PRS_SYNCH3ROUTE_PORT_DEFAULT: any = '_GPIO_PRS_SYNCH3ROUTE_PORT_DEFAULT << 0'
export const GPIO_TIMER_ROUTEEN_CC1PEN: any = '0x1UL << 1'
export const GPIO_TIMER_ROUTEEN_CC2PEN: any = '0x1UL << 2'
export const GPIO_TIMER_ROUTEEN_CCC0PEN: any = '0x1UL << 3'
export const GPIO_TIMER_ROUTEEN_CCC1PEN: any = '0x1UL << 4'
export const GPIO_TIMER_ROUTEEN_CCC2PEN: any = '0x1UL << 5'
export const GPIO_TIMER_CC0ROUTE_PORT_DEFAULT: any = '_GPIO_TIMER_CC0ROUTE_PORT_DEFAULT << 0'
export const GPIO_TIMER_CC1ROUTE_PORT_DEFAULT: any = '_GPIO_TIMER_CC1ROUTE_PORT_DEFAULT << 0'
export const GPIO_TIMER_CC2ROUTE_PORT_DEFAULT: any = '_GPIO_TIMER_CC2ROUTE_PORT_DEFAULT << 0'
export const GPIO_TIMER_CDTI0ROUTE_PORT_DEFAULT: any = '_GPIO_TIMER_CDTI0ROUTE_PORT_DEFAULT << 0'
export const GPIO_TIMER_CDTI1ROUTE_PORT_DEFAULT: any = '_GPIO_TIMER_CDTI1ROUTE_PORT_DEFAULT << 0'
export const GPIO_TIMER_CDTI2ROUTE_PORT_DEFAULT: any = '_GPIO_TIMER_CDTI2ROUTE_PORT_DEFAULT << 0'
export const GPIO_USART_ROUTEEN_RTSPEN: any = '0x1UL << 1'
export const GPIO_USART_ROUTEEN_RXPEN: any = '0x1UL << 2'
export const GPIO_USART_ROUTEEN_CLKPEN: any = '0x1UL << 3'
export const GPIO_USART_ROUTEEN_TXPEN: any = '0x1UL << 4'
export const GPIO_USART_CSROUTE_PORT_DEFAULT: any = '_GPIO_USART_CSROUTE_PORT_DEFAULT << 0'
export const GPIO_USART_CTSROUTE_PORT_DEFAULT: any = '_GPIO_USART_CTSROUTE_PORT_DEFAULT << 0'
export const GPIO_USART_RTSROUTE_PORT_DEFAULT: any = '_GPIO_USART_RTSROUTE_PORT_DEFAULT << 0'
export const GPIO_USART_RXROUTE_PORT_DEFAULT: any = '_GPIO_USART_RXROUTE_PORT_DEFAULT << 0'
export const GPIO_USART_CLKROUTE_PORT_DEFAULT: any = '_GPIO_USART_CLKROUTE_PORT_DEFAULT << 0'
export const GPIO_USART_TXROUTE_PORT_DEFAULT: any = '_GPIO_USART_TXROUTE_PORT_DEFAULT << 0'

// -------- GPIO_PORT -------- //

export interface GPIO_PORT_t {
    CTRL: $Reg
    MODEL: $Reg
    MODEH: $Reg
    DOUT: $Reg
    DIN: $Reg
}
export const GPIO_P_CTRL_SLEWRATE_DEFAULT: any = '_GPIO_P_CTRL_SLEWRATE_DEFAULT << 4'
export const GPIO_P_CTRL_DINDIS: any = '0x1UL << 12'
export const GPIO_P_CTRL_DINDISALT: any = '0x1UL << 28'
export const GPIO_P_MODEL_MODE0_DEFAULT: any = '_GPIO_P_MODEL_MODE0_DEFAULT << 0'
export const GPIO_P_MODEL_MODE0_DISABLED: any = '_GPIO_P_MODEL_MODE0_DISABLED << 0'
export const GPIO_P_MODEL_MODE0_INPUT: any = '_GPIO_P_MODEL_MODE0_INPUT << 0'
export const GPIO_P_MODEL_MODE0_INPUTPULL: any = '_GPIO_P_MODEL_MODE0_INPUTPULL << 0'
export const GPIO_P_MODEL_MODE0_INPUTPULLFILTER: any = '_GPIO_P_MODEL_MODE0_INPUTPULLFILTER << 0'
export const GPIO_P_MODEL_MODE0_PUSHPULL: any = '_GPIO_P_MODEL_MODE0_PUSHPULL << 0'
export const GPIO_P_MODEL_MODE0_PUSHPULLALT: any = '_GPIO_P_MODEL_MODE0_PUSHPULLALT << 0'
export const GPIO_P_MODEL_MODE0_WIREDOR: any = '_GPIO_P_MODEL_MODE0_WIREDOR << 0'
export const GPIO_P_MODEL_MODE0_WIREDORPULLDOWN: any = '_GPIO_P_MODEL_MODE0_WIREDORPULLDOWN << 0'
export const GPIO_P_MODEL_MODE0_WIREDAND: any = '_GPIO_P_MODEL_MODE0_WIREDAND << 0'
export const GPIO_P_MODEL_MODE0_WIREDANDFILTER: any = '_GPIO_P_MODEL_MODE0_WIREDANDFILTER << 0'
export const GPIO_P_MODEL_MODE0_WIREDANDPULLUP: any = '_GPIO_P_MODEL_MODE0_WIREDANDPULLUP << 0'
export const GPIO_P_MODEL_MODE0_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEL_MODE0_WIREDANDPULLUPFILTER << 0'
export const GPIO_P_MODEL_MODE0_WIREDANDALT: any = '_GPIO_P_MODEL_MODE0_WIREDANDALT << 0'
export const GPIO_P_MODEL_MODE0_WIREDANDALTFILTER: any = '_GPIO_P_MODEL_MODE0_WIREDANDALTFILTER << 0'
export const GPIO_P_MODEL_MODE0_WIREDANDALTPULLUP: any = '_GPIO_P_MODEL_MODE0_WIREDANDALTPULLUP << 0'
export const GPIO_P_MODEL_MODE0_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEL_MODE0_WIREDANDALTPULLUPFILTER << 0'
export const GPIO_P_MODEL_MODE1_DISABLED: any = '_GPIO_P_MODEL_MODE1_DISABLED << 4'
export const GPIO_P_MODEL_MODE1_INPUT: any = '_GPIO_P_MODEL_MODE1_INPUT << 4'
export const GPIO_P_MODEL_MODE1_INPUTPULL: any = '_GPIO_P_MODEL_MODE1_INPUTPULL << 4'
export const GPIO_P_MODEL_MODE1_INPUTPULLFILTER: any = '_GPIO_P_MODEL_MODE1_INPUTPULLFILTER << 4'
export const GPIO_P_MODEL_MODE1_PUSHPULL: any = '_GPIO_P_MODEL_MODE1_PUSHPULL << 4'
export const GPIO_P_MODEL_MODE1_PUSHPULLALT: any = '_GPIO_P_MODEL_MODE1_PUSHPULLALT << 4'
export const GPIO_P_MODEL_MODE1_WIREDOR: any = '_GPIO_P_MODEL_MODE1_WIREDOR << 4'
export const GPIO_P_MODEL_MODE1_WIREDORPULLDOWN: any = '_GPIO_P_MODEL_MODE1_WIREDORPULLDOWN << 4'
export const GPIO_P_MODEL_MODE1_WIREDAND: any = '_GPIO_P_MODEL_MODE1_WIREDAND << 4'
export const GPIO_P_MODEL_MODE1_WIREDANDFILTER: any = '_GPIO_P_MODEL_MODE1_WIREDANDFILTER << 4'
export const GPIO_P_MODEL_MODE1_WIREDANDPULLUP: any = '_GPIO_P_MODEL_MODE1_WIREDANDPULLUP << 4'
export const GPIO_P_MODEL_MODE1_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEL_MODE1_WIREDANDPULLUPFILTER << 4'
export const GPIO_P_MODEL_MODE1_WIREDANDALT: any = '_GPIO_P_MODEL_MODE1_WIREDANDALT << 4'
export const GPIO_P_MODEL_MODE1_WIREDANDALTFILTER: any = '_GPIO_P_MODEL_MODE1_WIREDANDALTFILTER << 4'
export const GPIO_P_MODEL_MODE1_WIREDANDALTPULLUP: any = '_GPIO_P_MODEL_MODE1_WIREDANDALTPULLUP << 4'
export const GPIO_P_MODEL_MODE1_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEL_MODE1_WIREDANDALTPULLUPFILTER << 4'
export const GPIO_P_MODEL_MODE2_DISABLED: any = '_GPIO_P_MODEL_MODE2_DISABLED << 8'
export const GPIO_P_MODEL_MODE2_INPUT: any = '_GPIO_P_MODEL_MODE2_INPUT << 8'
export const GPIO_P_MODEL_MODE2_INPUTPULL: any = '_GPIO_P_MODEL_MODE2_INPUTPULL << 8'
export const GPIO_P_MODEL_MODE2_INPUTPULLFILTER: any = '_GPIO_P_MODEL_MODE2_INPUTPULLFILTER << 8'
export const GPIO_P_MODEL_MODE2_PUSHPULL: any = '_GPIO_P_MODEL_MODE2_PUSHPULL << 8'
export const GPIO_P_MODEL_MODE2_PUSHPULLALT: any = '_GPIO_P_MODEL_MODE2_PUSHPULLALT << 8'
export const GPIO_P_MODEL_MODE2_WIREDOR: any = '_GPIO_P_MODEL_MODE2_WIREDOR << 8'
export const GPIO_P_MODEL_MODE2_WIREDORPULLDOWN: any = '_GPIO_P_MODEL_MODE2_WIREDORPULLDOWN << 8'
export const GPIO_P_MODEL_MODE2_WIREDAND: any = '_GPIO_P_MODEL_MODE2_WIREDAND << 8'
export const GPIO_P_MODEL_MODE2_WIREDANDFILTER: any = '_GPIO_P_MODEL_MODE2_WIREDANDFILTER << 8'
export const GPIO_P_MODEL_MODE2_WIREDANDPULLUP: any = '_GPIO_P_MODEL_MODE2_WIREDANDPULLUP << 8'
export const GPIO_P_MODEL_MODE2_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEL_MODE2_WIREDANDPULLUPFILTER << 8'
export const GPIO_P_MODEL_MODE2_WIREDANDALT: any = '_GPIO_P_MODEL_MODE2_WIREDANDALT << 8'
export const GPIO_P_MODEL_MODE2_WIREDANDALTFILTER: any = '_GPIO_P_MODEL_MODE2_WIREDANDALTFILTER << 8'
export const GPIO_P_MODEL_MODE2_WIREDANDALTPULLUP: any = '_GPIO_P_MODEL_MODE2_WIREDANDALTPULLUP << 8'
export const GPIO_P_MODEL_MODE2_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEL_MODE2_WIREDANDALTPULLUPFILTER << 8'
export const GPIO_P_MODEL_MODE3_DISABLED: any = '_GPIO_P_MODEL_MODE3_DISABLED << 12'
export const GPIO_P_MODEL_MODE3_INPUT: any = '_GPIO_P_MODEL_MODE3_INPUT << 12'
export const GPIO_P_MODEL_MODE3_INPUTPULL: any = '_GPIO_P_MODEL_MODE3_INPUTPULL << 12'
export const GPIO_P_MODEL_MODE3_INPUTPULLFILTER: any = '_GPIO_P_MODEL_MODE3_INPUTPULLFILTER << 12'
export const GPIO_P_MODEL_MODE3_PUSHPULL: any = '_GPIO_P_MODEL_MODE3_PUSHPULL << 12'
export const GPIO_P_MODEL_MODE3_PUSHPULLALT: any = '_GPIO_P_MODEL_MODE3_PUSHPULLALT << 12'
export const GPIO_P_MODEL_MODE3_WIREDOR: any = '_GPIO_P_MODEL_MODE3_WIREDOR << 12'
export const GPIO_P_MODEL_MODE3_WIREDORPULLDOWN: any = '_GPIO_P_MODEL_MODE3_WIREDORPULLDOWN << 12'
export const GPIO_P_MODEL_MODE3_WIREDAND: any = '_GPIO_P_MODEL_MODE3_WIREDAND << 12'
export const GPIO_P_MODEL_MODE3_WIREDANDFILTER: any = '_GPIO_P_MODEL_MODE3_WIREDANDFILTER << 12'
export const GPIO_P_MODEL_MODE3_WIREDANDPULLUP: any = '_GPIO_P_MODEL_MODE3_WIREDANDPULLUP << 12'
export const GPIO_P_MODEL_MODE3_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEL_MODE3_WIREDANDPULLUPFILTER << 12'
export const GPIO_P_MODEL_MODE3_WIREDANDALT: any = '_GPIO_P_MODEL_MODE3_WIREDANDALT << 12'
export const GPIO_P_MODEL_MODE3_WIREDANDALTFILTER: any = '_GPIO_P_MODEL_MODE3_WIREDANDALTFILTER << 12'
export const GPIO_P_MODEL_MODE3_WIREDANDALTPULLUP: any = '_GPIO_P_MODEL_MODE3_WIREDANDALTPULLUP << 12'
export const GPIO_P_MODEL_MODE3_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEL_MODE3_WIREDANDALTPULLUPFILTER << 12'
export const GPIO_P_MODEL_MODE4_DISABLED: any = '_GPIO_P_MODEL_MODE4_DISABLED << 16'
export const GPIO_P_MODEL_MODE4_INPUT: any = '_GPIO_P_MODEL_MODE4_INPUT << 16'
export const GPIO_P_MODEL_MODE4_INPUTPULL: any = '_GPIO_P_MODEL_MODE4_INPUTPULL << 16'
export const GPIO_P_MODEL_MODE4_INPUTPULLFILTER: any = '_GPIO_P_MODEL_MODE4_INPUTPULLFILTER << 16'
export const GPIO_P_MODEL_MODE4_PUSHPULL: any = '_GPIO_P_MODEL_MODE4_PUSHPULL << 16'
export const GPIO_P_MODEL_MODE4_PUSHPULLALT: any = '_GPIO_P_MODEL_MODE4_PUSHPULLALT << 16'
export const GPIO_P_MODEL_MODE4_WIREDOR: any = '_GPIO_P_MODEL_MODE4_WIREDOR << 16'
export const GPIO_P_MODEL_MODE4_WIREDORPULLDOWN: any = '_GPIO_P_MODEL_MODE4_WIREDORPULLDOWN << 16'
export const GPIO_P_MODEL_MODE4_WIREDAND: any = '_GPIO_P_MODEL_MODE4_WIREDAND << 16'
export const GPIO_P_MODEL_MODE4_WIREDANDFILTER: any = '_GPIO_P_MODEL_MODE4_WIREDANDFILTER << 16'
export const GPIO_P_MODEL_MODE4_WIREDANDPULLUP: any = '_GPIO_P_MODEL_MODE4_WIREDANDPULLUP << 16'
export const GPIO_P_MODEL_MODE4_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEL_MODE4_WIREDANDPULLUPFILTER << 16'
export const GPIO_P_MODEL_MODE4_WIREDANDALT: any = '_GPIO_P_MODEL_MODE4_WIREDANDALT << 16'
export const GPIO_P_MODEL_MODE4_WIREDANDALTFILTER: any = '_GPIO_P_MODEL_MODE4_WIREDANDALTFILTER << 16'
export const GPIO_P_MODEL_MODE4_WIREDANDALTPULLUP: any = '_GPIO_P_MODEL_MODE4_WIREDANDALTPULLUP << 16'
export const GPIO_P_MODEL_MODE4_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEL_MODE4_WIREDANDALTPULLUPFILTER << 16'
export const GPIO_P_MODEL_MODE5_DISABLED: any = '_GPIO_P_MODEL_MODE5_DISABLED << 20'
export const GPIO_P_MODEL_MODE5_INPUT: any = '_GPIO_P_MODEL_MODE5_INPUT << 20'
export const GPIO_P_MODEL_MODE5_INPUTPULL: any = '_GPIO_P_MODEL_MODE5_INPUTPULL << 20'
export const GPIO_P_MODEL_MODE5_INPUTPULLFILTER: any = '_GPIO_P_MODEL_MODE5_INPUTPULLFILTER << 20'
export const GPIO_P_MODEL_MODE5_PUSHPULL: any = '_GPIO_P_MODEL_MODE5_PUSHPULL << 20'
export const GPIO_P_MODEL_MODE5_PUSHPULLALT: any = '_GPIO_P_MODEL_MODE5_PUSHPULLALT << 20'
export const GPIO_P_MODEL_MODE5_WIREDOR: any = '_GPIO_P_MODEL_MODE5_WIREDOR << 20'
export const GPIO_P_MODEL_MODE5_WIREDORPULLDOWN: any = '_GPIO_P_MODEL_MODE5_WIREDORPULLDOWN << 20'
export const GPIO_P_MODEL_MODE5_WIREDAND: any = '_GPIO_P_MODEL_MODE5_WIREDAND << 20'
export const GPIO_P_MODEL_MODE5_WIREDANDFILTER: any = '_GPIO_P_MODEL_MODE5_WIREDANDFILTER << 20'
export const GPIO_P_MODEL_MODE5_WIREDANDPULLUP: any = '_GPIO_P_MODEL_MODE5_WIREDANDPULLUP << 20'
export const GPIO_P_MODEL_MODE5_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEL_MODE5_WIREDANDPULLUPFILTER << 20'
export const GPIO_P_MODEL_MODE5_WIREDANDALT: any = '_GPIO_P_MODEL_MODE5_WIREDANDALT << 20'
export const GPIO_P_MODEL_MODE5_WIREDANDALTFILTER: any = '_GPIO_P_MODEL_MODE5_WIREDANDALTFILTER << 20'
export const GPIO_P_MODEL_MODE5_WIREDANDALTPULLUP: any = '_GPIO_P_MODEL_MODE5_WIREDANDALTPULLUP << 20'
export const GPIO_P_MODEL_MODE5_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEL_MODE5_WIREDANDALTPULLUPFILTER << 20'
export const GPIO_P_MODEL_MODE6_DISABLED: any = '_GPIO_P_MODEL_MODE6_DISABLED << 24'
export const GPIO_P_MODEL_MODE6_INPUT: any = '_GPIO_P_MODEL_MODE6_INPUT << 24'
export const GPIO_P_MODEL_MODE6_INPUTPULL: any = '_GPIO_P_MODEL_MODE6_INPUTPULL << 24'
export const GPIO_P_MODEL_MODE6_INPUTPULLFILTER: any = '_GPIO_P_MODEL_MODE6_INPUTPULLFILTER << 24'
export const GPIO_P_MODEL_MODE6_PUSHPULL: any = '_GPIO_P_MODEL_MODE6_PUSHPULL << 24'
export const GPIO_P_MODEL_MODE6_PUSHPULLALT: any = '_GPIO_P_MODEL_MODE6_PUSHPULLALT << 24'
export const GPIO_P_MODEL_MODE6_WIREDOR: any = '_GPIO_P_MODEL_MODE6_WIREDOR << 24'
export const GPIO_P_MODEL_MODE6_WIREDORPULLDOWN: any = '_GPIO_P_MODEL_MODE6_WIREDORPULLDOWN << 24'
export const GPIO_P_MODEL_MODE6_WIREDAND: any = '_GPIO_P_MODEL_MODE6_WIREDAND << 24'
export const GPIO_P_MODEL_MODE6_WIREDANDFILTER: any = '_GPIO_P_MODEL_MODE6_WIREDANDFILTER << 24'
export const GPIO_P_MODEL_MODE6_WIREDANDPULLUP: any = '_GPIO_P_MODEL_MODE6_WIREDANDPULLUP << 24'
export const GPIO_P_MODEL_MODE6_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEL_MODE6_WIREDANDPULLUPFILTER << 24'
export const GPIO_P_MODEL_MODE6_WIREDANDALT: any = '_GPIO_P_MODEL_MODE6_WIREDANDALT << 24'
export const GPIO_P_MODEL_MODE6_WIREDANDALTFILTER: any = '_GPIO_P_MODEL_MODE6_WIREDANDALTFILTER << 24'
export const GPIO_P_MODEL_MODE6_WIREDANDALTPULLUP: any = '_GPIO_P_MODEL_MODE6_WIREDANDALTPULLUP << 24'
export const GPIO_P_MODEL_MODE6_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEL_MODE6_WIREDANDALTPULLUPFILTER << 24'
export const GPIO_P_MODEL_MODE7_DISABLED: any = '_GPIO_P_MODEL_MODE7_DISABLED << 28'
export const GPIO_P_MODEL_MODE7_INPUT: any = '_GPIO_P_MODEL_MODE7_INPUT << 28'
export const GPIO_P_MODEL_MODE7_INPUTPULL: any = '_GPIO_P_MODEL_MODE7_INPUTPULL << 28'
export const GPIO_P_MODEL_MODE7_INPUTPULLFILTER: any = '_GPIO_P_MODEL_MODE7_INPUTPULLFILTER << 28'
export const GPIO_P_MODEL_MODE7_PUSHPULL: any = '_GPIO_P_MODEL_MODE7_PUSHPULL << 28'
export const GPIO_P_MODEL_MODE7_PUSHPULLALT: any = '_GPIO_P_MODEL_MODE7_PUSHPULLALT << 28'
export const GPIO_P_MODEL_MODE7_WIREDOR: any = '_GPIO_P_MODEL_MODE7_WIREDOR << 28'
export const GPIO_P_MODEL_MODE7_WIREDORPULLDOWN: any = '_GPIO_P_MODEL_MODE7_WIREDORPULLDOWN << 28'
export const GPIO_P_MODEL_MODE7_WIREDAND: any = '_GPIO_P_MODEL_MODE7_WIREDAND << 28'
export const GPIO_P_MODEL_MODE7_WIREDANDFILTER: any = '_GPIO_P_MODEL_MODE7_WIREDANDFILTER << 28'
export const GPIO_P_MODEL_MODE7_WIREDANDPULLUP: any = '_GPIO_P_MODEL_MODE7_WIREDANDPULLUP << 28'
export const GPIO_P_MODEL_MODE7_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEL_MODE7_WIREDANDPULLUPFILTER << 28'
export const GPIO_P_MODEL_MODE7_WIREDANDALT: any = '_GPIO_P_MODEL_MODE7_WIREDANDALT << 28'
export const GPIO_P_MODEL_MODE7_WIREDANDALTFILTER: any = '_GPIO_P_MODEL_MODE7_WIREDANDALTFILTER << 28'
export const GPIO_P_MODEL_MODE7_WIREDANDALTPULLUP: any = '_GPIO_P_MODEL_MODE7_WIREDANDALTPULLUP << 28'
export const GPIO_P_MODEL_MODE7_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEL_MODE7_WIREDANDALTPULLUPFILTER << 28'
export const GPIO_P_MODEH_MODE0_DEFAULT: any = '_GPIO_P_MODEH_MODE0_DEFAULT << 0'
export const GPIO_P_MODEH_MODE0_DISABLED: any = '_GPIO_P_MODEH_MODE0_DISABLED << 0'
export const GPIO_P_MODEH_MODE0_INPUT: any = '_GPIO_P_MODEH_MODE0_INPUT << 0'
export const GPIO_P_MODEH_MODE0_INPUTPULL: any = '_GPIO_P_MODEH_MODE0_INPUTPULL << 0'
export const GPIO_P_MODEH_MODE0_INPUTPULLFILTER: any = '_GPIO_P_MODEH_MODE0_INPUTPULLFILTER << 0'
export const GPIO_P_MODEH_MODE0_PUSHPULL: any = '_GPIO_P_MODEH_MODE0_PUSHPULL << 0'
export const GPIO_P_MODEH_MODE0_PUSHPULLALT: any = '_GPIO_P_MODEH_MODE0_PUSHPULLALT << 0'
export const GPIO_P_MODEH_MODE0_WIREDOR: any = '_GPIO_P_MODEH_MODE0_WIREDOR << 0'
export const GPIO_P_MODEH_MODE0_WIREDORPULLDOWN: any = '_GPIO_P_MODEH_MODE0_WIREDORPULLDOWN << 0'
export const GPIO_P_MODEH_MODE0_WIREDAND: any = '_GPIO_P_MODEH_MODE0_WIREDAND << 0'
export const GPIO_P_MODEH_MODE0_WIREDANDFILTER: any = '_GPIO_P_MODEH_MODE0_WIREDANDFILTER << 0'
export const GPIO_P_MODEH_MODE0_WIREDANDPULLUP: any = '_GPIO_P_MODEH_MODE0_WIREDANDPULLUP << 0'
export const GPIO_P_MODEH_MODE0_WIREDANDPULLUPFILTER: any = '_GPIO_P_MODEH_MODE0_WIREDANDPULLUPFILTER << 0'
export const GPIO_P_MODEH_MODE0_WIREDANDALT: any = '_GPIO_P_MODEH_MODE0_WIREDANDALT << 0'
export const GPIO_P_MODEH_MODE0_WIREDANDALTFILTER: any = '_GPIO_P_MODEH_MODE0_WIREDANDALTFILTER << 0'
export const GPIO_P_MODEH_MODE0_WIREDANDALTPULLUP: any = '_GPIO_P_MODEH_MODE0_WIREDANDALTPULLUP << 0'
export const GPIO_P_MODEH_MODE0_WIREDANDALTPULLUPFILTER: any = '_GPIO_P_MODEH_MODE0_WIREDANDALTPULLUPFILTER << 0'
export const GPIO_P_DOUT_DOUT_DEFAULT: any = '_GPIO_P_DOUT_DOUT_DEFAULT << 0'
export const GPIO_P_DIN_DIN_DEFAULT: any = '_GPIO_P_DIN_DIN_DEFAULT << 0'

// -------- INSTANCES -------- //

export const CMU = {} as CMU_t
export const GPIO = {} as GPIO_t
