import em from '@$$emscript'
export const $U = em.$declare('COMPOSITE')

export function em$generate() {
    let out = $outfile('nrf.distro.54lxx/REGS.hpp')
    out.addFile('../nrf.54lxx/nrf.distro.54lxx/REGS.hpp.txt')
    out.close()
}

// -------- GPIO -------- //

export interface GPIO_t {
    OUT: em.$Reg
    OUTSET: em.$Reg
    OUTCLR: em.$Reg
    IN: em.$Reg
    DIR: em.$Reg
    DIRSET: em.$Reg
    DIRCLR: em.$Reg
    RESERVED: em.$Reg
    LATCH: em.$Reg
    DETECTMODE: em.$Reg
    RESERVED1: dim_t<em.$Reg, 22>
    PIN_CNF: dim_t<em.$Reg, 32>
}

// -------- UARTE_TASKS_DMA_RX -------- //

export interface UARTE_TASKS_DMA_RX_t {
    START: em.$Reg
    STOP: em.$Reg
    ENABLEMATCH: dim_t<em.$Reg, 4>
    DISABLEMATCH: dim_t<em.$Reg, 4>
}

// -------- UARTE_TASKS_DMA_TX -------- //

export interface UARTE_TASKS_DMA_TX_t {
    START: em.$Reg
    STOP: em.$Reg
}

// -------- UARTE_TASKS_DMA -------- //

export interface UARTE_TASKS_DMA_t {
    RX: UARTE_TASKS_DMA_RX_t
    TX: UARTE_TASKS_DMA_TX_t
}

// -------- UARTE_SUBSCRIBE_DMA_RX -------- //

export interface UARTE_SUBSCRIBE_DMA_RX_t {
    START: em.$Reg
    STOP: em.$Reg
    ENABLEMATCH: dim_t<em.$Reg, 4>
    DISABLEMATCH: dim_t<em.$Reg, 4>
}

// -------- UARTE_SUBSCRIBE_DMA_TX -------- //

export interface UARTE_SUBSCRIBE_DMA_TX_t {
    START: em.$Reg
    STOP: em.$Reg
}

// -------- UARTE_SUBSCRIBE_DMA -------- //

export interface UARTE_SUBSCRIBE_DMA_t {
    RX: UARTE_SUBSCRIBE_DMA_RX_t
    TX: UARTE_SUBSCRIBE_DMA_TX_t
}

// -------- UARTE_EVENTS_DMA_RX -------- //

export interface UARTE_EVENTS_DMA_RX_t {
    END: em.$Reg
    READY: em.$Reg
    BUSERROR: em.$Reg
    MATCH: dim_t<em.$Reg, 4>
}

// -------- UARTE_EVENTS_DMA_TX -------- //

export interface UARTE_EVENTS_DMA_TX_t {
    END: em.$Reg
    READY: em.$Reg
    BUSERROR: em.$Reg
}

// -------- UARTE_EVENTS_DMA -------- //

export interface UARTE_EVENTS_DMA_t {
    RX: UARTE_EVENTS_DMA_RX_t
    TX: UARTE_EVENTS_DMA_TX_t
}

// -------- UARTE_PUBLISH_DMA_RX -------- //

export interface UARTE_PUBLISH_DMA_RX_t {
    END: em.$Reg
    READY: em.$Reg
    BUSERROR: em.$Reg
    MATCH: dim_t<em.$Reg, 4>
}

// -------- UARTE_PUBLISH_DMA_TX -------- //

export interface UARTE_PUBLISH_DMA_TX_t {
    END: em.$Reg
    READY: em.$Reg
    BUSERROR: em.$Reg
}

// -------- UARTE_PUBLISH_DMA -------- //

export interface UARTE_PUBLISH_DMA_t {
    RX: UARTE_PUBLISH_DMA_RX_t
    TX: UARTE_PUBLISH_DMA_TX_t
}

// -------- UARTE_PSEL -------- //

export interface UARTE_PSEL_t {
    TXD: em.$Reg
    CTS: em.$Reg
    RXD: em.$Reg
    RTS: em.$Reg
}

// -------- UARTE_DMA_RX_MATCH -------- //

export interface UARTE_DMA_RX_MATCH_t {
    CONFIG: em.$Reg
    CANDIDATE: dim_t<em.$Reg, 4>
}

// -------- UARTE_DMA_RX -------- //

export interface UARTE_DMA_RX_t {
    RESERVED: em.$Reg
    PTR: em.$Reg
    MAXCNT: em.$Reg
    AMOUNT: em.$Reg
    RESERVED1: dim_t<em.$Reg, 3>
    TERMINATEONBUSERROR: em.$Reg
    BUSERRORADDRESS: em.$Reg
    MATCH: UARTE_DMA_RX_MATCH_t
}

// -------- UARTE_DMA_TX -------- //

export interface UARTE_DMA_TX_t {
    RESERVED: em.$Reg
    PTR: em.$Reg
    MAXCNT: em.$Reg
    AMOUNT: em.$Reg
    RESERVED1: dim_t<em.$Reg, 3>
    TERMINATEONBUSERROR: em.$Reg
    BUSERRORADDRESS: em.$Reg
}

// -------- UARTE_DMA -------- //

export interface UARTE_DMA_t {
    RX: UARTE_DMA_RX_t
    TX: UARTE_DMA_TX_t
}

// -------- UARTE -------- //

export interface UARTE_t {
    RESERVED: dim_t<em.$Reg, 7>
    TASKS_FLUSHRX: em.$Reg
    RESERVED1: dim_t<em.$Reg, 2>
    TASKS_DMA: UARTE_TASKS_DMA_t
    RESERVED2: dim_t<em.$Reg, 17>
    SUBSCRIBE_FLUSHRX: em.$Reg
    RESERVED3: dim_t<em.$Reg, 2>
    SUBSCRIBE_DMA: UARTE_SUBSCRIBE_DMA_t
    RESERVED4: dim_t<em.$Reg, 10>
    EVENTS_CTS: em.$Reg
    EVENTS_NCTS: em.$Reg
    RESERVED5: em.$Reg
    EVENTS_TXDRDY: em.$Reg
    EVENTS_RXDRDY: em.$Reg
    EVENTS_ERROR: em.$Reg
    RESERVED6: dim_t<em.$Reg, 3>
    EVENTS_RXTO: em.$Reg
    RESERVED7: dim_t<em.$Reg, 2>
    EVENTS_TXSTOPPED: em.$Reg
    RESERVED8: dim_t<em.$Reg, 6>
    EVENTS_DMA: UARTE_EVENTS_DMA_t
    EVENTS_FRAMETIMEOUT: em.$Reg
    RESERVED9: dim_t<em.$Reg, 2>
    PUBLISH_CTS: em.$Reg
    PUBLISH_NCTS: em.$Reg
    RESERVED10: em.$Reg
    PUBLISH_TXDRDY: em.$Reg
    PUBLISH_RXDRDY: em.$Reg
    PUBLISH_ERROR: em.$Reg
    RESERVED11: dim_t<em.$Reg, 3>
    PUBLISH_RXTO: em.$Reg
    RESERVED12: dim_t<em.$Reg, 2>
    PUBLISH_TXSTOPPED: em.$Reg
    RESERVED13: dim_t<em.$Reg, 6>
    PUBLISH_DMA: UARTE_PUBLISH_DMA_t
    PUBLISH_FRAMETIMEOUT: em.$Reg
    RESERVED14: dim_t<em.$Reg, 2>
    SHORTS: em.$Reg
    RESERVED15: dim_t<em.$Reg, 63>
    INTEN: em.$Reg
    INTENSET: em.$Reg
    INTENCLR: em.$Reg
    RESERVED16: dim_t<em.$Reg, 93>
    ERRORSRC: em.$Reg
    RESERVED17: dim_t<em.$Reg, 31>
    ENABLE: em.$Reg
    RESERVED18: dim_t<em.$Reg, 8>
    BAUDRATE: em.$Reg
    RESERVED19: dim_t<em.$Reg, 17>
    CONFIG: em.$Reg
    RESERVED20: em.$Reg
    ADDRESS: em.$Reg
    FRAMETIMEOUT: em.$Reg
    RESERVED21: dim_t<em.$Reg, 34>
    PSEL: UARTE_PSEL_t
    RESERVED22: dim_t<em.$Reg, 59>
    DMA: UARTE_DMA_t
}

// -------- CONSTANTS -------- //

export const UARTE_TASKS_DMA_RX_START_ResetValue: any = '0x00000000UL'
export const UARTE_TASKS_DMA_RX_START_START_Pos: any = '0UL'
export const UARTE_TASKS_DMA_RX_START_START_Msk: any = '0x1UL << UARTE_TASKS_DMA_RX_START_START_Pos'
export const UARTE_TASKS_DMA_RX_START_START_Min: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_START_START_Max: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_START_START_Trigger: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_STOP_ResetValue: any = '0x00000000UL'
export const UARTE_TASKS_DMA_RX_STOP_STOP_Pos: any = '0UL'
export const UARTE_TASKS_DMA_RX_STOP_STOP_Msk: any = '0x1UL << UARTE_TASKS_DMA_RX_STOP_STOP_Pos'
export const UARTE_TASKS_DMA_RX_STOP_STOP_Min: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_STOP_STOP_Max: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_STOP_STOP_Trigger: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_MaxCount: any = '4UL'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_MaxIndex: any = '3UL'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_MinIndex: any = '0UL'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_ResetValue: any = '0x00000000UL'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_ENABLEMATCH_Pos: any = '0UL'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_ENABLEMATCH_Msk: any = '0x1UL << UARTE_TASKS_DMA_RX_ENABLEMATCH_ENABLEMATCH_Pos'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_ENABLEMATCH_Min: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_ENABLEMATCH_Max: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_ENABLEMATCH_ENABLEMATCH_Trigger: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_MaxCount: any = '4UL'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_MaxIndex: any = '3UL'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_MinIndex: any = '0UL'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_ResetValue: any = '0x00000000UL'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_DISABLEMATCH_Pos: any = '0UL'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_DISABLEMATCH_Msk: any = '0x1UL << UARTE_TASKS_DMA_RX_DISABLEMATCH_DISABLEMATCH_Pos'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_DISABLEMATCH_Min: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_DISABLEMATCH_Max: any = '0x1UL'
export const UARTE_TASKS_DMA_RX_DISABLEMATCH_DISABLEMATCH_Trigger: any = '0x1UL'
export const UARTE_TASKS_DMA_TX_START_ResetValue: any = '0x00000000UL'
export const UARTE_TASKS_DMA_TX_START_START_Pos: any = '0UL'
export const UARTE_TASKS_DMA_TX_START_START_Msk: any = '0x1UL << UARTE_TASKS_DMA_TX_START_START_Pos'
export const UARTE_TASKS_DMA_TX_START_START_Min: any = '0x1UL'
export const UARTE_TASKS_DMA_TX_START_START_Max: any = '0x1UL'
export const UARTE_TASKS_DMA_TX_START_START_Trigger: any = '0x1UL'
export const UARTE_TASKS_DMA_TX_STOP_ResetValue: any = '0x00000000UL'
export const UARTE_TASKS_DMA_TX_STOP_STOP_Pos: any = '0UL'
export const UARTE_TASKS_DMA_TX_STOP_STOP_Msk: any = '0x1UL << UARTE_TASKS_DMA_TX_STOP_STOP_Pos'
export const UARTE_TASKS_DMA_TX_STOP_STOP_Min: any = '0x1UL'
export const UARTE_TASKS_DMA_TX_STOP_STOP_Max: any = '0x1UL'
export const UARTE_TASKS_DMA_TX_STOP_STOP_Trigger: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_RX_START_ResetValue: any = '0x00000000UL'
export const UARTE_SUBSCRIBE_DMA_RX_START_CHIDX_Pos: any = '0UL'
export const UARTE_SUBSCRIBE_DMA_RX_START_CHIDX_Msk: any = '0xFFUL << UARTE_SUBSCRIBE_DMA_RX_START_CHIDX_Pos'
export const UARTE_SUBSCRIBE_DMA_RX_START_CHIDX_Min: any = '0x00UL'
export const UARTE_SUBSCRIBE_DMA_RX_START_CHIDX_Max: any = '0xFFUL'
export const UARTE_SUBSCRIBE_DMA_RX_START_EN_Pos: any = '31UL'
export const UARTE_SUBSCRIBE_DMA_RX_START_EN_Msk: any = '0x1UL << UARTE_SUBSCRIBE_DMA_RX_START_EN_Pos'
export const UARTE_SUBSCRIBE_DMA_RX_START_EN_Min: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_RX_START_EN_Max: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_RX_START_EN_Disabled: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_RX_START_EN_Enabled: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_ResetValue: any = '0x00000000UL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_CHIDX_Pos: any = '0UL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_CHIDX_Msk: any = '0xFFUL << UARTE_SUBSCRIBE_DMA_RX_STOP_CHIDX_Pos'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_CHIDX_Min: any = '0x00UL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_CHIDX_Max: any = '0xFFUL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_EN_Pos: any = '31UL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_EN_Msk: any = '0x1UL << UARTE_SUBSCRIBE_DMA_RX_STOP_EN_Pos'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_EN_Min: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_EN_Max: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_EN_Disabled: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_RX_STOP_EN_Enabled: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_MaxCount: any = '4UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_MaxIndex: any = '3UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_MinIndex: any = '0UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_ResetValue: any = '0x00000000UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_CHIDX_Pos: any = '0UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_CHIDX_Msk: any = '0xFFUL << UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_CHIDX_Pos'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_CHIDX_Min: any = '0x00UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_CHIDX_Max: any = '0xFFUL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_EN_Pos: any = '31UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_EN_Msk: any = '0x1UL << UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_EN_Pos'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_EN_Min: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_EN_Max: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_EN_Disabled: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_RX_ENABLEMATCH_EN_Enabled: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_MaxCount: any = '4UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_MaxIndex: any = '3UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_MinIndex: any = '0UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_ResetValue: any = '0x00000000UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_CHIDX_Pos: any = '0UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_CHIDX_Msk: any = '0xFFUL << UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_CHIDX_Pos'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_CHIDX_Min: any = '0x00UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_CHIDX_Max: any = '0xFFUL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_EN_Pos: any = '31UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_EN_Msk: any = '0x1UL << UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_EN_Pos'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_EN_Min: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_EN_Max: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_EN_Disabled: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_RX_DISABLEMATCH_EN_Enabled: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_TX_START_ResetValue: any = '0x00000000UL'
export const UARTE_SUBSCRIBE_DMA_TX_START_CHIDX_Pos: any = '0UL'
export const UARTE_SUBSCRIBE_DMA_TX_START_CHIDX_Msk: any = '0xFFUL << UARTE_SUBSCRIBE_DMA_TX_START_CHIDX_Pos'
export const UARTE_SUBSCRIBE_DMA_TX_START_CHIDX_Min: any = '0x00UL'
export const UARTE_SUBSCRIBE_DMA_TX_START_CHIDX_Max: any = '0xFFUL'
export const UARTE_SUBSCRIBE_DMA_TX_START_EN_Pos: any = '31UL'
export const UARTE_SUBSCRIBE_DMA_TX_START_EN_Msk: any = '0x1UL << UARTE_SUBSCRIBE_DMA_TX_START_EN_Pos'
export const UARTE_SUBSCRIBE_DMA_TX_START_EN_Min: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_TX_START_EN_Max: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_TX_START_EN_Disabled: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_TX_START_EN_Enabled: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_ResetValue: any = '0x00000000UL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_CHIDX_Pos: any = '0UL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_CHIDX_Msk: any = '0xFFUL << UARTE_SUBSCRIBE_DMA_TX_STOP_CHIDX_Pos'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_CHIDX_Min: any = '0x00UL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_CHIDX_Max: any = '0xFFUL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_EN_Pos: any = '31UL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_EN_Msk: any = '0x1UL << UARTE_SUBSCRIBE_DMA_TX_STOP_EN_Pos'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_EN_Min: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_EN_Max: any = '0x1UL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_EN_Disabled: any = '0x0UL'
export const UARTE_SUBSCRIBE_DMA_TX_STOP_EN_Enabled: any = '0x1UL'
export const UARTE_EVENTS_DMA_RX_END_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_DMA_RX_END_END_Pos: any = '0UL'
export const UARTE_EVENTS_DMA_RX_END_END_Msk: any = '0x1UL << UARTE_EVENTS_DMA_RX_END_END_Pos'
export const UARTE_EVENTS_DMA_RX_END_END_Min: any = '0x0UL'
export const UARTE_EVENTS_DMA_RX_END_END_Max: any = '0x1UL'
export const UARTE_EVENTS_DMA_RX_END_END_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_DMA_RX_END_END_Generated: any = '0x1UL'
export const UARTE_EVENTS_DMA_RX_READY_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_DMA_RX_READY_READY_Pos: any = '0UL'
export const UARTE_EVENTS_DMA_RX_READY_READY_Msk: any = '0x1UL << UARTE_EVENTS_DMA_RX_READY_READY_Pos'
export const UARTE_EVENTS_DMA_RX_READY_READY_Min: any = '0x0UL'
export const UARTE_EVENTS_DMA_RX_READY_READY_Max: any = '0x1UL'
export const UARTE_EVENTS_DMA_RX_READY_READY_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_DMA_RX_READY_READY_Generated: any = '0x1UL'
export const UARTE_EVENTS_DMA_RX_BUSERROR_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_DMA_RX_BUSERROR_BUSERROR_Pos: any = '0UL'
export const UARTE_EVENTS_DMA_RX_BUSERROR_BUSERROR_Msk: any = '0x1UL << UARTE_EVENTS_DMA_RX_BUSERROR_BUSERROR_Pos'
export const UARTE_EVENTS_DMA_RX_BUSERROR_BUSERROR_Min: any = '0x0UL'
export const UARTE_EVENTS_DMA_RX_BUSERROR_BUSERROR_Max: any = '0x1UL'
export const UARTE_EVENTS_DMA_RX_BUSERROR_BUSERROR_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_DMA_RX_BUSERROR_BUSERROR_Generated: any = '0x1UL'
export const UARTE_EVENTS_DMA_RX_MATCH_MaxCount: any = '4UL'
export const UARTE_EVENTS_DMA_RX_MATCH_MaxIndex: any = '3UL'
export const UARTE_EVENTS_DMA_RX_MATCH_MinIndex: any = '0UL'
export const UARTE_EVENTS_DMA_RX_MATCH_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_DMA_RX_MATCH_MATCH_Pos: any = '0UL'
export const UARTE_EVENTS_DMA_RX_MATCH_MATCH_Msk: any = '0x1UL << UARTE_EVENTS_DMA_RX_MATCH_MATCH_Pos'
export const UARTE_EVENTS_DMA_RX_MATCH_MATCH_Min: any = '0x0UL'
export const UARTE_EVENTS_DMA_RX_MATCH_MATCH_Max: any = '0x1UL'
export const UARTE_EVENTS_DMA_RX_MATCH_MATCH_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_DMA_RX_MATCH_MATCH_Generated: any = '0x1UL'
export const UARTE_EVENTS_DMA_TX_END_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_DMA_TX_END_END_Pos: any = '0UL'
export const UARTE_EVENTS_DMA_TX_END_END_Msk: any = '0x1UL << UARTE_EVENTS_DMA_TX_END_END_Pos'
export const UARTE_EVENTS_DMA_TX_END_END_Min: any = '0x0UL'
export const UARTE_EVENTS_DMA_TX_END_END_Max: any = '0x1UL'
export const UARTE_EVENTS_DMA_TX_END_END_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_DMA_TX_END_END_Generated: any = '0x1UL'
export const UARTE_EVENTS_DMA_TX_READY_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_DMA_TX_READY_READY_Pos: any = '0UL'
export const UARTE_EVENTS_DMA_TX_READY_READY_Msk: any = '0x1UL << UARTE_EVENTS_DMA_TX_READY_READY_Pos'
export const UARTE_EVENTS_DMA_TX_READY_READY_Min: any = '0x0UL'
export const UARTE_EVENTS_DMA_TX_READY_READY_Max: any = '0x1UL'
export const UARTE_EVENTS_DMA_TX_READY_READY_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_DMA_TX_READY_READY_Generated: any = '0x1UL'
export const UARTE_EVENTS_DMA_TX_BUSERROR_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_DMA_TX_BUSERROR_BUSERROR_Pos: any = '0UL'
export const UARTE_EVENTS_DMA_TX_BUSERROR_BUSERROR_Msk: any = '0x1UL << UARTE_EVENTS_DMA_TX_BUSERROR_BUSERROR_Pos'
export const UARTE_EVENTS_DMA_TX_BUSERROR_BUSERROR_Min: any = '0x0UL'
export const UARTE_EVENTS_DMA_TX_BUSERROR_BUSERROR_Max: any = '0x1UL'
export const UARTE_EVENTS_DMA_TX_BUSERROR_BUSERROR_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_DMA_TX_BUSERROR_BUSERROR_Generated: any = '0x1UL'
export const UARTE_PUBLISH_DMA_RX_END_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_DMA_RX_END_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_DMA_RX_END_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_DMA_RX_END_CHIDX_Pos'
export const UARTE_PUBLISH_DMA_RX_END_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_DMA_RX_END_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_DMA_RX_END_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_DMA_RX_END_EN_Msk: any = '0x1UL << UARTE_PUBLISH_DMA_RX_END_EN_Pos'
export const UARTE_PUBLISH_DMA_RX_END_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_DMA_RX_END_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_DMA_RX_END_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_DMA_RX_END_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_DMA_RX_READY_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_DMA_RX_READY_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_DMA_RX_READY_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_DMA_RX_READY_CHIDX_Pos'
export const UARTE_PUBLISH_DMA_RX_READY_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_DMA_RX_READY_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_DMA_RX_READY_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_DMA_RX_READY_EN_Msk: any = '0x1UL << UARTE_PUBLISH_DMA_RX_READY_EN_Pos'
export const UARTE_PUBLISH_DMA_RX_READY_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_DMA_RX_READY_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_DMA_RX_READY_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_DMA_RX_READY_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_DMA_RX_BUSERROR_CHIDX_Pos'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_EN_Msk: any = '0x1UL << UARTE_PUBLISH_DMA_RX_BUSERROR_EN_Pos'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_DMA_RX_BUSERROR_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_MaxCount: any = '4UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_MaxIndex: any = '3UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_MinIndex: any = '0UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_DMA_RX_MATCH_CHIDX_Pos'
export const UARTE_PUBLISH_DMA_RX_MATCH_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_DMA_RX_MATCH_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_EN_Msk: any = '0x1UL << UARTE_PUBLISH_DMA_RX_MATCH_EN_Pos'
export const UARTE_PUBLISH_DMA_RX_MATCH_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_DMA_RX_MATCH_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_DMA_TX_END_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_DMA_TX_END_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_DMA_TX_END_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_DMA_TX_END_CHIDX_Pos'
export const UARTE_PUBLISH_DMA_TX_END_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_DMA_TX_END_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_DMA_TX_END_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_DMA_TX_END_EN_Msk: any = '0x1UL << UARTE_PUBLISH_DMA_TX_END_EN_Pos'
export const UARTE_PUBLISH_DMA_TX_END_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_DMA_TX_END_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_DMA_TX_END_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_DMA_TX_END_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_DMA_TX_READY_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_DMA_TX_READY_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_DMA_TX_READY_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_DMA_TX_READY_CHIDX_Pos'
export const UARTE_PUBLISH_DMA_TX_READY_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_DMA_TX_READY_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_DMA_TX_READY_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_DMA_TX_READY_EN_Msk: any = '0x1UL << UARTE_PUBLISH_DMA_TX_READY_EN_Pos'
export const UARTE_PUBLISH_DMA_TX_READY_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_DMA_TX_READY_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_DMA_TX_READY_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_DMA_TX_READY_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_DMA_TX_BUSERROR_CHIDX_Pos'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_EN_Msk: any = '0x1UL << UARTE_PUBLISH_DMA_TX_BUSERROR_EN_Pos'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_DMA_TX_BUSERROR_EN_Enabled: any = '0x1UL'
export const UARTE_PSEL_TXD_ResetValue: any = '0xFFFFFFFFUL'
export const UARTE_PSEL_TXD_PIN_Pos: any = '0UL'
export const UARTE_PSEL_TXD_PIN_Msk: any = '0x1FUL << UARTE_PSEL_TXD_PIN_Pos'
export const UARTE_PSEL_TXD_PIN_Min: any = '0x00UL'
export const UARTE_PSEL_TXD_PIN_Max: any = '0x1FUL'
export const UARTE_PSEL_TXD_PORT_Pos: any = '5UL'
export const UARTE_PSEL_TXD_PORT_Msk: any = '0x7UL << UARTE_PSEL_TXD_PORT_Pos'
export const UARTE_PSEL_TXD_PORT_Min: any = '0x0UL'
export const UARTE_PSEL_TXD_PORT_Max: any = '0x7UL'
export const UARTE_PSEL_TXD_CONNECT_Pos: any = '31UL'
export const UARTE_PSEL_TXD_CONNECT_Msk: any = '0x1UL << UARTE_PSEL_TXD_CONNECT_Pos'
export const UARTE_PSEL_TXD_CONNECT_Min: any = '0x0UL'
export const UARTE_PSEL_TXD_CONNECT_Max: any = '0x1UL'
export const UARTE_PSEL_TXD_CONNECT_Disconnected: any = '0x1UL'
export const UARTE_PSEL_TXD_CONNECT_Connected: any = '0x0UL'
export const UARTE_PSEL_CTS_ResetValue: any = '0xFFFFFFFFUL'
export const UARTE_PSEL_CTS_PIN_Pos: any = '0UL'
export const UARTE_PSEL_CTS_PIN_Msk: any = '0x1FUL << UARTE_PSEL_CTS_PIN_Pos'
export const UARTE_PSEL_CTS_PIN_Min: any = '0x00UL'
export const UARTE_PSEL_CTS_PIN_Max: any = '0x1FUL'
export const UARTE_PSEL_CTS_PORT_Pos: any = '5UL'
export const UARTE_PSEL_CTS_PORT_Msk: any = '0x7UL << UARTE_PSEL_CTS_PORT_Pos'
export const UARTE_PSEL_CTS_PORT_Min: any = '0x0UL'
export const UARTE_PSEL_CTS_PORT_Max: any = '0x7UL'
export const UARTE_PSEL_CTS_CONNECT_Pos: any = '31UL'
export const UARTE_PSEL_CTS_CONNECT_Msk: any = '0x1UL << UARTE_PSEL_CTS_CONNECT_Pos'
export const UARTE_PSEL_CTS_CONNECT_Min: any = '0x0UL'
export const UARTE_PSEL_CTS_CONNECT_Max: any = '0x1UL'
export const UARTE_PSEL_CTS_CONNECT_Disconnected: any = '0x1UL'
export const UARTE_PSEL_CTS_CONNECT_Connected: any = '0x0UL'
export const UARTE_PSEL_RXD_ResetValue: any = '0xFFFFFFFFUL'
export const UARTE_PSEL_RXD_PIN_Pos: any = '0UL'
export const UARTE_PSEL_RXD_PIN_Msk: any = '0x1FUL << UARTE_PSEL_RXD_PIN_Pos'
export const UARTE_PSEL_RXD_PIN_Min: any = '0x00UL'
export const UARTE_PSEL_RXD_PIN_Max: any = '0x1FUL'
export const UARTE_PSEL_RXD_PORT_Pos: any = '5UL'
export const UARTE_PSEL_RXD_PORT_Msk: any = '0x7UL << UARTE_PSEL_RXD_PORT_Pos'
export const UARTE_PSEL_RXD_PORT_Min: any = '0x0UL'
export const UARTE_PSEL_RXD_PORT_Max: any = '0x7UL'
export const UARTE_PSEL_RXD_CONNECT_Pos: any = '31UL'
export const UARTE_PSEL_RXD_CONNECT_Msk: any = '0x1UL << UARTE_PSEL_RXD_CONNECT_Pos'
export const UARTE_PSEL_RXD_CONNECT_Min: any = '0x0UL'
export const UARTE_PSEL_RXD_CONNECT_Max: any = '0x1UL'
export const UARTE_PSEL_RXD_CONNECT_Disconnected: any = '0x1UL'
export const UARTE_PSEL_RXD_CONNECT_Connected: any = '0x0UL'
export const UARTE_PSEL_RTS_ResetValue: any = '0xFFFFFFFFUL'
export const UARTE_PSEL_RTS_PIN_Pos: any = '0UL'
export const UARTE_PSEL_RTS_PIN_Msk: any = '0x1FUL << UARTE_PSEL_RTS_PIN_Pos'
export const UARTE_PSEL_RTS_PIN_Min: any = '0x00UL'
export const UARTE_PSEL_RTS_PIN_Max: any = '0x1FUL'
export const UARTE_PSEL_RTS_PORT_Pos: any = '5UL'
export const UARTE_PSEL_RTS_PORT_Msk: any = '0x7UL << UARTE_PSEL_RTS_PORT_Pos'
export const UARTE_PSEL_RTS_PORT_Min: any = '0x0UL'
export const UARTE_PSEL_RTS_PORT_Max: any = '0x7UL'
export const UARTE_PSEL_RTS_CONNECT_Pos: any = '31UL'
export const UARTE_PSEL_RTS_CONNECT_Msk: any = '0x1UL << UARTE_PSEL_RTS_CONNECT_Pos'
export const UARTE_PSEL_RTS_CONNECT_Min: any = '0x0UL'
export const UARTE_PSEL_RTS_CONNECT_Max: any = '0x1UL'
export const UARTE_PSEL_RTS_CONNECT_Disconnected: any = '0x1UL'
export const UARTE_PSEL_RTS_CONNECT_Connected: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE0_Pos: any = '0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE0_Msk: any = '0x1UL << UARTE_DMA_RX_MATCH_CONFIG_ENABLE0_Pos'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE0_Min: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE0_Max: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE0_Disabled: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE0_Enabled: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE1_Pos: any = '1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE1_Msk: any = '0x1UL << UARTE_DMA_RX_MATCH_CONFIG_ENABLE1_Pos'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE1_Min: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE1_Max: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE1_Disabled: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE1_Enabled: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE2_Pos: any = '2UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE2_Msk: any = '0x1UL << UARTE_DMA_RX_MATCH_CONFIG_ENABLE2_Pos'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE2_Min: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE2_Max: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE2_Disabled: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE2_Enabled: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE3_Pos: any = '3UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE3_Msk: any = '0x1UL << UARTE_DMA_RX_MATCH_CONFIG_ENABLE3_Pos'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE3_Min: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE3_Max: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE3_Disabled: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ENABLE3_Enabled: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT0_Pos: any = '16UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT0_Msk: any = '0x1UL << UARTE_DMA_RX_MATCH_CONFIG_ONESHOT0_Pos'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT0_Min: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT0_Max: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT0_Continuous: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT0_Oneshot: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT1_Pos: any = '17UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT1_Msk: any = '0x1UL << UARTE_DMA_RX_MATCH_CONFIG_ONESHOT1_Pos'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT1_Min: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT1_Max: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT1_Continuous: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT1_Oneshot: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT2_Pos: any = '18UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT2_Msk: any = '0x1UL << UARTE_DMA_RX_MATCH_CONFIG_ONESHOT2_Pos'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT2_Min: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT2_Max: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT2_Continuous: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT2_Oneshot: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT3_Pos: any = '19UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT3_Msk: any = '0x1UL << UARTE_DMA_RX_MATCH_CONFIG_ONESHOT3_Pos'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT3_Min: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT3_Max: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT3_Continuous: any = '0x0UL'
export const UARTE_DMA_RX_MATCH_CONFIG_ONESHOT3_Oneshot: any = '0x1UL'
export const UARTE_DMA_RX_MATCH_CANDIDATE_MaxCount: any = '4UL'
export const UARTE_DMA_RX_MATCH_CANDIDATE_MaxIndex: any = '3UL'
export const UARTE_DMA_RX_MATCH_CANDIDATE_MinIndex: any = '0UL'
export const UARTE_DMA_RX_MATCH_CANDIDATE_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_RX_MATCH_CANDIDATE_DATA_Pos: any = '0UL'
export const UARTE_DMA_RX_MATCH_CANDIDATE_DATA_Msk: any = '0xFFUL << UARTE_DMA_RX_MATCH_CANDIDATE_DATA_Pos'
export const UARTE_DMA_RX_PTR_ResetValue: any = '0x20000000UL'
export const UARTE_DMA_RX_PTR_PTR_Pos: any = '0UL'
export const UARTE_DMA_RX_PTR_PTR_Msk: any = '0xFFFFFFFFUL << UARTE_DMA_RX_PTR_PTR_Pos'
export const UARTE_DMA_RX_MAXCNT_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_RX_MAXCNT_MAXCNT_Pos: any = '0UL'
export const UARTE_DMA_RX_MAXCNT_MAXCNT_Msk: any = '0xFFFFUL << UARTE_DMA_RX_MAXCNT_MAXCNT_Pos'
export const UARTE_DMA_RX_MAXCNT_MAXCNT_Min: any = '0x0001UL'
export const UARTE_DMA_RX_MAXCNT_MAXCNT_Max: any = '0xFFFFUL'
export const UARTE_DMA_RX_AMOUNT_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_RX_AMOUNT_AMOUNT_Pos: any = '0UL'
export const UARTE_DMA_RX_AMOUNT_AMOUNT_Msk: any = '0xFFFFUL << UARTE_DMA_RX_AMOUNT_AMOUNT_Pos'
export const UARTE_DMA_RX_AMOUNT_AMOUNT_Min: any = '0x0001UL'
export const UARTE_DMA_RX_AMOUNT_AMOUNT_Max: any = '0xFFFFUL'
export const UARTE_DMA_RX_TERMINATEONBUSERROR_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_RX_TERMINATEONBUSERROR_ENABLE_Pos: any = '0UL'
export const UARTE_DMA_RX_TERMINATEONBUSERROR_ENABLE_Msk: any = '0x1UL << UARTE_DMA_RX_TERMINATEONBUSERROR_ENABLE_Pos'
export const UARTE_DMA_RX_TERMINATEONBUSERROR_ENABLE_Min: any = '0x0UL'
export const UARTE_DMA_RX_TERMINATEONBUSERROR_ENABLE_Max: any = '0x1UL'
export const UARTE_DMA_RX_TERMINATEONBUSERROR_ENABLE_Disabled: any = '0x0UL'
export const UARTE_DMA_RX_TERMINATEONBUSERROR_ENABLE_Enabled: any = '0x1UL'
export const UARTE_DMA_RX_BUSERRORADDRESS_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_RX_BUSERRORADDRESS_ADDRESS_Pos: any = '0UL'
export const UARTE_DMA_RX_BUSERRORADDRESS_ADDRESS_Msk: any = '0xFFFFFFFFUL << UARTE_DMA_RX_BUSERRORADDRESS_ADDRESS_Pos'
export const UARTE_DMA_TX_PTR_ResetValue: any = '0x20000000UL'
export const UARTE_DMA_TX_PTR_PTR_Pos: any = '0UL'
export const UARTE_DMA_TX_PTR_PTR_Msk: any = '0xFFFFFFFFUL << UARTE_DMA_TX_PTR_PTR_Pos'
export const UARTE_DMA_TX_MAXCNT_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_TX_MAXCNT_MAXCNT_Pos: any = '0UL'
export const UARTE_DMA_TX_MAXCNT_MAXCNT_Msk: any = '0xFFFFUL << UARTE_DMA_TX_MAXCNT_MAXCNT_Pos'
export const UARTE_DMA_TX_MAXCNT_MAXCNT_Min: any = '0x0001UL'
export const UARTE_DMA_TX_MAXCNT_MAXCNT_Max: any = '0xFFFFUL'
export const UARTE_DMA_TX_AMOUNT_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_TX_AMOUNT_AMOUNT_Pos: any = '0UL'
export const UARTE_DMA_TX_AMOUNT_AMOUNT_Msk: any = '0xFFFFUL << UARTE_DMA_TX_AMOUNT_AMOUNT_Pos'
export const UARTE_DMA_TX_AMOUNT_AMOUNT_Min: any = '0x0001UL'
export const UARTE_DMA_TX_AMOUNT_AMOUNT_Max: any = '0xFFFFUL'
export const UARTE_DMA_TX_TERMINATEONBUSERROR_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_TX_TERMINATEONBUSERROR_ENABLE_Pos: any = '0UL'
export const UARTE_DMA_TX_TERMINATEONBUSERROR_ENABLE_Msk: any = '0x1UL << UARTE_DMA_TX_TERMINATEONBUSERROR_ENABLE_Pos'
export const UARTE_DMA_TX_TERMINATEONBUSERROR_ENABLE_Min: any = '0x0UL'
export const UARTE_DMA_TX_TERMINATEONBUSERROR_ENABLE_Max: any = '0x1UL'
export const UARTE_DMA_TX_TERMINATEONBUSERROR_ENABLE_Disabled: any = '0x0UL'
export const UARTE_DMA_TX_TERMINATEONBUSERROR_ENABLE_Enabled: any = '0x1UL'
export const UARTE_DMA_TX_BUSERRORADDRESS_ResetValue: any = '0x00000000UL'
export const UARTE_DMA_TX_BUSERRORADDRESS_ADDRESS_Pos: any = '0UL'
export const UARTE_DMA_TX_BUSERRORADDRESS_ADDRESS_Msk: any = '0xFFFFFFFFUL << UARTE_DMA_TX_BUSERRORADDRESS_ADDRESS_Pos'
export const UARTE_TASKS_FLUSHRX_ResetValue: any = '0x00000000UL'
export const UARTE_TASKS_FLUSHRX_TASKS_FLUSHRX_Pos: any = '0UL'
export const UARTE_TASKS_FLUSHRX_TASKS_FLUSHRX_Msk: any = '0x1UL << UARTE_TASKS_FLUSHRX_TASKS_FLUSHRX_Pos'
export const UARTE_TASKS_FLUSHRX_TASKS_FLUSHRX_Min: any = '0x1UL'
export const UARTE_TASKS_FLUSHRX_TASKS_FLUSHRX_Max: any = '0x1UL'
export const UARTE_TASKS_FLUSHRX_TASKS_FLUSHRX_Trigger: any = '0x1UL'
export const UARTE_SUBSCRIBE_FLUSHRX_ResetValue: any = '0x00000000UL'
export const UARTE_SUBSCRIBE_FLUSHRX_CHIDX_Pos: any = '0UL'
export const UARTE_SUBSCRIBE_FLUSHRX_CHIDX_Msk: any = '0xFFUL << UARTE_SUBSCRIBE_FLUSHRX_CHIDX_Pos'
export const UARTE_SUBSCRIBE_FLUSHRX_CHIDX_Min: any = '0x00UL'
export const UARTE_SUBSCRIBE_FLUSHRX_CHIDX_Max: any = '0xFFUL'
export const UARTE_SUBSCRIBE_FLUSHRX_EN_Pos: any = '31UL'
export const UARTE_SUBSCRIBE_FLUSHRX_EN_Msk: any = '0x1UL << UARTE_SUBSCRIBE_FLUSHRX_EN_Pos'
export const UARTE_SUBSCRIBE_FLUSHRX_EN_Min: any = '0x0UL'
export const UARTE_SUBSCRIBE_FLUSHRX_EN_Max: any = '0x1UL'
export const UARTE_SUBSCRIBE_FLUSHRX_EN_Disabled: any = '0x0UL'
export const UARTE_SUBSCRIBE_FLUSHRX_EN_Enabled: any = '0x1UL'
export const UARTE_EVENTS_CTS_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_CTS_EVENTS_CTS_Pos: any = '0UL'
export const UARTE_EVENTS_CTS_EVENTS_CTS_Msk: any = '0x1UL << UARTE_EVENTS_CTS_EVENTS_CTS_Pos'
export const UARTE_EVENTS_CTS_EVENTS_CTS_Min: any = '0x0UL'
export const UARTE_EVENTS_CTS_EVENTS_CTS_Max: any = '0x1UL'
export const UARTE_EVENTS_CTS_EVENTS_CTS_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_CTS_EVENTS_CTS_Generated: any = '0x1UL'
export const UARTE_EVENTS_NCTS_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_NCTS_EVENTS_NCTS_Pos: any = '0UL'
export const UARTE_EVENTS_NCTS_EVENTS_NCTS_Msk: any = '0x1UL << UARTE_EVENTS_NCTS_EVENTS_NCTS_Pos'
export const UARTE_EVENTS_NCTS_EVENTS_NCTS_Min: any = '0x0UL'
export const UARTE_EVENTS_NCTS_EVENTS_NCTS_Max: any = '0x1UL'
export const UARTE_EVENTS_NCTS_EVENTS_NCTS_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_NCTS_EVENTS_NCTS_Generated: any = '0x1UL'
export const UARTE_EVENTS_TXDRDY_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_TXDRDY_EVENTS_TXDRDY_Pos: any = '0UL'
export const UARTE_EVENTS_TXDRDY_EVENTS_TXDRDY_Msk: any = '0x1UL << UARTE_EVENTS_TXDRDY_EVENTS_TXDRDY_Pos'
export const UARTE_EVENTS_TXDRDY_EVENTS_TXDRDY_Min: any = '0x0UL'
export const UARTE_EVENTS_TXDRDY_EVENTS_TXDRDY_Max: any = '0x1UL'
export const UARTE_EVENTS_TXDRDY_EVENTS_TXDRDY_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_TXDRDY_EVENTS_TXDRDY_Generated: any = '0x1UL'
export const UARTE_EVENTS_RXDRDY_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_RXDRDY_EVENTS_RXDRDY_Pos: any = '0UL'
export const UARTE_EVENTS_RXDRDY_EVENTS_RXDRDY_Msk: any = '0x1UL << UARTE_EVENTS_RXDRDY_EVENTS_RXDRDY_Pos'
export const UARTE_EVENTS_RXDRDY_EVENTS_RXDRDY_Min: any = '0x0UL'
export const UARTE_EVENTS_RXDRDY_EVENTS_RXDRDY_Max: any = '0x1UL'
export const UARTE_EVENTS_RXDRDY_EVENTS_RXDRDY_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_RXDRDY_EVENTS_RXDRDY_Generated: any = '0x1UL'
export const UARTE_EVENTS_ERROR_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_ERROR_EVENTS_ERROR_Pos: any = '0UL'
export const UARTE_EVENTS_ERROR_EVENTS_ERROR_Msk: any = '0x1UL << UARTE_EVENTS_ERROR_EVENTS_ERROR_Pos'
export const UARTE_EVENTS_ERROR_EVENTS_ERROR_Min: any = '0x0UL'
export const UARTE_EVENTS_ERROR_EVENTS_ERROR_Max: any = '0x1UL'
export const UARTE_EVENTS_ERROR_EVENTS_ERROR_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_ERROR_EVENTS_ERROR_Generated: any = '0x1UL'
export const UARTE_EVENTS_RXTO_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_RXTO_EVENTS_RXTO_Pos: any = '0UL'
export const UARTE_EVENTS_RXTO_EVENTS_RXTO_Msk: any = '0x1UL << UARTE_EVENTS_RXTO_EVENTS_RXTO_Pos'
export const UARTE_EVENTS_RXTO_EVENTS_RXTO_Min: any = '0x0UL'
export const UARTE_EVENTS_RXTO_EVENTS_RXTO_Max: any = '0x1UL'
export const UARTE_EVENTS_RXTO_EVENTS_RXTO_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_RXTO_EVENTS_RXTO_Generated: any = '0x1UL'
export const UARTE_EVENTS_TXSTOPPED_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_TXSTOPPED_EVENTS_TXSTOPPED_Pos: any = '0UL'
export const UARTE_EVENTS_TXSTOPPED_EVENTS_TXSTOPPED_Msk: any = '0x1UL << UARTE_EVENTS_TXSTOPPED_EVENTS_TXSTOPPED_Pos'
export const UARTE_EVENTS_TXSTOPPED_EVENTS_TXSTOPPED_Min: any = '0x0UL'
export const UARTE_EVENTS_TXSTOPPED_EVENTS_TXSTOPPED_Max: any = '0x1UL'
export const UARTE_EVENTS_TXSTOPPED_EVENTS_TXSTOPPED_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_TXSTOPPED_EVENTS_TXSTOPPED_Generated: any = '0x1UL'
export const UARTE_EVENTS_FRAMETIMEOUT_ResetValue: any = '0x00000000UL'
export const UARTE_EVENTS_FRAMETIMEOUT_EVENTS_FRAMETIMEOUT_Pos: any = '0UL'
export const UARTE_EVENTS_FRAMETIMEOUT_EVENTS_FRAMETIMEOUT_Msk: any = '0x1UL << UARTE_EVENTS_FRAMETIMEOUT_EVENTS_FRAMETIMEOUT_Pos'
export const UARTE_EVENTS_FRAMETIMEOUT_EVENTS_FRAMETIMEOUT_Min: any = '0x0UL'
export const UARTE_EVENTS_FRAMETIMEOUT_EVENTS_FRAMETIMEOUT_Max: any = '0x1UL'
export const UARTE_EVENTS_FRAMETIMEOUT_EVENTS_FRAMETIMEOUT_NotGenerated: any = '0x0UL'
export const UARTE_EVENTS_FRAMETIMEOUT_EVENTS_FRAMETIMEOUT_Generated: any = '0x1UL'
export const UARTE_PUBLISH_CTS_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_CTS_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_CTS_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_CTS_CHIDX_Pos'
export const UARTE_PUBLISH_CTS_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_CTS_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_CTS_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_CTS_EN_Msk: any = '0x1UL << UARTE_PUBLISH_CTS_EN_Pos'
export const UARTE_PUBLISH_CTS_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_CTS_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_CTS_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_CTS_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_NCTS_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_NCTS_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_NCTS_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_NCTS_CHIDX_Pos'
export const UARTE_PUBLISH_NCTS_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_NCTS_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_NCTS_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_NCTS_EN_Msk: any = '0x1UL << UARTE_PUBLISH_NCTS_EN_Pos'
export const UARTE_PUBLISH_NCTS_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_NCTS_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_NCTS_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_NCTS_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_TXDRDY_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_TXDRDY_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_TXDRDY_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_TXDRDY_CHIDX_Pos'
export const UARTE_PUBLISH_TXDRDY_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_TXDRDY_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_TXDRDY_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_TXDRDY_EN_Msk: any = '0x1UL << UARTE_PUBLISH_TXDRDY_EN_Pos'
export const UARTE_PUBLISH_TXDRDY_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_TXDRDY_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_TXDRDY_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_TXDRDY_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_RXDRDY_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_RXDRDY_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_RXDRDY_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_RXDRDY_CHIDX_Pos'
export const UARTE_PUBLISH_RXDRDY_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_RXDRDY_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_RXDRDY_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_RXDRDY_EN_Msk: any = '0x1UL << UARTE_PUBLISH_RXDRDY_EN_Pos'
export const UARTE_PUBLISH_RXDRDY_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_RXDRDY_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_RXDRDY_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_RXDRDY_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_ERROR_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_ERROR_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_ERROR_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_ERROR_CHIDX_Pos'
export const UARTE_PUBLISH_ERROR_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_ERROR_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_ERROR_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_ERROR_EN_Msk: any = '0x1UL << UARTE_PUBLISH_ERROR_EN_Pos'
export const UARTE_PUBLISH_ERROR_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_ERROR_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_ERROR_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_ERROR_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_RXTO_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_RXTO_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_RXTO_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_RXTO_CHIDX_Pos'
export const UARTE_PUBLISH_RXTO_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_RXTO_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_RXTO_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_RXTO_EN_Msk: any = '0x1UL << UARTE_PUBLISH_RXTO_EN_Pos'
export const UARTE_PUBLISH_RXTO_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_RXTO_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_RXTO_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_RXTO_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_TXSTOPPED_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_TXSTOPPED_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_TXSTOPPED_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_TXSTOPPED_CHIDX_Pos'
export const UARTE_PUBLISH_TXSTOPPED_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_TXSTOPPED_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_TXSTOPPED_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_TXSTOPPED_EN_Msk: any = '0x1UL << UARTE_PUBLISH_TXSTOPPED_EN_Pos'
export const UARTE_PUBLISH_TXSTOPPED_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_TXSTOPPED_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_TXSTOPPED_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_TXSTOPPED_EN_Enabled: any = '0x1UL'
export const UARTE_PUBLISH_FRAMETIMEOUT_ResetValue: any = '0x00000000UL'
export const UARTE_PUBLISH_FRAMETIMEOUT_CHIDX_Pos: any = '0UL'
export const UARTE_PUBLISH_FRAMETIMEOUT_CHIDX_Msk: any = '0xFFUL << UARTE_PUBLISH_FRAMETIMEOUT_CHIDX_Pos'
export const UARTE_PUBLISH_FRAMETIMEOUT_CHIDX_Min: any = '0x00UL'
export const UARTE_PUBLISH_FRAMETIMEOUT_CHIDX_Max: any = '0xFFUL'
export const UARTE_PUBLISH_FRAMETIMEOUT_EN_Pos: any = '31UL'
export const UARTE_PUBLISH_FRAMETIMEOUT_EN_Msk: any = '0x1UL << UARTE_PUBLISH_FRAMETIMEOUT_EN_Pos'
export const UARTE_PUBLISH_FRAMETIMEOUT_EN_Min: any = '0x0UL'
export const UARTE_PUBLISH_FRAMETIMEOUT_EN_Max: any = '0x1UL'
export const UARTE_PUBLISH_FRAMETIMEOUT_EN_Disabled: any = '0x0UL'
export const UARTE_PUBLISH_FRAMETIMEOUT_EN_Enabled: any = '0x1UL'
export const UARTE_SHORTS_ResetValue: any = '0x00000000UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_START_Pos: any = '5UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_START_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_END_DMA_RX_START_Pos'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_START_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_START_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_START_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_START_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_STOP_Pos: any = '6UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_STOP_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_END_DMA_RX_STOP_Pos'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_STOP_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_STOP_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_STOP_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_END_DMA_RX_STOP_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_TX_END_DMA_TX_STOP_Pos: any = '18UL'
export const UARTE_SHORTS_DMA_TX_END_DMA_TX_STOP_Msk: any = '0x1UL << UARTE_SHORTS_DMA_TX_END_DMA_TX_STOP_Pos'
export const UARTE_SHORTS_DMA_TX_END_DMA_TX_STOP_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_TX_END_DMA_TX_STOP_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_TX_END_DMA_TX_STOP_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_TX_END_DMA_TX_STOP_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_ENABLEMATCH1_Pos: any = '21UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_ENABLEMATCH1_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_ENABLEMATCH1_Pos'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_ENABLEMATCH1_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_ENABLEMATCH1_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_ENABLEMATCH1_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_ENABLEMATCH1_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_ENABLEMATCH2_Pos: any = '22UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_ENABLEMATCH2_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_ENABLEMATCH2_Pos'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_ENABLEMATCH2_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_ENABLEMATCH2_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_ENABLEMATCH2_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_ENABLEMATCH2_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_ENABLEMATCH3_Pos: any = '23UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_ENABLEMATCH3_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_ENABLEMATCH3_Pos'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_ENABLEMATCH3_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_ENABLEMATCH3_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_ENABLEMATCH3_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_ENABLEMATCH3_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_ENABLEMATCH0_Pos: any = '24UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_ENABLEMATCH0_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_ENABLEMATCH0_Pos'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_ENABLEMATCH0_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_ENABLEMATCH0_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_ENABLEMATCH0_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_ENABLEMATCH0_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_DISABLEMATCH0_Pos: any = '25UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_DISABLEMATCH0_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_DISABLEMATCH0_Pos'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_DISABLEMATCH0_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_DISABLEMATCH0_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_DISABLEMATCH0_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH0_DMA_RX_DISABLEMATCH0_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_DISABLEMATCH1_Pos: any = '26UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_DISABLEMATCH1_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_DISABLEMATCH1_Pos'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_DISABLEMATCH1_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_DISABLEMATCH1_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_DISABLEMATCH1_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH1_DMA_RX_DISABLEMATCH1_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_DISABLEMATCH2_Pos: any = '27UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_DISABLEMATCH2_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_DISABLEMATCH2_Pos'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_DISABLEMATCH2_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_DISABLEMATCH2_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_DISABLEMATCH2_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH2_DMA_RX_DISABLEMATCH2_Enabled: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_DISABLEMATCH3_Pos: any = '28UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_DISABLEMATCH3_Msk: any = '0x1UL << UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_DISABLEMATCH3_Pos'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_DISABLEMATCH3_Min: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_DISABLEMATCH3_Max: any = '0x1UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_DISABLEMATCH3_Disabled: any = '0x0UL'
export const UARTE_SHORTS_DMA_RX_MATCH3_DMA_RX_DISABLEMATCH3_Enabled: any = '0x1UL'
export const UARTE_SHORTS_FRAMETIMEOUT_DMA_RX_STOP_Pos: any = '29UL'
export const UARTE_SHORTS_FRAMETIMEOUT_DMA_RX_STOP_Msk: any = '0x1UL << UARTE_SHORTS_FRAMETIMEOUT_DMA_RX_STOP_Pos'
export const UARTE_SHORTS_FRAMETIMEOUT_DMA_RX_STOP_Min: any = '0x0UL'
export const UARTE_SHORTS_FRAMETIMEOUT_DMA_RX_STOP_Max: any = '0x1UL'
export const UARTE_SHORTS_FRAMETIMEOUT_DMA_RX_STOP_Disabled: any = '0x0UL'
export const UARTE_SHORTS_FRAMETIMEOUT_DMA_RX_STOP_Enabled: any = '0x1UL'
export const UARTE_INTEN_ResetValue: any = '0x00000000UL'
export const UARTE_INTEN_CTS_Pos: any = '0UL'
export const UARTE_INTEN_CTS_Msk: any = '0x1UL << UARTE_INTEN_CTS_Pos'
export const UARTE_INTEN_CTS_Min: any = '0x0UL'
export const UARTE_INTEN_CTS_Max: any = '0x1UL'
export const UARTE_INTEN_CTS_Disabled: any = '0x0UL'
export const UARTE_INTEN_CTS_Enabled: any = '0x1UL'
export const UARTE_INTEN_NCTS_Pos: any = '1UL'
export const UARTE_INTEN_NCTS_Msk: any = '0x1UL << UARTE_INTEN_NCTS_Pos'
export const UARTE_INTEN_NCTS_Min: any = '0x0UL'
export const UARTE_INTEN_NCTS_Max: any = '0x1UL'
export const UARTE_INTEN_NCTS_Disabled: any = '0x0UL'
export const UARTE_INTEN_NCTS_Enabled: any = '0x1UL'
export const UARTE_INTEN_TXDRDY_Pos: any = '3UL'
export const UARTE_INTEN_TXDRDY_Msk: any = '0x1UL << UARTE_INTEN_TXDRDY_Pos'
export const UARTE_INTEN_TXDRDY_Min: any = '0x0UL'
export const UARTE_INTEN_TXDRDY_Max: any = '0x1UL'
export const UARTE_INTEN_TXDRDY_Disabled: any = '0x0UL'
export const UARTE_INTEN_TXDRDY_Enabled: any = '0x1UL'
export const UARTE_INTEN_RXDRDY_Pos: any = '4UL'
export const UARTE_INTEN_RXDRDY_Msk: any = '0x1UL << UARTE_INTEN_RXDRDY_Pos'
export const UARTE_INTEN_RXDRDY_Min: any = '0x0UL'
export const UARTE_INTEN_RXDRDY_Max: any = '0x1UL'
export const UARTE_INTEN_RXDRDY_Disabled: any = '0x0UL'
export const UARTE_INTEN_RXDRDY_Enabled: any = '0x1UL'
export const UARTE_INTEN_ERROR_Pos: any = '5UL'
export const UARTE_INTEN_ERROR_Msk: any = '0x1UL << UARTE_INTEN_ERROR_Pos'
export const UARTE_INTEN_ERROR_Min: any = '0x0UL'
export const UARTE_INTEN_ERROR_Max: any = '0x1UL'
export const UARTE_INTEN_ERROR_Disabled: any = '0x0UL'
export const UARTE_INTEN_ERROR_Enabled: any = '0x1UL'
export const UARTE_INTEN_RXTO_Pos: any = '9UL'
export const UARTE_INTEN_RXTO_Msk: any = '0x1UL << UARTE_INTEN_RXTO_Pos'
export const UARTE_INTEN_RXTO_Min: any = '0x0UL'
export const UARTE_INTEN_RXTO_Max: any = '0x1UL'
export const UARTE_INTEN_RXTO_Disabled: any = '0x0UL'
export const UARTE_INTEN_RXTO_Enabled: any = '0x1UL'
export const UARTE_INTEN_TXSTOPPED_Pos: any = '12UL'
export const UARTE_INTEN_TXSTOPPED_Msk: any = '0x1UL << UARTE_INTEN_TXSTOPPED_Pos'
export const UARTE_INTEN_TXSTOPPED_Min: any = '0x0UL'
export const UARTE_INTEN_TXSTOPPED_Max: any = '0x1UL'
export const UARTE_INTEN_TXSTOPPED_Disabled: any = '0x0UL'
export const UARTE_INTEN_TXSTOPPED_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMARXEND_Pos: any = '19UL'
export const UARTE_INTEN_DMARXEND_Msk: any = '0x1UL << UARTE_INTEN_DMARXEND_Pos'
export const UARTE_INTEN_DMARXEND_Min: any = '0x0UL'
export const UARTE_INTEN_DMARXEND_Max: any = '0x1UL'
export const UARTE_INTEN_DMARXEND_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMARXEND_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMARXREADY_Pos: any = '20UL'
export const UARTE_INTEN_DMARXREADY_Msk: any = '0x1UL << UARTE_INTEN_DMARXREADY_Pos'
export const UARTE_INTEN_DMARXREADY_Min: any = '0x0UL'
export const UARTE_INTEN_DMARXREADY_Max: any = '0x1UL'
export const UARTE_INTEN_DMARXREADY_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMARXREADY_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMARXBUSERROR_Pos: any = '21UL'
export const UARTE_INTEN_DMARXBUSERROR_Msk: any = '0x1UL << UARTE_INTEN_DMARXBUSERROR_Pos'
export const UARTE_INTEN_DMARXBUSERROR_Min: any = '0x0UL'
export const UARTE_INTEN_DMARXBUSERROR_Max: any = '0x1UL'
export const UARTE_INTEN_DMARXBUSERROR_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMARXBUSERROR_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMARXMATCH0_Pos: any = '22UL'
export const UARTE_INTEN_DMARXMATCH0_Msk: any = '0x1UL << UARTE_INTEN_DMARXMATCH0_Pos'
export const UARTE_INTEN_DMARXMATCH0_Min: any = '0x0UL'
export const UARTE_INTEN_DMARXMATCH0_Max: any = '0x1UL'
export const UARTE_INTEN_DMARXMATCH0_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMARXMATCH0_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMARXMATCH1_Pos: any = '23UL'
export const UARTE_INTEN_DMARXMATCH1_Msk: any = '0x1UL << UARTE_INTEN_DMARXMATCH1_Pos'
export const UARTE_INTEN_DMARXMATCH1_Min: any = '0x0UL'
export const UARTE_INTEN_DMARXMATCH1_Max: any = '0x1UL'
export const UARTE_INTEN_DMARXMATCH1_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMARXMATCH1_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMARXMATCH2_Pos: any = '24UL'
export const UARTE_INTEN_DMARXMATCH2_Msk: any = '0x1UL << UARTE_INTEN_DMARXMATCH2_Pos'
export const UARTE_INTEN_DMARXMATCH2_Min: any = '0x0UL'
export const UARTE_INTEN_DMARXMATCH2_Max: any = '0x1UL'
export const UARTE_INTEN_DMARXMATCH2_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMARXMATCH2_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMARXMATCH3_Pos: any = '25UL'
export const UARTE_INTEN_DMARXMATCH3_Msk: any = '0x1UL << UARTE_INTEN_DMARXMATCH3_Pos'
export const UARTE_INTEN_DMARXMATCH3_Min: any = '0x0UL'
export const UARTE_INTEN_DMARXMATCH3_Max: any = '0x1UL'
export const UARTE_INTEN_DMARXMATCH3_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMARXMATCH3_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMATXEND_Pos: any = '26UL'
export const UARTE_INTEN_DMATXEND_Msk: any = '0x1UL << UARTE_INTEN_DMATXEND_Pos'
export const UARTE_INTEN_DMATXEND_Min: any = '0x0UL'
export const UARTE_INTEN_DMATXEND_Max: any = '0x1UL'
export const UARTE_INTEN_DMATXEND_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMATXEND_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMATXREADY_Pos: any = '27UL'
export const UARTE_INTEN_DMATXREADY_Msk: any = '0x1UL << UARTE_INTEN_DMATXREADY_Pos'
export const UARTE_INTEN_DMATXREADY_Min: any = '0x0UL'
export const UARTE_INTEN_DMATXREADY_Max: any = '0x1UL'
export const UARTE_INTEN_DMATXREADY_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMATXREADY_Enabled: any = '0x1UL'
export const UARTE_INTEN_DMATXBUSERROR_Pos: any = '28UL'
export const UARTE_INTEN_DMATXBUSERROR_Msk: any = '0x1UL << UARTE_INTEN_DMATXBUSERROR_Pos'
export const UARTE_INTEN_DMATXBUSERROR_Min: any = '0x0UL'
export const UARTE_INTEN_DMATXBUSERROR_Max: any = '0x1UL'
export const UARTE_INTEN_DMATXBUSERROR_Disabled: any = '0x0UL'
export const UARTE_INTEN_DMATXBUSERROR_Enabled: any = '0x1UL'
export const UARTE_INTEN_FRAMETIMEOUT_Pos: any = '29UL'
export const UARTE_INTEN_FRAMETIMEOUT_Msk: any = '0x1UL << UARTE_INTEN_FRAMETIMEOUT_Pos'
export const UARTE_INTEN_FRAMETIMEOUT_Min: any = '0x0UL'
export const UARTE_INTEN_FRAMETIMEOUT_Max: any = '0x1UL'
export const UARTE_INTEN_FRAMETIMEOUT_Disabled: any = '0x0UL'
export const UARTE_INTEN_FRAMETIMEOUT_Enabled: any = '0x1UL'
export const UARTE_INTENSET_ResetValue: any = '0x00000000UL'
export const UARTE_INTENSET_CTS_Pos: any = '0UL'
export const UARTE_INTENSET_CTS_Msk: any = '0x1UL << UARTE_INTENSET_CTS_Pos'
export const UARTE_INTENSET_CTS_Min: any = '0x0UL'
export const UARTE_INTENSET_CTS_Max: any = '0x1UL'
export const UARTE_INTENSET_CTS_Set: any = '0x1UL'
export const UARTE_INTENSET_CTS_Disabled: any = '0x0UL'
export const UARTE_INTENSET_CTS_Enabled: any = '0x1UL'
export const UARTE_INTENSET_NCTS_Pos: any = '1UL'
export const UARTE_INTENSET_NCTS_Msk: any = '0x1UL << UARTE_INTENSET_NCTS_Pos'
export const UARTE_INTENSET_NCTS_Min: any = '0x0UL'
export const UARTE_INTENSET_NCTS_Max: any = '0x1UL'
export const UARTE_INTENSET_NCTS_Set: any = '0x1UL'
export const UARTE_INTENSET_NCTS_Disabled: any = '0x0UL'
export const UARTE_INTENSET_NCTS_Enabled: any = '0x1UL'
export const UARTE_INTENSET_TXDRDY_Pos: any = '3UL'
export const UARTE_INTENSET_TXDRDY_Msk: any = '0x1UL << UARTE_INTENSET_TXDRDY_Pos'
export const UARTE_INTENSET_TXDRDY_Min: any = '0x0UL'
export const UARTE_INTENSET_TXDRDY_Max: any = '0x1UL'
export const UARTE_INTENSET_TXDRDY_Set: any = '0x1UL'
export const UARTE_INTENSET_TXDRDY_Disabled: any = '0x0UL'
export const UARTE_INTENSET_TXDRDY_Enabled: any = '0x1UL'
export const UARTE_INTENSET_RXDRDY_Pos: any = '4UL'
export const UARTE_INTENSET_RXDRDY_Msk: any = '0x1UL << UARTE_INTENSET_RXDRDY_Pos'
export const UARTE_INTENSET_RXDRDY_Min: any = '0x0UL'
export const UARTE_INTENSET_RXDRDY_Max: any = '0x1UL'
export const UARTE_INTENSET_RXDRDY_Set: any = '0x1UL'
export const UARTE_INTENSET_RXDRDY_Disabled: any = '0x0UL'
export const UARTE_INTENSET_RXDRDY_Enabled: any = '0x1UL'
export const UARTE_INTENSET_ERROR_Pos: any = '5UL'
export const UARTE_INTENSET_ERROR_Msk: any = '0x1UL << UARTE_INTENSET_ERROR_Pos'
export const UARTE_INTENSET_ERROR_Min: any = '0x0UL'
export const UARTE_INTENSET_ERROR_Max: any = '0x1UL'
export const UARTE_INTENSET_ERROR_Set: any = '0x1UL'
export const UARTE_INTENSET_ERROR_Disabled: any = '0x0UL'
export const UARTE_INTENSET_ERROR_Enabled: any = '0x1UL'
export const UARTE_INTENSET_RXTO_Pos: any = '9UL'
export const UARTE_INTENSET_RXTO_Msk: any = '0x1UL << UARTE_INTENSET_RXTO_Pos'
export const UARTE_INTENSET_RXTO_Min: any = '0x0UL'
export const UARTE_INTENSET_RXTO_Max: any = '0x1UL'
export const UARTE_INTENSET_RXTO_Set: any = '0x1UL'
export const UARTE_INTENSET_RXTO_Disabled: any = '0x0UL'
export const UARTE_INTENSET_RXTO_Enabled: any = '0x1UL'
export const UARTE_INTENSET_TXSTOPPED_Pos: any = '12UL'
export const UARTE_INTENSET_TXSTOPPED_Msk: any = '0x1UL << UARTE_INTENSET_TXSTOPPED_Pos'
export const UARTE_INTENSET_TXSTOPPED_Min: any = '0x0UL'
export const UARTE_INTENSET_TXSTOPPED_Max: any = '0x1UL'
export const UARTE_INTENSET_TXSTOPPED_Set: any = '0x1UL'
export const UARTE_INTENSET_TXSTOPPED_Disabled: any = '0x0UL'
export const UARTE_INTENSET_TXSTOPPED_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMARXEND_Pos: any = '19UL'
export const UARTE_INTENSET_DMARXEND_Msk: any = '0x1UL << UARTE_INTENSET_DMARXEND_Pos'
export const UARTE_INTENSET_DMARXEND_Min: any = '0x0UL'
export const UARTE_INTENSET_DMARXEND_Max: any = '0x1UL'
export const UARTE_INTENSET_DMARXEND_Set: any = '0x1UL'
export const UARTE_INTENSET_DMARXEND_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMARXEND_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMARXREADY_Pos: any = '20UL'
export const UARTE_INTENSET_DMARXREADY_Msk: any = '0x1UL << UARTE_INTENSET_DMARXREADY_Pos'
export const UARTE_INTENSET_DMARXREADY_Min: any = '0x0UL'
export const UARTE_INTENSET_DMARXREADY_Max: any = '0x1UL'
export const UARTE_INTENSET_DMARXREADY_Set: any = '0x1UL'
export const UARTE_INTENSET_DMARXREADY_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMARXREADY_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMARXBUSERROR_Pos: any = '21UL'
export const UARTE_INTENSET_DMARXBUSERROR_Msk: any = '0x1UL << UARTE_INTENSET_DMARXBUSERROR_Pos'
export const UARTE_INTENSET_DMARXBUSERROR_Min: any = '0x0UL'
export const UARTE_INTENSET_DMARXBUSERROR_Max: any = '0x1UL'
export const UARTE_INTENSET_DMARXBUSERROR_Set: any = '0x1UL'
export const UARTE_INTENSET_DMARXBUSERROR_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMARXBUSERROR_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH0_Pos: any = '22UL'
export const UARTE_INTENSET_DMARXMATCH0_Msk: any = '0x1UL << UARTE_INTENSET_DMARXMATCH0_Pos'
export const UARTE_INTENSET_DMARXMATCH0_Min: any = '0x0UL'
export const UARTE_INTENSET_DMARXMATCH0_Max: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH0_Set: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH0_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMARXMATCH0_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH1_Pos: any = '23UL'
export const UARTE_INTENSET_DMARXMATCH1_Msk: any = '0x1UL << UARTE_INTENSET_DMARXMATCH1_Pos'
export const UARTE_INTENSET_DMARXMATCH1_Min: any = '0x0UL'
export const UARTE_INTENSET_DMARXMATCH1_Max: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH1_Set: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH1_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMARXMATCH1_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH2_Pos: any = '24UL'
export const UARTE_INTENSET_DMARXMATCH2_Msk: any = '0x1UL << UARTE_INTENSET_DMARXMATCH2_Pos'
export const UARTE_INTENSET_DMARXMATCH2_Min: any = '0x0UL'
export const UARTE_INTENSET_DMARXMATCH2_Max: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH2_Set: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH2_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMARXMATCH2_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH3_Pos: any = '25UL'
export const UARTE_INTENSET_DMARXMATCH3_Msk: any = '0x1UL << UARTE_INTENSET_DMARXMATCH3_Pos'
export const UARTE_INTENSET_DMARXMATCH3_Min: any = '0x0UL'
export const UARTE_INTENSET_DMARXMATCH3_Max: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH3_Set: any = '0x1UL'
export const UARTE_INTENSET_DMARXMATCH3_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMARXMATCH3_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMATXEND_Pos: any = '26UL'
export const UARTE_INTENSET_DMATXEND_Msk: any = '0x1UL << UARTE_INTENSET_DMATXEND_Pos'
export const UARTE_INTENSET_DMATXEND_Min: any = '0x0UL'
export const UARTE_INTENSET_DMATXEND_Max: any = '0x1UL'
export const UARTE_INTENSET_DMATXEND_Set: any = '0x1UL'
export const UARTE_INTENSET_DMATXEND_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMATXEND_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMATXREADY_Pos: any = '27UL'
export const UARTE_INTENSET_DMATXREADY_Msk: any = '0x1UL << UARTE_INTENSET_DMATXREADY_Pos'
export const UARTE_INTENSET_DMATXREADY_Min: any = '0x0UL'
export const UARTE_INTENSET_DMATXREADY_Max: any = '0x1UL'
export const UARTE_INTENSET_DMATXREADY_Set: any = '0x1UL'
export const UARTE_INTENSET_DMATXREADY_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMATXREADY_Enabled: any = '0x1UL'
export const UARTE_INTENSET_DMATXBUSERROR_Pos: any = '28UL'
export const UARTE_INTENSET_DMATXBUSERROR_Msk: any = '0x1UL << UARTE_INTENSET_DMATXBUSERROR_Pos'
export const UARTE_INTENSET_DMATXBUSERROR_Min: any = '0x0UL'
export const UARTE_INTENSET_DMATXBUSERROR_Max: any = '0x1UL'
export const UARTE_INTENSET_DMATXBUSERROR_Set: any = '0x1UL'
export const UARTE_INTENSET_DMATXBUSERROR_Disabled: any = '0x0UL'
export const UARTE_INTENSET_DMATXBUSERROR_Enabled: any = '0x1UL'
export const UARTE_INTENSET_FRAMETIMEOUT_Pos: any = '29UL'
export const UARTE_INTENSET_FRAMETIMEOUT_Msk: any = '0x1UL << UARTE_INTENSET_FRAMETIMEOUT_Pos'
export const UARTE_INTENSET_FRAMETIMEOUT_Min: any = '0x0UL'
export const UARTE_INTENSET_FRAMETIMEOUT_Max: any = '0x1UL'
export const UARTE_INTENSET_FRAMETIMEOUT_Set: any = '0x1UL'
export const UARTE_INTENSET_FRAMETIMEOUT_Disabled: any = '0x0UL'
export const UARTE_INTENSET_FRAMETIMEOUT_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_ResetValue: any = '0x00000000UL'
export const UARTE_INTENCLR_CTS_Pos: any = '0UL'
export const UARTE_INTENCLR_CTS_Msk: any = '0x1UL << UARTE_INTENCLR_CTS_Pos'
export const UARTE_INTENCLR_CTS_Min: any = '0x0UL'
export const UARTE_INTENCLR_CTS_Max: any = '0x1UL'
export const UARTE_INTENCLR_CTS_Clear: any = '0x1UL'
export const UARTE_INTENCLR_CTS_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_CTS_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_NCTS_Pos: any = '1UL'
export const UARTE_INTENCLR_NCTS_Msk: any = '0x1UL << UARTE_INTENCLR_NCTS_Pos'
export const UARTE_INTENCLR_NCTS_Min: any = '0x0UL'
export const UARTE_INTENCLR_NCTS_Max: any = '0x1UL'
export const UARTE_INTENCLR_NCTS_Clear: any = '0x1UL'
export const UARTE_INTENCLR_NCTS_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_NCTS_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_TXDRDY_Pos: any = '3UL'
export const UARTE_INTENCLR_TXDRDY_Msk: any = '0x1UL << UARTE_INTENCLR_TXDRDY_Pos'
export const UARTE_INTENCLR_TXDRDY_Min: any = '0x0UL'
export const UARTE_INTENCLR_TXDRDY_Max: any = '0x1UL'
export const UARTE_INTENCLR_TXDRDY_Clear: any = '0x1UL'
export const UARTE_INTENCLR_TXDRDY_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_TXDRDY_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_RXDRDY_Pos: any = '4UL'
export const UARTE_INTENCLR_RXDRDY_Msk: any = '0x1UL << UARTE_INTENCLR_RXDRDY_Pos'
export const UARTE_INTENCLR_RXDRDY_Min: any = '0x0UL'
export const UARTE_INTENCLR_RXDRDY_Max: any = '0x1UL'
export const UARTE_INTENCLR_RXDRDY_Clear: any = '0x1UL'
export const UARTE_INTENCLR_RXDRDY_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_RXDRDY_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_ERROR_Pos: any = '5UL'
export const UARTE_INTENCLR_ERROR_Msk: any = '0x1UL << UARTE_INTENCLR_ERROR_Pos'
export const UARTE_INTENCLR_ERROR_Min: any = '0x0UL'
export const UARTE_INTENCLR_ERROR_Max: any = '0x1UL'
export const UARTE_INTENCLR_ERROR_Clear: any = '0x1UL'
export const UARTE_INTENCLR_ERROR_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_ERROR_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_RXTO_Pos: any = '9UL'
export const UARTE_INTENCLR_RXTO_Msk: any = '0x1UL << UARTE_INTENCLR_RXTO_Pos'
export const UARTE_INTENCLR_RXTO_Min: any = '0x0UL'
export const UARTE_INTENCLR_RXTO_Max: any = '0x1UL'
export const UARTE_INTENCLR_RXTO_Clear: any = '0x1UL'
export const UARTE_INTENCLR_RXTO_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_RXTO_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_TXSTOPPED_Pos: any = '12UL'
export const UARTE_INTENCLR_TXSTOPPED_Msk: any = '0x1UL << UARTE_INTENCLR_TXSTOPPED_Pos'
export const UARTE_INTENCLR_TXSTOPPED_Min: any = '0x0UL'
export const UARTE_INTENCLR_TXSTOPPED_Max: any = '0x1UL'
export const UARTE_INTENCLR_TXSTOPPED_Clear: any = '0x1UL'
export const UARTE_INTENCLR_TXSTOPPED_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_TXSTOPPED_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMARXEND_Pos: any = '19UL'
export const UARTE_INTENCLR_DMARXEND_Msk: any = '0x1UL << UARTE_INTENCLR_DMARXEND_Pos'
export const UARTE_INTENCLR_DMARXEND_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMARXEND_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMARXEND_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMARXEND_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMARXEND_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMARXREADY_Pos: any = '20UL'
export const UARTE_INTENCLR_DMARXREADY_Msk: any = '0x1UL << UARTE_INTENCLR_DMARXREADY_Pos'
export const UARTE_INTENCLR_DMARXREADY_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMARXREADY_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMARXREADY_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMARXREADY_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMARXREADY_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMARXBUSERROR_Pos: any = '21UL'
export const UARTE_INTENCLR_DMARXBUSERROR_Msk: any = '0x1UL << UARTE_INTENCLR_DMARXBUSERROR_Pos'
export const UARTE_INTENCLR_DMARXBUSERROR_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMARXBUSERROR_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMARXBUSERROR_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMARXBUSERROR_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMARXBUSERROR_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH0_Pos: any = '22UL'
export const UARTE_INTENCLR_DMARXMATCH0_Msk: any = '0x1UL << UARTE_INTENCLR_DMARXMATCH0_Pos'
export const UARTE_INTENCLR_DMARXMATCH0_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMARXMATCH0_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH0_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH0_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMARXMATCH0_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH1_Pos: any = '23UL'
export const UARTE_INTENCLR_DMARXMATCH1_Msk: any = '0x1UL << UARTE_INTENCLR_DMARXMATCH1_Pos'
export const UARTE_INTENCLR_DMARXMATCH1_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMARXMATCH1_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH1_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH1_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMARXMATCH1_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH2_Pos: any = '24UL'
export const UARTE_INTENCLR_DMARXMATCH2_Msk: any = '0x1UL << UARTE_INTENCLR_DMARXMATCH2_Pos'
export const UARTE_INTENCLR_DMARXMATCH2_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMARXMATCH2_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH2_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH2_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMARXMATCH2_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH3_Pos: any = '25UL'
export const UARTE_INTENCLR_DMARXMATCH3_Msk: any = '0x1UL << UARTE_INTENCLR_DMARXMATCH3_Pos'
export const UARTE_INTENCLR_DMARXMATCH3_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMARXMATCH3_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH3_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMARXMATCH3_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMARXMATCH3_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMATXEND_Pos: any = '26UL'
export const UARTE_INTENCLR_DMATXEND_Msk: any = '0x1UL << UARTE_INTENCLR_DMATXEND_Pos'
export const UARTE_INTENCLR_DMATXEND_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMATXEND_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMATXEND_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMATXEND_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMATXEND_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMATXREADY_Pos: any = '27UL'
export const UARTE_INTENCLR_DMATXREADY_Msk: any = '0x1UL << UARTE_INTENCLR_DMATXREADY_Pos'
export const UARTE_INTENCLR_DMATXREADY_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMATXREADY_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMATXREADY_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMATXREADY_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMATXREADY_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_DMATXBUSERROR_Pos: any = '28UL'
export const UARTE_INTENCLR_DMATXBUSERROR_Msk: any = '0x1UL << UARTE_INTENCLR_DMATXBUSERROR_Pos'
export const UARTE_INTENCLR_DMATXBUSERROR_Min: any = '0x0UL'
export const UARTE_INTENCLR_DMATXBUSERROR_Max: any = '0x1UL'
export const UARTE_INTENCLR_DMATXBUSERROR_Clear: any = '0x1UL'
export const UARTE_INTENCLR_DMATXBUSERROR_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_DMATXBUSERROR_Enabled: any = '0x1UL'
export const UARTE_INTENCLR_FRAMETIMEOUT_Pos: any = '29UL'
export const UARTE_INTENCLR_FRAMETIMEOUT_Msk: any = '0x1UL << UARTE_INTENCLR_FRAMETIMEOUT_Pos'
export const UARTE_INTENCLR_FRAMETIMEOUT_Min: any = '0x0UL'
export const UARTE_INTENCLR_FRAMETIMEOUT_Max: any = '0x1UL'
export const UARTE_INTENCLR_FRAMETIMEOUT_Clear: any = '0x1UL'
export const UARTE_INTENCLR_FRAMETIMEOUT_Disabled: any = '0x0UL'
export const UARTE_INTENCLR_FRAMETIMEOUT_Enabled: any = '0x1UL'
export const UARTE_ERRORSRC_ResetValue: any = '0x00000000UL'
export const UARTE_ERRORSRC_OVERRUN_Pos: any = '0UL'
export const UARTE_ERRORSRC_OVERRUN_Msk: any = '0x1UL << UARTE_ERRORSRC_OVERRUN_Pos'
export const UARTE_ERRORSRC_OVERRUN_Min: any = '0x0UL'
export const UARTE_ERRORSRC_OVERRUN_Max: any = '0x1UL'
export const UARTE_ERRORSRC_OVERRUN_NotPresent: any = '0x0UL'
export const UARTE_ERRORSRC_OVERRUN_Present: any = '0x1UL'
export const UARTE_ERRORSRC_PARITY_Pos: any = '1UL'
export const UARTE_ERRORSRC_PARITY_Msk: any = '0x1UL << UARTE_ERRORSRC_PARITY_Pos'
export const UARTE_ERRORSRC_PARITY_Min: any = '0x0UL'
export const UARTE_ERRORSRC_PARITY_Max: any = '0x1UL'
export const UARTE_ERRORSRC_PARITY_NotPresent: any = '0x0UL'
export const UARTE_ERRORSRC_PARITY_Present: any = '0x1UL'
export const UARTE_ERRORSRC_FRAMING_Pos: any = '2UL'
export const UARTE_ERRORSRC_FRAMING_Msk: any = '0x1UL << UARTE_ERRORSRC_FRAMING_Pos'
export const UARTE_ERRORSRC_FRAMING_Min: any = '0x0UL'
export const UARTE_ERRORSRC_FRAMING_Max: any = '0x1UL'
export const UARTE_ERRORSRC_FRAMING_NotPresent: any = '0x0UL'
export const UARTE_ERRORSRC_FRAMING_Present: any = '0x1UL'
export const UARTE_ERRORSRC_BREAK_Pos: any = '3UL'
export const UARTE_ERRORSRC_BREAK_Msk: any = '0x1UL << UARTE_ERRORSRC_BREAK_Pos'
export const UARTE_ERRORSRC_BREAK_Min: any = '0x0UL'
export const UARTE_ERRORSRC_BREAK_Max: any = '0x1UL'
export const UARTE_ERRORSRC_BREAK_NotPresent: any = '0x0UL'
export const UARTE_ERRORSRC_BREAK_Present: any = '0x1UL'
export const UARTE_ENABLE_ResetValue: any = '0x00000000UL'
export const UARTE_ENABLE_ENABLE_Pos: any = '0UL'
export const UARTE_ENABLE_ENABLE_Msk: any = '0xFUL << UARTE_ENABLE_ENABLE_Pos'
export const UARTE_ENABLE_ENABLE_Min: any = '0x0UL'
export const UARTE_ENABLE_ENABLE_Max: any = '0x8UL'
export const UARTE_ENABLE_ENABLE_Disabled: any = '0x0UL'
export const UARTE_ENABLE_ENABLE_Enabled: any = '0x8UL'
export const UARTE_BAUDRATE_ResetValue: any = '0x04000000UL'
export const UARTE_BAUDRATE_BAUDRATE_Pos: any = '0UL'
export const UARTE_BAUDRATE_BAUDRATE_Msk: any = '0xFFFFFFFFUL << UARTE_BAUDRATE_BAUDRATE_Pos'
export const UARTE_BAUDRATE_BAUDRATE_Min: any = '0x4F000UL'
export const UARTE_BAUDRATE_BAUDRATE_Max: any = '0x10000000UL'
export const UARTE_BAUDRATE_BAUDRATE_Baud1200: any = '0x0004F000UL) /*!< 1200 baud (actual rate: 1205'
export const UARTE_BAUDRATE_BAUDRATE_Baud2400: any = '0x0009D000UL) /*!< 2400 baud (actual rate: 2396'
export const UARTE_BAUDRATE_BAUDRATE_Baud4800: any = '0x0013B000UL) /*!< 4800 baud (actual rate: 4808'
export const UARTE_BAUDRATE_BAUDRATE_Baud9600: any = '0x00275000UL) /*!< 9600 baud (actual rate: 9598'
export const UARTE_BAUDRATE_BAUDRATE_Baud14400: any = '0x003AF000UL) /*!< 14400 baud (actual rate: 14401'
export const UARTE_BAUDRATE_BAUDRATE_Baud19200: any = '0x004EA000UL) /*!< 19200 baud (actual rate: 19208'
export const UARTE_BAUDRATE_BAUDRATE_Baud28800: any = '0x0075C000UL) /*!< 28800 baud (actual rate: 28777'
export const UARTE_BAUDRATE_BAUDRATE_Baud31250: any = '0x00800000UL'
export const UARTE_BAUDRATE_BAUDRATE_Baud38400: any = '0x009D0000UL) /*!< 38400 baud (actual rate: 38369'
export const UARTE_BAUDRATE_BAUDRATE_Baud56000: any = '0x00E50000UL) /*!< 56000 baud (actual rate: 55944'
export const UARTE_BAUDRATE_BAUDRATE_Baud57600: any = '0x00EB0000UL) /*!< 57600 baud (actual rate: 57554'
export const UARTE_BAUDRATE_BAUDRATE_Baud76800: any = '0x013A9000UL) /*!< 76800 baud (actual rate: 76923'
export const UARTE_BAUDRATE_BAUDRATE_Baud115200: any = '0x01D60000UL) /*!< 115200 baud (actual rate: 115108'
export const UARTE_BAUDRATE_BAUDRATE_Baud230400: any = '0x03B00000UL) /*!< 230400 baud (actual rate: 231884'
export const UARTE_BAUDRATE_BAUDRATE_Baud250000: any = '0x04000000UL'
export const UARTE_BAUDRATE_BAUDRATE_Baud460800: any = '0x07400000UL) /*!< 460800 baud (actual rate: 457143'
export const UARTE_BAUDRATE_BAUDRATE_Baud921600: any = '0x0F000000UL) /*!< 921600 baud (actual rate: 941176'
export const UARTE_BAUDRATE_BAUDRATE_Baud1M: any = '0x10000000UL'
export const UARTE_CONFIG_ResetValue: any = '0x00001000UL'
export const UARTE_CONFIG_HWFC_Pos: any = '0UL'
export const UARTE_CONFIG_HWFC_Msk: any = '0x1UL << UARTE_CONFIG_HWFC_Pos'
export const UARTE_CONFIG_HWFC_Min: any = '0x0UL'
export const UARTE_CONFIG_HWFC_Max: any = '0x1UL'
export const UARTE_CONFIG_HWFC_Disabled: any = '0x0UL'
export const UARTE_CONFIG_HWFC_Enabled: any = '0x1UL'
export const UARTE_CONFIG_PARITY_Pos: any = '1UL'
export const UARTE_CONFIG_PARITY_Msk: any = '0x7UL << UARTE_CONFIG_PARITY_Pos'
export const UARTE_CONFIG_PARITY_Min: any = '0x0UL'
export const UARTE_CONFIG_PARITY_Max: any = '0x7UL'
export const UARTE_CONFIG_PARITY_Excluded: any = '0x0UL'
export const UARTE_CONFIG_PARITY_Included: any = '0x7UL'
export const UARTE_CONFIG_STOP_Pos: any = '4UL'
export const UARTE_CONFIG_STOP_Msk: any = '0x1UL << UARTE_CONFIG_STOP_Pos'
export const UARTE_CONFIG_STOP_Min: any = '0x0UL'
export const UARTE_CONFIG_STOP_Max: any = '0x1UL'
export const UARTE_CONFIG_STOP_One: any = '0x0UL'
export const UARTE_CONFIG_STOP_Two: any = '0x1UL'
export const UARTE_CONFIG_PARITYTYPE_Pos: any = '8UL'
export const UARTE_CONFIG_PARITYTYPE_Msk: any = '0x1UL << UARTE_CONFIG_PARITYTYPE_Pos'
export const UARTE_CONFIG_PARITYTYPE_Min: any = '0x0UL'
export const UARTE_CONFIG_PARITYTYPE_Max: any = '0x1UL'
export const UARTE_CONFIG_PARITYTYPE_Even: any = '0x0UL'
export const UARTE_CONFIG_PARITYTYPE_Odd: any = '0x1UL'
export const UARTE_CONFIG_FRAMESIZE_Pos: any = '9UL'
export const UARTE_CONFIG_FRAMESIZE_Msk: any = '0xFUL << UARTE_CONFIG_FRAMESIZE_Pos'
export const UARTE_CONFIG_FRAMESIZE_Min: any = '0x4UL'
export const UARTE_CONFIG_FRAMESIZE_Max: any = '0x9UL'
export const UARTE_CONFIG_FRAMESIZE_9bit: any = '0x9UL'
export const UARTE_CONFIG_FRAMESIZE_8bit: any = '0x8UL'
export const UARTE_CONFIG_FRAMESIZE_7bit: any = '0x7UL'
export const UARTE_CONFIG_FRAMESIZE_6bit: any = '0x6UL'
export const UARTE_CONFIG_FRAMESIZE_5bit: any = '0x5UL'
export const UARTE_CONFIG_FRAMESIZE_4bit: any = '0x4UL'
export const UARTE_CONFIG_ENDIAN_Pos: any = '13UL'
export const UARTE_CONFIG_ENDIAN_Msk: any = '0x1UL << UARTE_CONFIG_ENDIAN_Pos'
export const UARTE_CONFIG_ENDIAN_Min: any = '0x0UL'
export const UARTE_CONFIG_ENDIAN_Max: any = '0x1UL'
export const UARTE_CONFIG_ENDIAN_MSB: any = '0x0UL'
export const UARTE_CONFIG_ENDIAN_LSB: any = '0x1UL'
export const UARTE_CONFIG_FRAMETIMEOUT_Pos: any = '14UL'
export const UARTE_CONFIG_FRAMETIMEOUT_Msk: any = '0x1UL << UARTE_CONFIG_FRAMETIMEOUT_Pos'
export const UARTE_CONFIG_FRAMETIMEOUT_Min: any = '0x0UL'
export const UARTE_CONFIG_FRAMETIMEOUT_Max: any = '0x1UL'
export const UARTE_CONFIG_FRAMETIMEOUT_DISABLED: any = '0x0UL'
export const UARTE_CONFIG_FRAMETIMEOUT_ENABLED: any = '0x1UL'
export const UARTE_CONFIG_FRAMETIMEOUT_Disabled: any = '0x0UL'
export const UARTE_CONFIG_FRAMETIMEOUT_Enabled: any = '0x1UL'
export const UARTE_ADDRESS_ResetValue: any = '0x00000000UL'
export const UARTE_ADDRESS_ADDRESS_Pos: any = '0UL'
export const UARTE_ADDRESS_ADDRESS_Msk: any = '0xFFUL << UARTE_ADDRESS_ADDRESS_Pos'
export const UARTE_FRAMETIMEOUT_ResetValue: any = '0x00000010UL'
export const UARTE_FRAMETIMEOUT_COUNTERTOP_Pos: any = '0UL'
export const UARTE_FRAMETIMEOUT_COUNTERTOP_Msk: any = '0x3FFUL << UARTE_FRAMETIMEOUT_COUNTERTOP_Pos'

// -------- INSTANCES -------- //

export const P0 = {} as GPIO_t
export const P1 = {} as GPIO_t
export const P2 = {} as GPIO_t
export const UARTE30 = {} as UARTE_t

// -------- INDICIES -------- //

export const P = [] as GPIO_t[]
